apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-postgres

manifests:
  kustomize:
    paths:
      - deploy/postgres/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-migrations

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/plans-migrations
      context: migrations
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - deploy/migrations/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-api

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/plans-api
      context: api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - deploy/api/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-relay

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/relay
      context: ../../platform/runtime/relay
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - deploy/relay/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-accounts-projection

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/plans-accounts-projection
      context: accounts-projection
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - deploy/accounts-projection/overlays/ephemeral

deploy:
  kubectl: {}
