apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-postgres

manifests:
  kustomize:
    paths:
      - infra/postgres/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-migrations

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/plans-migrations
      context: components/migrations
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - components/migrations/infra/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-api

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/plans-api
      context: components/api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/api/infra/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-outbox

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/plans-outbox
      context: components/outbox
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/outbox/infra/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-accounts-projection

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/plans-accounts-projection
      context: components/accounts-projection
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/accounts-projection/infra/overlays/ephemeral

deploy:
  kubectl: {}
