CREATE ROLE capabilities_migrator
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

CREATE ROLE capabilities_api
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

CREATE ROLE capabilities_worker
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

REVOKE CONNECT, TEMPORARY ON DATABASE capabilities FROM PUBLIC;

GRANT CONNECT, CREATE, TEMPORARY
ON DATABASE capabilities
TO capabilities_migrator;

GRANT CONNECT
ON DATABASE capabilities
TO capabilities_api,
   capabilities_worker;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;

GRANT USAGE, CREATE
ON SCHEMA public
TO capabilities_migrator;

GRANT USAGE
ON SCHEMA public
TO capabilities_api,
   capabilities_worker;
