apiVersion: apps/v1
kind: Deployment

metadata:
  name: traefik-depl
spec:
  selector:
    matchLabels:
      app: traefik
  replicas: 1
  template:
    spec:
      affinity: null
      containers:
        - name: traefik
          args:
            #
            # https://doc.traefik.io/traefik/operations/dashboard/
            #
            - --api=true
            - --api.dashboard=true
            #
            - --accesslog=true
            #
            #
            - --entrypoints.http.address=:80/tcp
            - --entrypoints.https.address=:443/tcp
            #
            #
            - --ping=true
            - --ping.entryPoint=http
            #
            #
            - --providers.kubernetescrd=true
            #
            # accept IngressRoutes that reference a Service that might not exist at deployment time (useful for zero-downtime deployments)
            #
            - --providers.kubernetescrd.allowEmptyServices=true
            #
            # Plugins
            #
            - --experimental.plugins.jwt.moduleName=github.com/traefik-plugins/traefik-jwt-plugin
            - --experimental.plugins.jwt.version=v0.10.0
