apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: accounts
resources:
  - ../../base
  - networkpolicy.yaml
configMapGenerator:
  - name: outbox-relay-streams
    files:
      - streams.json
patches:
  - path: deployment.yaml
images:
  - name: ghcr.io/mstaicu/outbox-relay
    newTag: latest
    digest: sha256:e358ab8cc6677bd345ab4f21f987a6344eda5c0771594e336be21fdf728769df # {"$imagepolicy": "flux-system:outbox-relay:digest"}
