#
# helm repo update
# helm template linkerd-crd linkerd/linkerd-crds --set installGatewayAPI=true > linkerd-crd.yaml
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - linkerd-crds.yaml
