apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: nats
  serviceName: nats-headless
  template:
    metadata:
      labels:
        app: nats
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nats
              topologyKey: kubernetes.io/hostname
      enableServiceLinks: false
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: nats
          image: docker.io/nats:2.12.1-alpine
          args:
            - --config
            - /etc/nats-config/nats.conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_NAME
              value: $(POD_NAME)

          volumeMounts:
            - mountPath: /etc/nats-config
              name: config

          ports:
            - containerPort: 4222
              name: nats
            - containerPort: 8222
              name: monitor

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz?js-enabled-only=true
              port: monitor
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz?js-server-only=true
              port: monitor
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 90
            httpGet:
              path: /healthz
              port: monitor
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: config
          configMap:
            name: nats-config
