apiVersion: apps/v1
kind: Deployment

metadata:
  name: traefik-depl
spec:
  selector:
    matchLabels:
      app: traefik
  replicas: 3
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        linkerd.io/inject: disabled
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - traefik
              topologyKey: kubernetes.io/hostname
      serviceAccountName: traefik-controller
      containers:
        - name: traefik
          image: traefik:v3.4
          args:
            - --accesslog
            - --log.level=INFO
            - --providers.kubernetesgateway
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --metrics.prometheus=true
            - --ping=true
            - --ping.entrypoint=web
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
