apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base
  - identity-ui-public-ingressroute.yaml

patches:
  - path: identity-ui-deployment.yaml

images:
  - name: ghcr.io/mstaicu/identity-ui
    newTag: latest
