apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base
  - identity-ui-ingress.yaml

patches:
  - path: identity-ui-depl.yaml

images:
  - name: ghcr.io/mstaicu/identity-ui
    newTag: latest # {"$imagepolicy": "flux-system:identity-ui:tag"}
    digest: "" # {"$imagepolicy": "flux-system:identity-ui:digest"}
