apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - ../../base
  - service.yaml

configMapGenerator:
  - name: dashboard
    literals:
      - |
        dashboard.yaml=http:
          routers:
            dashboard:
              entryPoints:
                - http
              rule: PathPrefix(`/api`) || PathPrefix(`/dashboard`)
              service: api@internal

patches:
  - path: deployment.yaml
