apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository

metadata:
  name: aperitif-repo
  namespace: flux-system
spec:
  url: ssh://git@github.com/mstaicu/aperitif.git
  ref:
    branch: master
  interval: 1m
  secretRef:
    name: github-ssh
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
  path: ./k8s/infra/traefik/crd
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-depl
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
  path: ./k8s/infra/traefik/overlays/prod
  dependsOn:
    - name: traefik-crds
  #
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  #
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traefik-depl
      namespace: traefik
    - apiVersion: v1
      kind: Service
      name: traefik-lb
      namespace: traefik
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
