apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  path: ./k8s/infra/traefik/crd
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-depl
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  path: ./k8s/infra/traefik/overlays/dev
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
  dependsOn:
    - name: traefik-crds
    # - name: linkerd-control-plane
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traefik-depl
      namespace: traefik
    - apiVersion: v1
      kind: Service
      name: traefik-lb
      namespace: traefik
