apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenancy

resources:
  - namespace.yaml
  - ../../base

generators:
  - tenancy-worker-ksops-generator.yaml

patches:
  - path: tenancy-worker-depl.yaml
