apiVersion: v1
kind: Secret
metadata:
    name: tenancy-worker-db
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:HAq6scKiLHElreR9E1T+RFIwiHkx41UNE0kXpCD4wQ8MemZJVIL5kcRBnI420g7y1LvORUCWdsT4tAXft4c3eCi0pEBW3ZA=,iv:L9/yeFPs8nLk92Oh+suQa/sU3zJ8kyscvddKhnsDPnQ=,tag:utHO7A6uxgMBq2M43LbzEQ==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTnhiK2hPZVRkc1dzczJm
            NStMT1YxYkZKZ0Z3NXVwT09NY0RJTks0N0hzCmMwRVZqK0NxV0R0OXd3dHFyTnRj
            Y1hzeEkrbDcxbjRiNWFhUTJnL2o2OG8KLS0tIEJwZEs1WGllejFXUkJpWTJKN2VZ
            Wm1uSEVPcWdYQ0VBbXhMenh3d2pGR1kKKH7R6tyM2EJkP6B7aBlAyPqYHRkj/+40
            NQYr9tRYq7e+W9gEKX9jugKCz5spQM0aTUIPiVWJdoWBmpz8V+l+fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T18:53:55Z"
    mac: ENC[AES256_GCM,data:Zv/s5Y/qJdMmRoM7Ilr4zmHr+m6o1I0A8l0xLPfFKOGXPLH1Vqi0VDbmYSNsjAzlU9dHnDUci7tMg4jHWDlSQaW2bYMZNjewftP5hOoAXCQX3Maw/KJEnu45/npDJZQLPUHzRuGqFx2qybbKGjCGpBA3iexeCV+wXWPhL0S0CHY=,iv:WpRwdaTKPzS69APOeCp3wE47t4MEYX/oM7qyCAlu9oM=,tag:LD/uFiRFcSwgu270YEwpuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
