apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: documents

resources:
  - namespace.yaml
  - ../../base
  - documents-api-ingress.yaml

patches:
  - path: documents-api-depl.yaml

images:
  - name: mdstaicu/documents-api
    newTag: latest
