apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-depl
spec:
  volumeClaimTemplates:
    - metadata:
        name: nats-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
