apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: entitlements-api-internal
spec:
  entryPoints:
    - http

  routes:
    - kind: Rule
      match: PathPrefix(`/v1/entitlements`)
      services:
        - name: entitlements-api
          port: 3000
