apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - entitlements-api-internal-ingressroute.yaml
  - entitlements-api-networkpolicy.yaml
  - entitlements-api-deployment.yaml
  - entitlements-api-service.yaml
