apiVersion: v1
kind: Secret
metadata:
    name: capabilities-migrate-db
stringData:
    FLYWAY_URL: ENC[AES256_GCM,data:Atlw5m4LmdtExXghAweb8sA7HvtIVP8VLjfnyucPsN1PzYaYUunxflLUyAOaw7S5mXAg86YG00/3KoNypF5R/A==,iv:E2pZO3/yxALnIQ/HAhPiKKNDVAI9Kbb7ZUZuAunm94Q=,tag:vdoD/NKV0xDeEqRITIhjQg==,type:str]
    FLYWAY_USER: ENC[AES256_GCM,data:L5O9k5iL9x3d82iCWiL6Uur7wmN9,iv:Nk8YrvQJu6yxi6EgDgHMHnJAWjnXFStjYk3oYf6g63Q=,tag:sDGs60m/ebzIdi5bLQ1XXA==,type:str]
    FLYWAY_PASSWORD: ENC[AES256_GCM,data:yaAe,iv:K5GSlnvti/GUSDOo3fz5hzOZEMgDBIjTqoHlouSVrEA=,tag:9/+s4ZVjW/oPbnrI+2g0Rw==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGNNVWw3STloVUxjd2cw
            WThTKzRtWW1kYmZkQUhkakRWUGc0VzRuWERjCmtQMHlTSHBwbEF3R1BKMmIxclFQ
            YlVDblhaVWVqdlh4azNiMDZYSUFxa3MKLS0tIHpBeWFiNWRTZkR4VW54UDRZTzlR
            R3IyRGlHYVdEeVB2dmFXN3VNa2pvNmsKdaiPSaF44cQajSgHgRfeoVI+0FQpaXjG
            dTt09aq5D0cPGui4YKa7jN7CVLP7ljzhGdRriT8NMh7sSw2eLbG5aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T16:25:15Z"
    mac: ENC[AES256_GCM,data:meiy7F6/OduGvLAAgG+1Hpm9T5qQuB1SxwGjMun40Kti+JzOIy/vH15BQtkHQQ7P6IcMmtuHKrhBVsKhdLgCPvO8mitC4ydokueWf4L6we63KAjfYNjK5S1Cjhy1vnZzc8Eoh07Qs9QUW/X1nen/7MbKKUdQZbRZ7iZH1dQucRA=,iv:q7Z0YWncecNtf+9U2Oqw4tMmWYqD0SY96pxpil+ferk=,tag:3zEqd3Zreo5YHw3RluktfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
