apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: secret-manager-serviceaccount
roleRef:
  kind: Role
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io
