apiVersion: batch/v1
kind: CronJob

metadata:
  name: identity-cleanup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup
              env:
                - name: DATABASE_URL
                  value: "postgres://postgres:postgres@identity-postgres:5432/identity"
