apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spaces

resources:
  - spaces-api-ingress.yaml
  - spaces-np.yaml
  - spaces-api-depl.yaml
  - spaces-api-sa.yaml
  - spaces-api-srv.yaml
  - spaces-ns.yaml
