apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mdstaicu/auth
          envFrom:
            - secretRef:
                name: dotenv
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            #
            # Total first probe time, worst case, 15s
            # Total second probe time, worst case, 15s
            #
            # Pod is restarted after 30s, worst case,
            # because the first probe fails after 15s,
            # and the second probe fails after 15s, totally 2 time failures
            # thus triggering a pod restart after 30s
            #
            # 1. first probe is sent after 10 seconds
            initialDelaySeconds: 10
            # 3. we then wait another 10 seconds, we send a probe, we wait 5 seconds
            periodSeconds: 10
            # 2. we then wait 5 seconds
            timeoutSeconds: 5
            # restart the pod after this many probe failures
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            #
            # Total first probe time, worst case, 15s
            # Total second probe time, worst case, 15s
            #
            # Pod is restarted after 30s, worst case,
            # because the first probe fails after 15s,
            # and the second probe fails after 15s, totally 2 time failures
            # thus triggering a pod restart after 30s
            #
            # 1. first probe is sent after 10 seconds
            initialDelaySeconds: 10
            # 3. we then wait another 10 seconds, we send a probe, we wait 5 seconds
            periodSeconds: 10
            # 2. we then wait 5 seconds
            timeoutSeconds: 5
            # restart the pod after this many probe failures
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
