apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass

metadata:
  name: traefik-gwc
spec:
  controllerName: traefik.io/gateway-controller

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: traefik-pgw
  namespace: traefik
  annotations:
    traefik.io/tls.certresolver: le
spec:
  gatewayClassName: traefik-gwc

  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: tma.com

      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: traefik-igw
  namespace: traefik
spec:
  gatewayClassName: traefik-gwc

  listeners:
    - name: http
      port: 80
      protocol: HTTP

      allowedRoutes:
        namespaces:
          from: All
