service: serverless-aws-node
provider:
  name: aws
  runtime: nodejs12.x
  provider: serverless
  # you can overwrite defaults here
  stage: prod
  #  region: us-east-1
  #
  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - Fn::Join:
            - ':'
            - - arn:aws:lambda
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - function:${self:service}-${opt:stage, self:provider.stage}-*

functions:
  hello:
    handler: src/api/handler.hello
    events:
      - http:
          path: /hello
          # method ANY instructs this endpoint to receive all request method types
          method: ANY
          cors: true
    warmup:
      # Specify for which stage we want to keep this function warm
      enabled: prod

plugins:
  - serverless-offline
  - serverless-plugin-warmup

custom:
  warmup:
    default:
      name: 'lambda warmer🔥'
      prewarm: true
      concurrency: 2
