apiVersion: apps/v1
kind: Deployment

metadata:
  name: tenancy-postgres-depl
spec:
  template:
    spec:
      containers:
        - name: tenancy-postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres

          volumeMounts:
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/001-tenancy-init.sql
              subPath: tenancy-postgres-init.sql
              readOnly: true

      volumes:
        - name: postgres-init
          configMap:
            name: tenancy-postgres-init
