apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nats

resources:
  - ../../base
  - nats-ns.yaml

configMapGenerator:
  - name: nats-conf-cm
    files:
      - nats-server.conf=nats-server.conf

patches:
  - path: nats-depl.yaml
