apiVersion: v1
kind: ServiceAccount
metadata:
  name: jetstream-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jetstream-controller-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - jetstream.nats.io
    resources:
      - streams
      - streams/status
      - consumers
      - consumers/status
      - streamtemplates
      - streamtemplates/status
      - accounts
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jetstream-controller-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: jetstream-controller
roleRef:
  kind: ClusterRole
  name: jetstream-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nack
spec:
  selector:
    matchLabels:
      app: nack

  replicas: 1

  template:
    metadata:
      labels:
        app: nack
    spec:
      serviceAccountName: jetstream-controller
      initContainers:
        - name: wait-for-nats
          image: natsio/nats-box:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking DNS for NATS JetStream readiness..."
              until nslookup nats-depl-0.nats-headless && 
                    nslookup nats-depl-1.nats-headless && 
                    nslookup nats-depl-2.nats-headless; do
                echo "Waiting for NATS JetStream DNS entries..."
                sleep 5
              done
              echo "DNS entries found. Checking NATS readiness..."
              until nats pub test hi -s nats://nats-depl-0.nats-headless:4222 &&
                    nats pub test hi -s nats://nats-depl-1.nats-headless:4222 &&
                    nats pub test hi -s nats://nats-depl-2.nats-headless:4222; do
                echo "Waiting for NATS JetStream to be ready..."
                sleep 5
              done
              echo "NATS JetStream is ready!"
      containers:
        - name: nack
          image: natsio/jetstream-controller:0.16.0
          command:
            - /jetstream-controller
          args:
            - -s=nats://mircea:mircea@nats-depl-0.nats-headless:4222,nats://mircea:mircea@nats-depl-1.nats-headless:4222,nats://mircea:mircea@nats-depl-2.nats-headless:4222
          volumeMounts:
            - name: runtime
              mountPath: /nack
      volumes:
        - name: runtime
          emptyDir: {}
