apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: nats
  serviceName: nats-headless
  template:
    metadata:
      labels:
        app: nats
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nats
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
        - name: nats
          image: nats:alpine
          args: ["-c", "/etc/nats/nats-server.conf"]
          ports:
            - name: nats-client
              containerPort: 4222
            - name: nats-cluster
              containerPort: 6222
            - name: nats-monitor
              containerPort: 8222
          volumeMounts:
            - name: nats-server-cm
              mountPath: /etc/nats/
          readinessProbe:
            httpGet:
              path: /healthz?js-server-only=true
              port: nats-monitor
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz?js-enabled-only=true
              port: nats-monitor
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: nats-monitor
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 90
      volumes:
        - name: nats-server-cm
          configMap:
            name: nats-cm
