# Cluster specific service
apiVersion: v1
kind: Service

metadata:
  name: nats-headless
spec:
  clusterIP: None
  selector:
    app: nats
  publishNotReadyAddresses: true
  ports:
    - name: nats-cluster
      protocol: TCP
      port: 6222
      targetPort: 6222
    - name: nats-monitor
      protocol: TCP
      appProtocol: HTTP
      port: 8222
      targetPort: 8222
---
# Client specific service
apiVersion: v1
kind: Service

metadata:
  name: nats
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - name: nats
      protocol: TCP
      port: 4222
      targetPort: 4222
