apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: auth-postgres

manifests:
  kustomize:
    paths:
      - infra/postgres/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: auth-migrations

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/auth-migrations
      context: components/migrations
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - components/migrations/infra/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: auth-api

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/auth-api
      context: components/api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/api/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: auth-ui

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/auth-ui
      context: components/ui
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/ui/infra/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: auth-cleanup

manifests:
  kustomize:
    paths:
      - components/cleanup/infra/overlays/ephemeral

deploy:
  kubectl: {}
