apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plans

resources:
  - ../../base

patches:
  - path: accounts-projector-deployment.yaml

images:
  - name: ghcr.io/mstaicu/plans-accounts-projector
    newTag: latest
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000 # {"$imagepolicy": "flux-system:plans-accounts-projector:digest"}
