apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-api-depl
spec:
  selector:
    matchLabels:
      app: auth-api
  replicas: 3
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#more-practical-use-cases
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - auth-api
              topologyKey: kubernetes.io/hostname
      containers:
        - name: auth-api
          image: mdstaicu/auth-api
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: auth-api-cm
                  key: MONGO_DB_URI
            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: auth-api-cm
                  key: ORIGIN
            - name: JWT_PRIVATE_KEY_PATH
              value: /app/keys/jwt-private.key
            - name: JWT_PUBLIC_KEY_PATH
              value: /app/keys/jwt-public.pub

          volumeMounts:
            - name: auth-api-jwt
              mountPath: /app/keys
              readOnly: true
            - name: auth-api-nats-creds
              mountPath: /nats
          #
          # total probe time =
          #     initialDelay + timeout + ( (periodSeconds + timeout) * (failureThreshold - 1) )
          #
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
      volumes:
        - name: auth-api-jwt
          secret:
            secretName: auth-api-jwt
        - name: auth-api-nats-creds
          secret:
            secretName: auth-api-nats.creds