apiVersion: apps/v1
kind: Deployment

metadata:
  name: plans-api
spec:
  template:
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: plans-api
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@plans-postgres:5432/plans"
            - name: IDENTITY_JWKS_URL
              value: http://traefik-internal.traefik.svc.cluster.local/.well-known/jwks.json
            - name: OTEL_SERVICE_NAME
              value: plans-api
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://signoz-ingester.signoz.svc.cluster.local:4318
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
