apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  template:
    spec:
      containers:
        - name: nats
          volumeMounts:
            - name: resolver-volume
              mountPath: /etc/resolver.conf
              subPath: resolver.conf
            - name: nats-storage
              mountPath: /data
      volumes:
        - name: resolver-volume
          secret:
            secretName: nats-resolver

  volumeClaimTemplates:
    - metadata:
        name: nats-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
