apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-postgres

manifests:
  kustomize:
    paths:
      - infra/postgres/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-migrate

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-migrate
      context: components/migrate
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - components/migrate/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-api

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-api
      context: components/api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/api/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-accounts-projector

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-accounts-projector
      context: components/accounts-projector
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/accounts-projector/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-entitlements-projector

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-entitlements-projector
      context: components/entitlements-projector
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/entitlements-projector/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-ui

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-ui
      context: components/ui
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: app/**/*
            dest: /home/node/app
          - src: server.ts
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/ui/infra/overlays/ephemeral

deploy:
  kubectl: {}
