apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-postgres-dev

manifests:
  kustomize:
    paths:
      - infra/postgres/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-ui-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-ui
      context: packages/ui
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: app/**/*
            dest: /home/node/app
          - src: server.ts
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - infra/ui/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-migrate-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-migrate
      context: packages/database
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - infra/migrate/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-api-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-api
      context: packages/api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - infra/api/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: documents-worker-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/documents-worker
      context: packages/worker
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - infra/worker/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}
