version: "3.1"

services:

  traefik:
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.labels.traefik-certificates == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.tls.certresolver=le
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `public`)
      - --providers.docker.exposedbydefault=false
      #
      - --providers.docker.swarmMode=true
      #
      - --entrypoints.web.address=:80
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.address=:443
      #
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      #
      - --accesslog
      - --log
      - --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/certificates
    networks:
      - public

  api:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.docker.network=public
      #
      # - traefik.http.routers.api.tls=true
      # - traefik.http.routers.api.tls.certresolver=le
      #
      # - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/api`)
      - traefik.http.routers.api.middlewares=api-stripprefix
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
      - traefik.http.services.api-service.loadbalancer.server.port=3000
    environment:
      - API_ENV_FILE=/run/secrets/api_env
    secrets:
      - api_env
    networks:
      - public

  postgres:
    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    secrets:
      - psql_user
      - psql_password
    networks:
      - public

networks:
  public:
    external: true

volumes:
  traefik-certificates:

secrets:
  api_env:
    external: true
  #
  psql_user:
    external: true
  psql_password:
    external: true
