#
# $ docker stack deploy --compose-file docker-stack.yml STACK
#

version: "3.1"

services:

  traefik:
    image: traefik:2.4.1
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.labels.traefik-certificates == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode
      - --entryPoints.web.address=:80
      - --accesslog
      - --log
      - --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/certificates
    networks:
      - public

  api:
    image: mdstaicu/api
    deploy:
      labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.rule=Host(`api.iarmaroc.space`)
      - traefik.http.services.api.loadbalancer.server.port=3000
    environment:
      - API_ENV_FILE=/run/secrets/api_env
    secrets:
      - api_env
    networks:
      - public

  postgres:
    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    secrets:
      - psql_user
      - psql_password
    networks:
      - public

networks:
  public:
    external: true

volumes:
  traefik-certificates:

secrets:
  api_env:
    external: true
  psql_user:
    external: true
  psql_password:
    external: true