version: "3.1"

services:

  traefik:
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.routers.traefik.rule=Host(`localhost`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --api.insecure
      - --entrypoints.web.address=:80
      - --log
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/certificates
    networks:
      - public

  api:
    build:
      context: ./api
      target: dev
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - API_ENV_FILE=/run/secrets/api_env
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.api.middlewares=api-stripprefix
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
    secrets:
      - api_env
    volumes:
      - ./api:/home/node/api/dev
      # This is needed because the host node modules are built
      # for the host operating system architecture
      # and our development environment's architecture is based on Debian
      #
      # Hide the host node_modules by creating an anonymous volume
      # at the location of the bind mounted node modules
      #
      # This will allow us to either run the development environment
      # with or without Docker
      - /home/node/api/dev/node_modules
    networks:
      - public

  postgres:
    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
    secrets:
      - psql_user
      - psql_password
    networks:
      - public

networks:
  public:

volumes:
  traefik-certificates:

secrets:
  api_env:
    file: ./secrets/api/.env
  #
  psql_user:
    file: ./secrets/postgres/psql_user
  psql_password:
    file: ./secrets/postgres/psql_password
