apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - ../../base

patches:
  - path: outbox-publisher-depl.yaml

images:
  - name: ghcr.io/mstaicu/accounts-outbox-publisher
    newTag: latest # {"$imagepolicy": "flux-system:accounts-outbox-publisher:tag"}
    digest: "" # {"$imagepolicy": "flux-system:accounts-outbox-publisher:digest"}
