apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - entitlements-postgres-deployment.yaml
  - entitlements-postgres-service.yaml
  - entitlements-postgres-networkpolicy.yaml
