apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - namespace.yaml
  - ../../base
  - accounts-api-db.yaml

patches:
  - path: accounts-api-depl.yaml
  - path: accounts-api-ingress.yaml

images:
  - name: mdstaicu/accounts-api
    newTag: latest
