apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - ../../base

secretGenerator:
  - name: accounts-api-db
    literals:
      - DATABASE_URL=postgres://postgres@postgres-srv:5432/accounts?sslmode=disable
    options:
      disableNameSuffixHash: true

images:
  - name: mdstaicu/accounts-api
    # This field is managed by this ImagePolicy: <namespace>:<imagepolicy-name>
    # meaning: flux-system:accounts-api-latest
    newTag: latest # {"$imagepolicy": "flux-system:accounts-api-latest"}
