apiVersion: batch/v1
kind: Job

metadata:
  name: migrations
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  template:
    spec:
      containers:
        - name: migrations
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://postgres:5432/accounts?user=postgres&password=postgres"
