apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: monitor
      protocol: TCP
      appProtocol: HTTP
      port: 8222
      targetPort: 8222
