server_name: $HOSTNAME

port: 4222
http_port: 8222

jetstream {
  store_dir: "/data"
}

# Without this, Kubernetes may kill a pod while it’s still leader,
# causing rougher elections and client disconnect pain
lame_duck_duration: 30s
lame_duck_grace_period: 10s

pid_file: "/var/run/nats/nats.pid"

cluster {
  name: "EU"
  port: 6222

  no_advertise: true

  routes = [
    "nats://nats-depl-0.nats-headless.nats.svc.cluster.local:6222",
    "nats://nats-depl-1.nats-headless.nats.svc.cluster.local:6222",
    "nats://nats-depl-2.nats-headless.nats.svc.cluster.local:6222"
  ]
}

# SYS remains authenticated for system operations.
system_account: SYS
# Unauthenticated clients are mapped into the APP account.
no_auth_user: app

accounts: {
  SYS: {
    users: [
      { user: "sys", password: "changeit" }
    ]
  }

  APP: {
    users: [
      { user: "app" }
    ]
  }
}
