apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-depl
spec:
  replicas: 1
  template:
    spec:
      affinity: null
      #
      # This is provided by referencing the secret manager in the overlay kustomization
      # in the components directive
      #
      serviceAccountName: secrets-viewer-sa
      initContainers:
        - name: wait-for-auth-secrets
          image: bitnami/kubectl:latest
          env:
            #
            # Kustomize will insert the namespace
            #
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUTH_SECRETS
              value: auth-secrets
          command:
            - sh
            - -c
            - |
              while ! kubectl get secret "$AUTH_SECRETS" -n "$NAMESPACE" > /dev/null 2>&1; do
                sleep 1
              done
