apiVersion: batch/v1
kind: Job

metadata:
  name: secrets-manager
spec:
  template:
    metadata:
      name: generate-auth-secrets
    spec:
      containers:
        - name: create-k8s-secret
          env:
            - name: SECRET_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-scripts-config
                  key: SECRET_NAME
      volumes:
        - name: scripts-volume
          configMap:
            name: auth-secrets-scripts
