apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-depl
spec:
  replicas: 1
  template:
    spec:
      affinity: null
      serviceAccountName: secrets-manager-sa
      initContainers:
        - name: auth-ic-generate-secrets
          image: node:latest
          volumeMounts:
            - name: auth-volume-scripts
              mountPath: /secrets
            - name: auth-cm-scripts
              mountPath: /scripts
          command:
            - node
            - /scripts/generate-secrets.mjs

        - name: auth-ic-create-secret
          image: bitnami/kubectl:latest
          volumeMounts:
            - name: auth-volume-scripts
              mountPath: /secrets
            - name: auth-cm-scripts
              mountPath: /scripts
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - /scripts/create-secrets.sh

      volumes:
        - name: auth-volume-scripts
          emptyDir: {}
        - name: auth-cm-scripts
          configMap:
            name: auth-cm-scripts
