apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-depl
spec:
  replicas: 1
  template:
    spec:
      affinity: null
      serviceAccountName: secrets-manager-sa
      initContainers:
        - name: generate-auth-secrets
          image: node:alpine
          volumeMounts:
            - name: auth-volume-scripts
              mountPath: /secrets
            - name: auth-cm-scripts
              mountPath: /scripts
          command:
            - node
            - /scripts/generate-secrets.mjs

        - name: create-auth-secret
          image: bitnami/kubectl:latest
          volumeMounts:
            - name: auth-volume-scripts
              mountPath: /secrets
            - name: auth-cm-scripts
              mountPath: /scripts
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - /scripts/create-secrets.sh

        - name: wait-for-nats-secret
          image: bitnami/kubectl:latest
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          command:
            - /bin/sh
            - "-c"
            - |
              until kubectl get secret nats-auth-creds-secret -n $NAMESPACE 2>&1 >/dev/null; do
                sleep 2
              done

      volumes:
        - name: auth-volume-scripts
          emptyDir: {}
        - name: auth-cm-scripts
          configMap:
            name: auth-cm-scripts
