apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-depl
spec:
  replicas: 1
  template:
    spec:
      affinity: null
      initContainers:
        - name: wait-for-auth-secrets
          image: bitnami/kubectl:latest
          env:
            - name: NAMESPACE
              value: dev
            - name: AUTH_SECRETS
              value: auth-secrets
          command:
            - sh
            - -c
            - |
              while ! kubectl get secret $AUTH_SECRETS -n $NAMESPACE > /dev/null 2>&1; do
                sleep 1
              done
