apiVersion: batch/v1
kind: Job

metadata:
  name: auth-secrets-manager
spec:
  ttlSecondsAfterFinished: 0 # Automatically delete after 0 seconds
  template:
    spec:
      serviceAccountName: secrets-manager-sa
      initContainers:
        - name: generate-secrets
          image: node:latest
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
            - name: scripts-volume
              mountPath: /scripts
          command:
            - sh
            - -c
            - |
              node /scripts/generate-secrets.mjs
      containers:
        - name: create-k8s-secret
          image: bitnami/kubectl:latest
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
            - name: scripts-volume
              mountPath: /scripts
          env:
            - name: SECRET_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-scripts-config
                  key: SECRET_NAME
            #
            # Kustomize will insert the namespace
            #
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          command:
            - sh
            - -c
            - |
              sh /scripts/create-k8s-secret.sh

      volumes:
        - name: secrets-volume
          emptyDir: {}
        - name: scripts-volume
          configMap:
            name: auth-secrets-scripts

      restartPolicy: OnFailure
