apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-depl
spec:
  replicas: 1
  template:
    spec:
      affinity: null
      serviceAccountName: secrets-manager-sa
      initContainers:
        - name: generate-secrets
          image: node:latest
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
            - name: auth-scripts
              mountPath: /scripts
          command:
            - node
            - /scripts/generate-secrets.mjs

        - name: create-secret
          image: bitnami/kubectl:latest
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
            - name: auth-scripts
              mountPath: /scripts
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - sh
            - /scripts/create-secrets.sh

      volumes:
        - name: secrets-volume
          emptyDir: {}
        - name: auth-scripts
          configMap:
            name: auth-scripts
