apiVersion: batch/v1
kind: Job

metadata:
  name: auth-secrets-job
spec:
  template:
    spec:
      serviceAccountName: secrets-manager-sa
      restartPolicy: Never
      initContainers:
        - name: generate-auth-secrets
          image: node:alpine
          command:
            - node
            - /scripts/generate-secrets.mjs
          volumeMounts:
            - name: auth-secrets-volume
              mountPath: /secrets
            - name: auth-scripts-cm
              mountPath: /scripts

      containers:
        - name: create-auth-secret
          image: bitnami/kubectl:latest
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/sh
            - /scripts/create-secrets.sh
          volumeMounts:
            - name: auth-secrets-volume
              mountPath: /secrets
            - name: auth-scripts-cm
              mountPath: /scripts

      volumes:
        - name: auth-secrets-volume
          emptyDir: {}
        - name: auth-scripts-cm
          configMap:
            name: auth-scripts-cm
