apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/auth
  - auth-mongo-depl.yaml

configMapGenerator:
  - name: auth-service-config
    literals:
      - MONGO_DB_URI=mongodb://auth-mongo-srv:27017
      - DOMAIN=tma.com
      - ORIGIN=https://tma.com

patches:
  - path: auth-depl.yaml
