apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/auth
  - auth-cert.yaml
  - auth-mongo-depl.yaml
  - auth-rbac.yaml

configMapGenerator:
  - name: auth-cm
    literals:
      - MONGO_DB_URI=mongodb://auth-mongo-srv:27017
      - DOMAIN=tma.com
      - ORIGIN=https://tma.com
  - name: auth-scripts-cm
    files:
      - auth-token-secrets.mjs=auth-token-secrets.mjs

patches:
  - path: auth-depl.yaml
