apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/auth
  - auth-rbac.yaml
  - auth-secrets-job.yaml
  - auth-mongo-depl.yaml

configMapGenerator:
  - name: auth-cm
    literals:
      - MONGO_DB_URI=mongodb://auth-mongo-srv:27017
      - DOMAIN=tma.com
      - ORIGIN=https://tma.com
  - name: auth-scripts-cm
    files:
      - create-secrets.sh=scripts/create-secrets.sh
      - generate-secrets.mjs=scripts/generate-secrets.mjs

patches:
  - path: auth-depl.yaml
