apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/auth
  - auth-mongo-depl.yaml

components:
  - ../../../components/secrets-manager

configMapGenerator:
  - name: auth-config
    literals:
      - MONGO_DB_URI=mongodb://auth-mongo-srv:27017
      - DOMAIN=tma.com
      - ORIGIN=https://tma.com
  - name: auth-scripts-config
    literals:
      - SECRET_NAME=auth-secrets
  - name: auth-secrets-scripts
    files:
      - generate-secrets.mjs=./scripts/generate-secrets.mjs
      - create-k8s-secret.sh=./scripts/create-k8s-secret.sh

patches:
  - path: auth-depl.yaml
  - path: auth-secrets-job.yaml
