apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: features

resources:
  - namespace.yaml
  - ../../base

generators:
  - features-api-ksops-generator.yaml

patches:
  - path: features-api-depl.yaml
