CREATE ROLE documents_migrator
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

CREATE ROLE documents_api
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

CREATE ROLE documents_worker
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

REVOKE CONNECT, TEMPORARY ON DATABASE documents FROM PUBLIC;

GRANT CONNECT, CREATE, TEMPORARY
ON DATABASE documents
TO documents_migrator;

GRANT CONNECT
ON DATABASE documents
TO documents_api,
   documents_worker;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;

GRANT USAGE, CREATE
ON SCHEMA public
TO documents_migrator;

GRANT USAGE
ON SCHEMA public
TO documents_api,
   documents_worker;
