apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: api-public-docs
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`api.tma.com`) && PathPrefix(`/v1/auth/docs`)
      services:
        - name: api
          port: 3000
  tls: {}
