apiVersion: v1
data:
  OPENOBSERVE_TOKEN: ENC[AES256_GCM,data:l7qMKiohydM53Zcjc1rfKQQmUQIbXg8giAbEWI6n2XxrTrLryaEdQn20ynPhD3hB,iv:I4UPIGjMDobF2OlX2ZXQVyPjsSYugOpB/oTF2wcEsOg=,tag:UzR30JE14fGQ2vUIABzCXQ==,type:str]
  ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:SxwGScPhH7Pch7YVnQm9F3PqN8JdcZZLU2C8gw==,iv:ZeHdNrHqdDAJItwS3uRC+lkqq1tJxJBXtA3MCFGl25E=,tag:XGMkOUf+uYYDdRZV9FZkbw==,type:str]
  ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:WzKg1fd0jJE=,iv:vLSQK7FrbxpFFQ1oyiK46irYyza9h5rQsRRes+aAIb8=,tag:9LtuNqddQ86pIo5thg5eSA==,type:str]
kind: Secret
metadata:
  name: openobserve
stringData:
  ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:rooI72XBY6iR4MlU4ls=,iv:9g/M4vX8ibdUKvw+AZa1Kgd5M7vnwF942NjSKkkRHEo=,tag:N2vi88fJru76GW8NOGI+3g==,type:str]
  OPENOBSERVE_TOKEN: ENC[AES256_GCM,data:yF0ixfDiXEuiQlSyuTzuczEn/ZFHrEqUMsAtBpb+2McaE6lz5oBmlJyk/DX+FaNs,iv:a8GY5eQ8W+5nA2BtRnjU34jEYOovfOI67ZjJEw0uRPQ=,tag:8VB4pmNr6T9hqEgmGMCaXg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb1J3ck1PVC9UbFhjZVBD
        aVhxZEp4cFRvWHJKUFRVQW40RDgweVNUakJnCjViVGRoSHBScWhVcWE5R2hER0V2
        NnlmVGdYRXBkWVl6TUlRNGxyMVV1a0EKLS0tIE1PbXBzSDRydjNtRGRkZVpGTDAw
        Tm5IcDkySXZVMTc1Rnh6eC9QazVqM2sKGUElGwDv0Tt/YdAnrC9muyw4fUf/Hjee
        J4VjdRnrqWenx+8NagQeLVCwDWagrpcMKGRsTPd7gt3QYPgQU/H41w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-08T12:55:02Z"
  mac: ENC[AES256_GCM,data:hYAfnvgorU/B9lRZO3TVkbRaUzQ9LHN/KEOghlL53W5VAkFBSg47Z1kRHdnWcA1bQU2W+DtedidbXYZrR6K5Vpi4UTg1ZR91TfcFlhnELbLZmfNw+8EUwPZ3zG9Jko8hE8O9xc4pkycM42QS0aPq0MrmauI2GHUhyyDEnsAyDW0=,iv:K7DJ3+aOhI1I/PKBAsfb8GxoT3KE+AIkFNIyQrN0/1A=,tag:dkeZiedcPIM1aNQQjYY8NQ==,type:str]
  version: 3.13.1
