apiVersion: v1
kind: Secret
metadata:
  name: identity-migrate-db
stringData:
  FLYWAY_URL: ENC[AES256_GCM,data:2JlfRpZAi2jZA7Wy77AL1F1gwzBfECoYKUZSlbDN5oOYPPP+SBEnYaEC3Pr+4A08bGzMPjvlK2Xb+ROl,iv:hp8RArWdvp9utVgb4wd7KXzEaxm3gR1WXcfHmPdX9m8=,tag:0fTc0EfIzZ379/NiFu98pA==,type:str]
  FLYWAY_USER: ENC[AES256_GCM,data:bBfiZ0w9n/ixU/pLwKnSC4I=,iv:5PlIjpLh7fuLzBwpqb4RlkbWRKzgJolFnPe8Iha5Zxg=,tag:8XISH2UXWzMqL6lToUdoAg==,type:str]
  FLYWAY_PASSWORD: ENC[AES256_GCM,data:WuiT,iv:bbzqEHBhfSACyYMM0VKRwc5NJgHk4xKpAyv5u7NCNVU=,tag:YzSJSoXnj7E2pM0lfenjrQ==,type:str]
  FLYWAY_LOCATIONS: ENC[AES256_GCM,data:CYITU0sFkS4Mu42CyojG9i/71nRNHrmmCtkbhYdpuITkynkfmwmDrcSnmBMZY3kgpLm3fnaCL017K/rl6BYJ+VDvZYBm0J1k,iv:FEY67mrod/vGoOWCi/TALgF/6gcYT23A+0Jwu1Trerg=,tag:NIGDcWv3FhYUQRV3wsdKmA==,type:str]
sops:
  age:
    - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWZwU0l0UVdsbnJueWpG
        MFFvWVZ5T3RBVXkrK0J0UFRIMU04dHN6ZjBnCmlvYkNTbGhDWEZsanJOTnlueklF
        aWx4akFrOStPVE5yOEFvMTk0SWlCMXMKLS0tIEhLTUU5Rk1RQWJiOHFRTk5rT1Yr
        cWE3UlRva08yaUl0SFZ1YnpzWlNZQlkKEqAun7bWDWONcWvB+lxLcN28b4Gmg+Eu
        Z4zLGrE/qux+T0ztLr6qJz5IbonjtTGiqWTKNXA+aCTnGTRH36QUZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T21:07:04Z"
  mac: ENC[AES256_GCM,data:IajA/LOQg1JmmvAueLRexXXMugCkkcrqEGDaQ5k/4mwsy9DcKdeuCp4UyiTdsYNbXwvE/pJ/L9pxK185Cea6gsUREmq6iC6GhI8G7p5YB/Qlya3gW2bF6C2uX0nLLlinY0sxKGkHexyEUV/aYRonDv0e/P+8kNVm0wog4ivVjWU=,iv:f9bGPfb9kIT2b01Oy/m2gRJCGKIghIeaW3MnASR2SXs=,tag:UsCFA9t0fSYXearGxy136A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
