apiVersion: viaduct.ai/v1
kind: KSOPS

metadata:
  name: identity-migrate-ksops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - identity-migrate-db.yaml
