apiVersion: v1
kind: Secret
metadata:
  name: identity-migrate-db
stringData:
  FLYWAY_URL: ENC[AES256_GCM,data:2JlfRpZAi2jZA7Wy77AL1F1gwzBfECoYKUZSlbDN5oOYPPP+SBEnYaEC3Pr+4A08bGzMPjvlK2Xb+ROl,iv:hp8RArWdvp9utVgb4wd7KXzEaxm3gR1WXcfHmPdX9m8=,tag:0fTc0EfIzZ379/NiFu98pA==,type:str]
  FLYWAY_USER: ENC[AES256_GCM,data:bBfiZ0w9n/ixU/pLwKnSC4I=,iv:5PlIjpLh7fuLzBwpqb4RlkbWRKzgJolFnPe8Iha5Zxg=,tag:8XISH2UXWzMqL6lToUdoAg==,type:str]
  FLYWAY_PASSWORD: ENC[AES256_GCM,data:WuiT,iv:bbzqEHBhfSACyYMM0VKRwc5NJgHk4xKpAyv5u7NCNVU=,tag:YzSJSoXnj7E2pM0lfenjrQ==,type:str]
sops:
  age:
    - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWZwU0l0UVdsbnJueWpG
        MFFvWVZ5T3RBVXkrK0J0UFRIMU04dHN6ZjBnCmlvYkNTbGhDWEZsanJOTnlueklF
        aWx4akFrOStPVE5yOEFvMTk0SWlCMXMKLS0tIEhLTUU5Rk1RQWJiOHFRTk5rT1Yr
        cWE3UlRva08yaUl0SFZ1YnpzWlNZQlkKEqAun7bWDWONcWvB+lxLcN28b4Gmg+Eu
        Z4zLGrE/qux+T0ztLr6qJz5IbonjtTGiqWTKNXA+aCTnGTRH36QUZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T11:33:32Z"
  mac: ENC[AES256_GCM,data:IWLcnNAlooUIxYoFxDcS5AB8wSLE4tOVxeVovRxj0bWdxmN0vVquw8HXjLPP26ILeNLJKOJ7tv3pYnPvMQcCtNdk1/gVuL8xvz3rY9QDO1VsVNZyPUFUIQSOVQpBuZvvqNF3hFRYdx5912EjpaAxsUEGlAHD7xp+7x1D7s9fWw4=,iv:YG3fAxorVE5KcOdhP/+EfmATb1RasgNCra0h4wna3d0=,tag:YjbNzzAUx297PaT0ToV1CA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
