apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base

secretGenerator:
  - name: identity-migrate-db
    literals:
      - DATABASE_URL=postgres://postgres@postgres-srv:5432/identity?sslmode=disable

generatorOptions:
  disableNameSuffixHash: true
