apiVersion: v1
kind: Service

metadata:
  name: traefik-public
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
