apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nats

resources:
  - ../../base
  - nats-networkpolicy.yaml
  - namespace.yaml

configMapGenerator:
  - name: nats-config
    files:
      - nats.conf=nats.conf

patches:
  - path: nats-statefulset.yaml
  - path: nats-client-service.yaml
