apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nats

resources:
  - ../../base
  - nats-np.yaml
  - nats-ns.yaml

configMapGenerator:
  - name: nats-config
    files:
      - nats.conf=nats.conf

patches:
  - path: nats-statefulset.yaml
  - path: nats-srv.yaml
