apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/nack
  # - nack-cr.yaml
  # - nack-job.yaml

#
# Mount the CRDs so that we can create the resources
# after the CRs are registered, mitigating eventual consistency issues
#
# configMapGenerator:
#   - name: nack-cm-crs
#     files:
#       - nack-crs.yaml=nack-crs.yaml

#
# Here's the magic
#
# We mount an empty file secret called 'nack-creds' to the nack controller
# after which we create the actual secret in the 'nack-job',
# and remount it in the pod by leveraging the k8s runtime
# to delete the secret and recreate it, k8s will remount it
# ( if the secret is not 'optional' or using a subPath )
#
secretGenerator:
  - name: nack-creds
    literals:
      - nack.creds=
    options:
      disableNameSuffixHash: true
