apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - identity-api-deployment.yaml
  - identity-api-internal-ingressroute.yaml
  - identity-api-internal-jwks-ingressroute.yaml
  - identity-api-service.yaml
  - identity-api-networkpolicy.yaml
