apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: auth-ui
  namespace: flux-system

spec:
  image: ghcr.io/mstaicu/auth-ui
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: auth-ui
  namespace: flux-system

spec:
  imageRepositoryRef:
    name: auth-ui
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: auth-ui
  namespace: flux-system

spec:
  interval: 10m
  path: ./domains/auth/workloads/ui/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: ghcr.io/mstaicu/auth-ui
      newTag: latest
      digest: sha256:6f23eff3e92d473179cea00f80fdc061efba768a2934c72c45bb351969b6fc3d # {"$imagepolicy": "flux-system:auth-ui:digest"}
  wait: true
  timeout: 5m
