apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: accounts-outbox-relay
  namespace: flux-system

spec:
  image: ghcr.io/mstaicu/outbox-relay
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: accounts-outbox-relay
  namespace: flux-system

spec:
  imageRepositoryRef:
    name: accounts-outbox-relay
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: accounts-outbox-relay
  namespace: flux-system

spec:
  interval: 10m
  path: ./domains/accounts/workloads/outbox-relay/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: accounts-migrations
    - name: event-bus
  images:
    - name: ghcr.io/mstaicu/outbox-relay
      newTag: latest
      digest: sha256:b3fe5b1c123244f4eeb91784c3bf1875515ae0a96e32ed169307190dae38c9f7 # {"$imagepolicy": "flux-system:accounts-outbox-relay:digest"}
  wait: true
  timeout: 5m
