apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - documents-api-internal-ingressroute.yaml
  - documents-api-networkpolicy.yaml
  - documents-api-deployment.yaml
  - documents-api-service.yaml
