apiVersion: apps/v1
kind: Deployment

metadata:
  name: entitlements-projector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entitlements-projector
  template:
    metadata:
      labels:
        app: entitlements-projector
    spec:
      terminationGracePeriodSeconds: 15
      automountServiceAccountToken: false

      containers:
        - name: entitlements-projector
          image: mdstaicu/documents-entitlements-projector
          ports:
            - name: health
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /livez
              port: health
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 2
