apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-reflector-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-reflector-controller
  template:
    metadata:
      labels:
        app: image-reflector-controller
    spec:
      serviceAccountName: image-reflector-controller
      containers:
        - name: manager
          image: ghcr.io/fluxcd/image-reflector-controller:v1.1.1
          args:
            - --watch-all-namespaces=true
            - --log-level=info
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
