apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: openobserve
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`observe.tma.com`)
      services:
        - name: openobserve
          port: 5080
  tls: {}
