apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: identity-api-public
spec:
  tls:
    certResolver: le
    domains:
      - main: api.tma.com

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: identity-jwks-public
spec:
  tls:
    certResolver: le
    domains:
      - main: api.tma.com
