apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - namespace.yaml
  - ../../base
  - identity-api-jwt.yaml
  - identity-api-db.yaml

patches:
  - path: identity-api-depl.yaml
  - path: identity-api-ingress.yaml

configMapGenerator:
  - name: identity-api-cm
    literals:
      - ORIGIN=https://tma.com
      - ACCESS_TOKEN_AUDIENCE=aperitif-api

images:
  - name: mdstaicu/identity-api
    newTag: latest
