apiVersion: apps/v1
kind: Deployment

metadata:
  name: accounts-postgres-depl
spec:
  template:
    spec:
      containers:
        - name: accounts-postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres

          volumeMounts:
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/001-accounts-init.sql
              subPath: accounts-postgres-init.sql
              readOnly: true

      volumes:
        - name: postgres-init
          configMap:
            name: accounts-postgres-init
