apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: traefik-acme-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 10Mi
