apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-tenancy-units-to-postgres
spec:
  podSelector:
    matchLabels:
      app: tenancy-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tenancy-api
        - podSelector:
            matchLabels:
              app: tenancy-migrate
        - podSelector:
            matchLabels:
              app: tenancy-worker
      ports:
        - protocol: TCP
          port: 5432
