apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: entitlements

resources:
  - ../../base

patches:
  - path: accounts-projector-depl.yaml

images:
  - name: ghcr.io/mstaicu/entitlements-accounts-projector
    newTag: latest # {"$imagepolicy": "flux-system:entitlements-accounts-projector:tag"}
    digest: "" # {"$imagepolicy": "flux-system:entitlements-accounts-projector:digest"}
