apiVersion: apps/v1
kind: Deployment
metadata:
  name: pebble-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pebble
  template:
    metadata:
      labels:
        app: pebble
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pebble
          image: letsencrypt/pebble
          env:
            # https://github.com/letsencrypt/pebble#testing-at-full-speed
            - name: PEBBLE_VA_NOSLEEP
              value: "1"
            # https://github.com/letsencrypt/pebble#skipping-validation
            - name: PEBBLE_VA_ALWAYS_VALID
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: pebble
spec:
  type: ClusterIP
  selector:
    app: pebble
  ports:
    - name: pebble-api
      protocol: TCP
      port: 14000
      targetPort: 14000
    - name: pebble-management
      protocol: TCP
      port: 15000
      targetPort: 15000
