apiVersion: v1
kind: Secret
metadata:
    name: accounts-api-db
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:nKHR4ocUVCYzYkhYKVLwwAG2HErPOKSzgfawg9v/sbXOrmKxIYMt0d/rWj9fd8Acq9BUunisXiDjKPIvlabPhStputAVtA==,iv:etPPHPHqFInCa0PqrNq3s+7Cht8JD5wH81vQpIaST+0=,tag:Jt1DNY7WFzjhtP5TJ8K/hw==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNVB1d3lWSC9vTGMxbDJk
            MkpRdG9FclJqUUVhZk9uZ3NvKzVOcFlNUGxzClBrR0pPZi9SdEdKalEyTThqZXhY
            Qzhxc1A1cWlvdkp5eTI4ZnRDaDQycUkKLS0tIDhHMUUyVDBSZG5WZ0p1azRTNGtY
            dFJ3MzZFSTZKaEI2Z3BjaUFUZGlzL2MKaiMer0YhPiUt7U1N1XDv+ZuRK2Op+yte
            UtFA8HKzq6gVA1vTY+FtJcb0TbkU9iqc9fLzHjyBN5hvOy0rzk47vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T08:35:59Z"
    mac: ENC[AES256_GCM,data:GwzJCML9OBcgWVtZjSif+9hLe0kVrFrRPkf9YKTjuxShlXpQM4Ek8kZEDJmCN+ftCj11arSsjmjPEQMzCLjFi9/oSgvpmMxmZq+Wz/carY1ySqG1BQv5JXCGawtAbijtVWRrRH/QSbcdsHMskpOoTj62huOysdmCvgf8LDdFSVo=,iv:aBmUQWzj3rfPPSPCUSiSkkW7uIvtS+2nYWbAWK+6Y44=,tag:lK8lZRcBzvfAYNaFhK2OhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
