apiVersion: v1
kind: Secret
metadata:
  name: accounts-api-db
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:XRJX2JdI/KMOt/CSu4Jfe0iPMVurrlvMTIwfnEwo37/vGYjb/kRUp8Dz4LEYTk2wEKZmdgATTGpPGUFCEUUItFHH97YC2w==,iv:TJjO6sGY7hZG5ytKdDEL/nokA5quyTvAISujANJpXN4=,tag:8sT9n+f4tKCGOBirohb0HA==,type:str]
sops:
  age:
    - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSjZUd2ZDb1N5cVFaTU44
        d21QNlhRQzZDd3pORjFpYTRxeEpSbFJmc1FrCkpnWGhQNlFsWkkrejlGVGpGWjZJ
        RDVYQS9CWnIyejJNeEI2R29aMjhCZWcKLS0tIEk3Z0hKZkF1alFUS0YyUmdiclp1
        NVg2Y0NiVFNhTTBrNnh1WUhjLzlFdlkKbyzw3vGmxjpVmMQldiYWNlylSw6Gdf3B
        L5gIKAPlrVYa2w9kEMHdl0Fhaqx/5ixh6VQY6Z6+4I214zW0h3XarQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T21:07:04Z"
  mac: ENC[AES256_GCM,data:+nbOcFoRauGIJ39eSbHMh6VdyV95NxOUAA47+K8+Uq0gEOe3qavgr8rVtWYcShFtlLRqAgK/20V2bFlpUzmSm1RLw/+xp5qa2m6ieGfX58BSb0VWXEoYuYZcGI4Tn4ic6OBjwsZRAPEq6dsUUsKoAP33/WM1ezKJvhLQUV+/8sg=,iv:mWiM88Fudorjf7WqrtIa9/xZZobjc8rvjA+pBMThGUk=,tag:UZC3734/gpy/lts+SsibXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
