brew "kubernetes-cli"
brew "kustomize"
brew "skaffold"

brew "mkcert"
brew "libpq"

brew "age"
brew "sops"
brew "ksops"

# tap "fluxcd/tap"
# brew "fluxcd/tap/flux"

# brew "helm"

# tap "nats-io/nats-tools"
# brew "nats-io/nats-tools/nats"
# brew "nats-io/nats-tools/nsc"

# brew "linkerd"

# brew "kubectl-slice"
