apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

profiles:
  - name: dev
    activation:
      - command: dev

    manifests:
      kustomize:
        paths:
          - infra/overlays/dev

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command: ["node", ".skaffold/hooks/setup-local-dev.mjs"]

  - name: debug
    activation:
      - command: debug

    manifests:
      kustomize:
        paths:
          - infra/overlays/dev

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command: ["node", ".skaffold/hooks/setup-local-dev.mjs"]

    # portForward:
    #   - resourceType: service
    #     resourceName: nats
    #     port: 4222
    #     address: 127.0.0.1

  - name: prod
    build:
      local:
        push: true

    manifests:
      kustomize:
        paths:
          - infra/overlays/prod
