apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-setup/*
      - ./infra/k8s-dev/*
      - ./infra/k8s/*
build:
  local:
    # Whenver we build an image, do not push to docker hub
    push: false
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: mdstaicu/client-remix
      context: client-remix
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "app/**/*.ts"
            dest: .
          - src: "app/**/*.tsx"
            dest: .
          - src: "app/**/*.css"
            dest: .
    # - image: mdstaicu/tickets
    #   context: tickets
    #   docker:
    #     dockerfile: Dockerfile
    #     target: dev
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    # - image: mdstaicu/orders
    #   context: orders
    #   docker:
    #     dockerfile: Dockerfile
    #     target: dev
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    # - image: mdstaicu/expiration
    #   context: expiration
    #   docker:
    #     dockerfile: Dockerfile
    #     target: dev
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    # - image: mdstaicu/payments
    #   context: payments
    #   docker:
    #     dockerfile: Dockerfile
    #     target: dev
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
