apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: k8s

build:
  local:
    push: true
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: prod

profiles:
  - name: dev
    build:
      local:
        push: false
      artifacts:
        - image: mdstaicu/auth
          context: auth
          docker:
            dockerfile: Dockerfile
            target: dev
          sync:
            manual:
              - src: src/**/*.mjs
                dest: .
    manifests:
      kustomize:
        paths:
          - infra/identity/overlays/dev

  - name: identity-prod
    manifests:
      kustomize:
        paths:
          - infra/identity/overlays/prod

    # deploy:
    #   kubectl:
    #     hooks:
    #       after:
    #         - host:
    #             command: ["./scripts/localhost.sh"]
