apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

profiles:
  - name: platform
    activation:
      - command: dev

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command: ["sh", "-c", "DOMAIN=tma.com node .skaffold/hooks/pre-deploy.mjs"]
          after:
            - host:
                command: ["sh", "-c", "DOMAIN=tma.com node .skaffold/hooks/post-deploy.mjs"]

    manifests:
      kustomize:
        paths:
          - infra/envs/dev/crds
          - infra/envs/dev/namespace

  - name: stack
    activation:
      - command: dev

    manifests:
      kustomize:
        paths:
          - infra/envs/dev/platform
