apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/auth-api
      context: auth-api
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

manifests:
  kustomize:
    paths:
      - infra/auth/overlays/dev

# portForward:
#   - resourceType: statefulset
#     resourceName: nats-depl
#     namespace: nats
#     port: 4222
