apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

profiles:
  - name: dev
    build:
      artifacts:
        - image: mdstaicu/auth
          context: auth
          docker:
            dockerfile: Dockerfile
            target: dev
          sync:
            manual:
              - src: src/**/*.mjs
                dest: .
      local:
        push: false

    manifests:
      kustomize:
        paths:
          - infra/overlays/dev

  - name: staging
    manifests:
      kustomize:
        paths:
          - infra/overlays/staging

  - name: prod
    build:
      artifacts:
        - image: mdstaicu/auth
          context: auth
          docker:
            dockerfile: Dockerfile
            target: prod
      local:
        push: true

    manifests:
      kustomize:
        paths:
          - infra/overlays/prod
