apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

profiles:
  - name: setup
    deploy:
      kubectl:
        hooks:
          after:
            - host:
                command: ["sh", "-c", "node .skaffold/post-deploy.mjs"]

    manifests:
      rawYaml:
        - infra2/linkerd/base/linkerd-ns.yaml
        - infra2/linkerd/base/linkerd-crd.yaml
        - infra2/linkerd/base/gateway-api-crd.yaml
        - infra2/traefik/base/traefik-ns.yaml
        - infra2/traefik/base/traefik-crd.yaml

      # kustomize:
      #   paths:
      #     - infra/envs/dev/crds
      #     - infra/envs/dev/namespace

  - name: start
    activation:
      - command: dev

    manifests:
      kustomize:
        paths:
          - infra2/linkerd/overlays/dev
          - infra2/traefik/overlays/dev
          - infra2/auth/overlays/dev
