apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/identity
      context: identity
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

profiles:
  - name: depl
    manifests:
      kustomize:
        paths:
          - infra/apps/overlays/dev

    deploy:
      kubectl:
        hooks:
          after:
            - host:
                command: ["./scripts/localhost.sh"]
