apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

profiles:
  - name: dev
    activation:
      - command: dev

    manifests:
      kustomize:
        paths:
          # - infra/base/cert-manager
          - infra/overlays/dev

    # deploy:
    #   kubectl:
    #     hooks:
    #       before:
    #         - host:
    #             command: ["sh", "-c", "node .skaffold/hooks/local-setup.mjs"]

  - name: debug
    activation:
      - command: debug

    manifests:
      kustomize:
        paths:
          # - infra/base/cert-manager
          - infra/overlays/dev

    portForward:
      - resourceType: statefulset
        resourceName: nats-depl
        port: 4222

  - name: prod
    build:
      local:
        push: false
      artifacts:
        - image: mdstaicu/auth
          docker:
            dockerfile: Dockerfile
            target: prod

    manifests:
      kustomize:
        paths:
          - infra/overlays/prod
