apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

profiles:
  - name: dev
    activation:
      - command: dev

    build:
      local:
        push: false

    manifests:
      kustomize:
        paths:
          - infra/overlays/dev

  - name: debug
    activation:
      - command: debug

    build:
      local:
        push: false

    manifests:
      kustomize:
        paths:
          - infra/overlays/dev

    portForward:
      - resourceType: service
        resourceName: nats
        port: 4222
        address: 127.0.0.1

  - name: prod
    build:
      local:
        push: true

    manifests:
      kustomize:
        paths:
          - infra/overlays/prod
