apiVersion: skaffold/v4beta11
kind: Config
profiles:
  - name: dev
    build:
      artifacts:
        - image: mdstaicu/authentication
          context: authentication
          sync:
            manual:
              - src: src/**/*.ts
                dest: .
          docker:
            dockerfile: Dockerfile
            target: dev
      local:
        push: false
    deploy:
      kubectl: {}
    manifests:
      rawYaml:
        - ./infra/**/*
