apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/**/*
build:
  local:
    #
    # Whenver we build an image, do not push to docker hub
    #
    push: false
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
