apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k-s
build:
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .
  local:
    push: false
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - infra/redis/redis-depl.yaml
    - infra/auth/auth-mongo-depl.yaml
    - infra/auth/auth-depl.yaml
