apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s
build:
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .
  local:
    push: false

manifests:
  kustomize:
    paths:
      - infra-2/overlays/dev

profiles:
  - name: staging
    manifests:
      kustomize:
        paths:
          - infra-2/overlays/staging

  - name: prod
    manifests:
      kustomize:
        paths:
          - infra-2/overlays/prod
