apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
      artifacts:
        - image: mdstaicu/auth
          context: auth
          docker:
            target: dev
          sync:
            manual:
              - src: src/**/*.mjs
                dest: .
    manifests:
      kustomize:
        paths:
          - infra/base/cert-manager
          - infra/overlays/dev

    # deploy:
    #   kubectl:
    #     hooks:
    #       before:
    #         - host:
    #             command: ["sh", "-c", "node .skaffold/hooks/local-setup.mjs"]

  - name: debug
    activation:
      - command: debug
    build:
      local:
        push: false
      artifacts:
        - image: mdstaicu/auth
          context: auth
          docker:
            target: dev
          sync:
            manual:
              - src: src/**/*.mjs
                dest: .
    manifests:
      kustomize:
        paths:
          - infra/base/cert-manager
          - infra/overlays/dev

    # deploy:
    #   kubectl:
    #     hooks:
    #       before:
    #         - host:
    #             command: ["sh", "-c", "node .skaffold/hooks/local-setup.mjs"]

    portForward:
      - resourceType: statefulset
        resourceName: nats-depl
        port: 4222

  - name: prod
    build:
      local:
        push: true
      artifacts:
        - image: mdstaicu/auth
          docker:
            target: prod
    manifests:
      kustomize:
        paths:
          - infra/base/cert-manager
          - infra/overlays/prod
