apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: root

requires:
  - path: platform/event-bus
  - path: platform/ingress
  - path: platform/observability

  - path: domains/identity
  - path: domains/tenancy
  - path: domains/capabilities
  - path: domains/documents
