apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: mdstaicu/auth
          context: auth
          docker:
            dockerfile: Dockerfile
            target: dev
          sync:
            manual:
              - src: src/**/*.mjs
                dest: .
      local:
        push: false

    manifests:
      kustomize:
        paths:
          - infra/overlays/dev

    # deploy:
    #   kubectl:
    #     hooks:
    #       before:
    #         - host:
    #             command:
    #               ["kubectl", "apply", "-f", "infra/base/nats/nats-crd.yaml"]

  - name: debug
    activation:
      - command: debug
    build:
      artifacts:
        - image: mdstaicu/auth
          context: auth
          docker:
            dockerfile: Dockerfile
            target: dev
          sync:
            manual:
              - src: src/**/*.mjs
                dest: .
      local:
        push: false

    manifests:
      kustomize:
        paths:
          - infra/overlays/dev

    # deploy:
    #   kubectl:
    #     hooks:
    #       before:
    #         - host:
    #             command:
    #               ["kubectl", "apply", "-f", "infra/base/nats/nats-crd.yaml"]

    portForward:
      - resourceType: statefulset
        resourceName: nats-depl
        port: 4222
        address: 127.0.0.1

  - name: prod
    build:
      artifacts:
        - image: mdstaicu/auth
          context: auth
          docker:
            dockerfile: Dockerfile
            target: prod
      local:
        push: true

    manifests:
      kustomize:
        paths:
          - infra/overlays/prod
