apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

profiles:
  - name: dev
    activation:
      - command: dev

    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command: ["sh", "-c", "node .skaffold/hooks/local-setup.mjs"]

    manifests:
      kustomize:
        paths:
          - infra2/envs/dev/crds
          - infra2/envs/dev/namespace
          - infra2/envs/dev/jobs
          - infra2/envs/dev/platforms/linkerd
          - infra2/envs/dev/platforms/traefik
