apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - docker:
        dockerfile: Dockerfile
        target: dev
      image: mdstaicu/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.js
            dest: .
  local:
    push: false
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./infra3/auth/*
    - ./infra3/traefik/*
