apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*.mjs
            dest: .

profiles:
  - name: crd
    manifests:
      rawYaml:
        - infra/linkerd/base/linkerd-crd.yaml
        - infra/linkerd/base/gateway-api-crd.yaml
        - infra/traefik/base/traefik-crd.yaml

  - name: ns
    deploy:
      kubectl:
        hooks:
          after:
            - host:
                command: ["sh", "-c", "node .skaffold/post-deploy.mjs"]

    manifests:
      rawYaml:
        - infra/linkerd/base/linkerd-ns.yaml
        - infra/traefik/base/traefik-ns.yaml
        - infra/apps/overlays/dev/namespace.yaml

  - name: depl
    manifests:
      kustomize:
        paths:
          - infra/linkerd/overlays/dev
          - infra/traefik/overlays/dev
          - infra/apps/overlays/dev
