apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: k8s

build:
  local:
    push: false
  artifacts:
    - image: mdstaicu/auth-api
      context: auth-api
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*
            dest: .
    - image: mdstaicu/auth-worker
      context: auth-worker
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: src/**/*
            dest: .

manifests:
  kustomize:
    paths:
      - infra/domains/auth/overlays/dev

    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec
# portForward:
#   - resourceType: statefulset
#     resourceName: nats-depl
#     namespace: nats
#     port: 4222
