version: "3"

env:
  NAMESPACE: dev
  DOMAIN: tma.com
  ORIGIN: https://tma.com

tasks:
  check-tools:
    desc: "Check if required tools are installed"
    cmds:
      - node ./.tasks/check-tools.mjs

  check-kubernetes:
    desc: "Check if Kubernetes is configured and kubectl is working"
    deps: [check-tools]
    cmds:
      - node ./.tasks/check-k8s-ready.mjs

  check-namespace:
    desc: "Check if namespace exists"
    deps: [check-kubernetes]
    cmds:
      - node ./.tasks/check-namespace.mjs

  generate-cert-secret:
    desc: "Generate a certificate secret for the domain"
    deps: [check-namespace]
    cmds:
      - node ./.tasks/generate-cert-secret.mjs

  generate-nats-users:
    desc: "Generates secrets for the NATS accounts and users"
    deps: [generate-cert-secret]
    cmds:
      - node ./.tasks/add-nats-auth.mjs

  add-host:
    desc: "Add /etc/hosts entry"
    deps: [generate-nats-users]
    cmds:
      - node ./.tasks/add-host.mjs

  create-k8s-resources:
    desc: "Create environment resources"
    deps: [add-host]
    cmds:
      - node ./.tasks/create-k8s-resources.mjs

  dev:
    desc: "Start development environment"
    deps: [create-k8s-resources]
    cmds:
      - node ./.tasks/dev.mjs

  debug:
    desc: "Start debug environment"
    deps: [create-k8s-resources]
    cmds:
      - node ./.tasks/debug.mjs

  default:
    desc: "This is the default task"
    cmds:
      - task: dev
