version: "3"

env:
  NAMESPACE: dev
  DOMAIN: tma.com
  ORIGIN: https://tma.com

tasks:
  check-tools:
    desc: "check if required tools are installed"
    cmds:
      - node ./.tasks/check-tools.mjs

  check-kubernetes:
    desc: "check if cluster is online"
    deps: [check-tools]
    cmds:
      - node ./.tasks/check-k8s.mjs

  check-namespace:
    desc: "check if namespace exists"
    deps: [check-kubernetes]
    cmds:
      - node ./.tasks/check-namespace.mjs

  add-service-resources:
    desc: "add resources and secrets"
    deps: [check-namespace]
    cmds:
      - node ./.tasks/add-service-resources.mjs

  add-nats-auth:
    desc: "add nats operator, accounts and user auth"
    deps: [add-service-resources]
    cmds:
      - node ./.tasks/add-nats-auth.mjs

  add-host:
    desc: "add /etc/hosts entry"
    deps: [add-nats-auth]
    cmds:
      - node ./.tasks/add-host.mjs

  dev:
    desc: "start development environment"
    deps: [add-host]
    cmds:
      - node ./.tasks/dev.mjs

  debug:
    desc: "start debug environment"
    deps: [add-host]
    cmds:
      - node ./.tasks/debug.mjs

  default:
    desc: "this is the default task"
    cmds:
      - task: dev
