apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`tma.com`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefik-tls
    options:
      name: tls-options
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption

metadata:
  name: tls-options
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 # TLS 1.2
    - TLS_AES_256_GCM_SHA384 # TLS 1.3
    - TLS_CHACHA20_POLY1305_SHA256 # TLS 1.3
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: true
