apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: spaces-db-dev

manifests:
  kustomize:
    paths:
      - infra/db/overlays/dev

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: spaces-migrate-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/spaces-migrate
      context: migrations
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - infra/migrate/overlays/dev

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: spaces-api-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/spaces-api
      context: api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - infra/api/overlays/dev
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}
