apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nats

resources:
  - ../../base
  - nats-ns.yaml

configMapGenerator:
  - name: nats-conf-cm
    files:
      - nats-server.conf=nats-server.conf

secretGenerator:
  - name: nats-jwts
    files:
      - ./jwts/ABEVBBVRYGGFHURMSSELOEAD3MRGK3FV43KRPUWSRABX76KGDPXERHO2.jwt # SYS
      - ./jwts/ACGC3HECZ7NOTRWKGGLRR43XNRGQ2ANURI6LSQG37BNNJ3B5NRYCDTZH.jwt # TMA
  - name: nack-creds
    files:
      - ./creds/nack.creds

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: nats-depl.yaml
  - path: nack-depl.yaml
