apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nats

resources:
  - ../../base
  # - nack-creds.yaml
  # - nats-accounts.yaml
  - nats-ns.yaml

configMapGenerator:
  - name: nats-conf-cm
    files:
      - nats-server.conf=nats-server.conf

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: nats-depl.yaml
  - path: nack-depl.yaml

generators:
  - nats-ksops-generator.yaml
