apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  template:
    metadata:
      labels:
        app: nats
    spec:
      affinity: null
      containers:
        - name: nats
          volumeMounts:
            - name: nats-conf-cm
              mountPath: /etc/nats/
            - name: nats-storage
              mountPath: /data
            - mountPath: /jwt
              name: nats-jwts

      volumes:
        - name: nats-conf-cm
          configMap:
            name: nats-conf-cm
        - name: nats-jwts
          secret:
            secretName: nats-jwts

  volumeClaimTemplates:
    - metadata:
        name: nats-storage
      spec:
        storageClassName: hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
