apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"

    providers:
      kubernetesCRD: {}

    tls:
      certificates:
        - certFile: /certs/tls.crt
          keyFile: /certs/tls.key

    log:
      level: DEBUG

    api:
      dashboard: true
      insecure: false

    accessLog: {}
