apiVersion: apps/v1
kind: Deployment

metadata:
  name: accounts-projector
spec:
  template:
    spec:
      containers:
        - name: accounts-projector
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres-srv:5432/entitlements"
            - name: NATS_URL
              value: nats://nats-srv.nats.svc.cluster.local:4222
