apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - ../../base

secretGenerator:
  - name: accounts-migrate-db
    literals:
      - FLYWAY_URL=jdbc:postgresql://postgres-srv:5432/accounts?sslmode=disable
      - FLYWAY_USER=postgres
      - FLYWAY_LOCATIONS=filesystem:/db/migrations,filesystem:/db/repeatable,filesystem:/db/seeds

generatorOptions:
  disableNameSuffixHash: true
