apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - identities-ns.yaml
  - identities-ui-depl.yaml
  - identities-ui-ingress.yaml
  - identities-ui-np.yaml
  - identities-ui-sa.yaml
  - identities-ui-srv.yaml
