apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease

metadata:
  name: linkerd-crds
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: linkerd-crds
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: linkerd-stable
