apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - namespace.yaml
  - ../../base
  - networkpolicy.yaml
  - public-docs-ingressroute.yaml
  - public-ingressroute.yaml
  - public-jwks-ingressroute.yaml

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: api-config
    literals:
      - ORIGIN=https://tma.com

secretGenerator:
  - name: api-jwt
    files:
      - jwt-private.pem=jwt-private.local.pem
      - jwt-public.pem=jwt-public.local.pem

generatorOptions:
  disableNameSuffixHash: true
