apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation

metadata:
  name: auth
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@tma.com
        name: FluxCD Bot
    push:
      branch: master
  update:
    path: ./k8s/infra/domains/auth/overlays/staging-eu
    strategy: Setters
