apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver

metadata:
  name: github-webhook
spec:
  events:
    - ping
    - push
  resources:
    - kind: GitRepository
      name: aperitif-repo
  secretRef:
    name: github-webhook
  type: github
