apiVersion: traefik.io/v1alpha1
kind: Middleware

metadata:
  name: auth-api-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /api/v1/auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware

metadata:
  name: auth-api-jwt
spec:
  plugin:
    jwt:
      # Required: true
      Keys:
        - http://auth-api-srv.auth.svc.cluster.local:3000/.well-known/jwks.json # Cluster-internal JWKS
      Alg: ES256
      PayloadFields:
        - exp
        - sub
        - aud
        - iss
      Audiences:
        - tma.com
      Issuers:
        - https://tma.com
      ForceRefreshKeys: true
      JwtSources:
        - type: bearer
          key: Authorization
      JwtHeaders:
        X-User-Id: sub
---
apiVersion: traefik.io/v1alpha1
kind: Middleware

metadata:
  name: auth-api-registration
spec:
  chain:
    middlewares:
      - name: auth-api-jwt
      - name: auth-api-strip-prefix
