apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-auth-worker-egress-to-nats
spec:
  podSelector:
    matchLabels:
      app: auth-worker
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nats
      ports:
        - protocol: TCP
          port: 4222
