apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: auth-api-external

spec:
  entryPoints:
    - https

  routes:
    - match: Host(`api.tma.com`) &&
        PathPrefix(`/v1/passkeys`) &&
        Method(`POST`)
      kind: Rule
      middlewares:
        - name: auth-ratelimit
        - name: auth-inflight
        - name: auth-body-limit
      services:
        - name: auth-api-srv
          port: 3000
          serversTransport: auth-api-timeouts

  tls: {}

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: auth-api-internal

spec:
  entryPoints:
    - http

  routes:
    - match: PathPrefix(`/v1/passkeys`) &&
        Method(`POST`)
      kind: Rule
      middlewares:
        - name: auth-inflight
        - name: auth-body-limit
      services:
        - name: auth-api-srv
          port: 3000
          serversTransport: auth-api-timeouts
