apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - ../../base
  - auth-api-ingress.yaml
  - auth-api-middleware.yaml
  # - auth-api-nats-account.yaml
  - auth-api-nats-creds.yaml
  - auth-ns.yaml
  - auth-postgres-depl.yaml
  # - auth-stream.yaml
  # - auth-worker-consumer.yaml
  # - auth-worker-nats-secret.yaml

configMapGenerator:
  - name: auth-api-cm
    literals:
      - DATABASE_URL=postgres://postgres@postgres-srv:5432/auth
      - ORIGIN=https://tma.com
  # - name: auth-worker-cm
  #   literals:
  #     - DATABASE_URL=postgres://postgres@postgres-srv:5432/auth

patches:
  - path: auth-api-depl.yaml

generators:
  - auth-ksops-generator.yaml
