apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-api-depl
spec:
  replicas: 1
  template:
    spec:
      affinity: null
      containers:
        - name: auth-api
          image: mdstaicu/auth-api
