apiVersion: jetstream.nats.io/v1beta2
kind: Stream

metadata:
  name: subscriptions
spec:
  name: subscriptions
  subjects: ["subscriptions.*"]
  storage: memory
  replicas: 3
  creds: /nack/creds/nack.creds