apiVersion: v1
kind: Secret
metadata:
    name: features-migrate-db
stringData:
    FLYWAY_URL: ENC[AES256_GCM,data:slykme0KDPELlZh8mQ5hL7yDM3kHqyjeClCAc1R70YZr1lQjad9LfPWmJLbXQ0ARkbLKZshN0VJCP4MD,iv:K4jWLJqa/ggZf+DPVUyCAcLV1gi013AK78yB7pjYVX8=,tag:A8VG18x+dEsFtuMcUr32EA==,type:str]
    FLYWAY_USER: ENC[AES256_GCM,data:4hu7o9FZ939oSmxD7xkqoeg=,iv:hg1H6e9RJ/xZMqGvOxOOMmXmFkAKWn+PK1gVGR3HOuQ=,tag:o13CFjmcP1eh/9MpQTIWnA==,type:str]
    FLYWAY_PASSWORD: ENC[AES256_GCM,data:jO8F,iv:zNQDGCoet/pDGBfWVlOkEiNxdxvRe8N/mCf7vhDqZvs=,tag:QCDEU0w59hkOwXi3QLYAcQ==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWDlsVHZSTTl2YkJaYnps
            TkNFcFFhakFIZ2wrRFZRQkFTbXNCaTM4RDI4CjVvTzN5TTd3K0Z5TmNqV3VIRTU0
            ZEhPZWFQV0tUM0pDcGVLd2g0aDVGVjAKLS0tIDdWVUx4SlcyWEVCUkMvazF5Z0Yw
            WGxiSHF5c09od09MYXcyMEhMMFdXM1kKEAN5tAlTfgkFRxpS3ktauLDreMOTqJZn
            LZSImMHJ3dr2jiBzjlbFzU5PXcjeIqhUNpDpD0zPjfW8/0Egaewl1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T11:29:24Z"
    mac: ENC[AES256_GCM,data:XLDNfmxkCUGUyXFlN0goetRfJ+RNVCONiPGlWHceJBvmte8f7EVHkHevVwriMco+N6GzGQUxAn4vLW7sFTPHbLCKbH6SgU/hUe3QmPkvENRL2zLkvynH3XuXuesKdP4/Pf3i2NEsXIjw253hlQXNtyr8wG5nIaDwV9edd+8MmDk=,iv:og4k8U2LiqQGOp0CqETXvgkaJR1tPL14qmcAQ63fqoU=,tag:79w0SZn4X9Jma+h6e48zPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
