apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: cert-manager-crs
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
    namespace: flux-system
  path: ./k8s/infra/cert-manager-crs/overlays/dev
  prune: true
  wait: true
  interval: 10m
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Issuer
      name: linkerd-trust-root-issuer
      namespace: cert-manager
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: linkerd-trust-anchor
      namespace: cert-manager
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: linkerd-identity-issuer
  dependsOn:
    - name: cert-manager
