apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: sources
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
    namespace: flux-system
  path: ./k8s/infra/sources
  prune: true
  wait: true
  interval: 10m