apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: trust-manager
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
    namespace: flux-system
  path: ./k8s/infra/trust-manager/base
  prune: true
  wait: true
  interval: 10m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: trust-manager
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: trust-manager
      namespace: cert-manager
  dependsOn:
    - name: cert-manager-cr
