apiVersion: apps/v1
kind: Deployment

metadata:
  name: traefik-depl
spec:
  replicas: 1
  template:
    spec:
      affinity: null
      containers:
        - name: traefik
          args:
            - --log.level=DEBUG
