apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: accounts-api-public
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`api.tma.com`) && PathPrefix(`/v1/accounts`)
      services:
        - name: accounts-api
          port: 3000
  tls: {}
