apiVersion: v1
data:
    jwks.json: ENC[AES256_GCM,data:ntAgVZ22tbIpF/Pf8LatIm7usFbyMRl5E8kceDnxZdneVk075FY8rouNaDomJqtMKzhyicFAGSVOtl0PTATGHfiPFCgXnoEXioCanFtwokk+z2jtSiFU8Na6u3nygNQZz0XdLz1v27AGN0c7kTEIqz9SediotawWajLqpUK2Pkdebb4sEg1ja6oxt9W5oQ8MmRxA57GlkM8P8iaxyQ2VsBwW+E5BRkpWQlya7m9PCUYxiRj5trYBT8hebkmCQdb+N+jZlhn4TKIuAsr1VKJH4fmv4PXXcgK6f0oiqLYyb8HkorNAphkc9cjFezY3arJQDjhm5UIPOSj9tQdgyhifO30GlWd2NIh1DFi2pfaAyIvss44EFkgVEiA1+FgjCyw5LXrXsvtXH8NA8iIkYZCOJRjsibapL6ZV6d9atBnYhoqWJozfSOjY0i521cnam3ocrH3BJGWWFV16Lv6Z1pFQTtisraxdYW/U1avFrk2BwLPTNdDlbSuEh0svDRk/eFSyRlz3QyD7Yl18FUOn592wLE5jqqkGHsUfL7m9/K8imLZdBS7QHQn76+qSug9r6aW4SZU3809Rc2IySJodRUacNiQ4vJc6l7+uSB5Z++UaECCkFyO13BNEto7VllH2vb3OnOIMHOlUSE1ubWABYAUzdYtZjjc3R1HPAVhiGYE3Y/XHv4NR1BiDMH7ojQRFBijafGqoOHZ8GljjQyV9EendzMZy2ZaUNSzgVdYu4wElfJuJR7y1mi3l0calHNB1W3owPlbUC9o0yXOtUr/Un1CNAQJz9ubaOiUQhv0c8bKQtsJEu9uAzypijkIJvOxrePVQEyfUwDxuD9K2uDUASQXwlWwPvkbgHfyGl6WwDYATCxcIJtnQzVPUCtAY9rsvN/7PxFtDzMkHojd5gJTdgJpGQicu4P98w856g4tVcqwjZX3be5SlIzl8cE5D+Xy89+YmKqLjuQ3HKwMd0b9c,iv:wRpttQR0BpdQd/RJbAgWc00u1DcP8D3H+cxWDC/Ad2w=,tag:XPMU3WnoTMU5B4FpWE1ZNQ==,type:str]
kind: Secret
metadata:
    name: api-jwt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna3VGR1BFeUR0L1BhY0p5
            Y2d5U3l6cUxCcFI3SHc4OEtuQlJhZGxNVVJNCnBwbDJaa2drcWlKdmN1V2t0ZEhI
            WjNPcUNWR0Y1VTRkMEtHQktSZW1sekEKLS0tIDJmWDNsMm43T0NaaVJjNHNLNEhO
            WjA4WEZuZXlhQXl4Tm5FQ1ZITHdiZWMKvWjmRz3GzCC5P+ORgptheuUgbPenT1eO
            l1ZEpZ+Wv8ObrHii64IBLol42vPSB6DAtUTaGZCvFTrOy3r6cZZHPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T18:06:43Z"
    mac: ENC[AES256_GCM,data:vH5uoDI6ns3mr3vAXAGfIx/X5dzIvP9CBxnv7OJNGvZv0Km4waaeUy10GEezuLS1aqCYqBO2z0lN4nOh5PE9fe0sbElile46oP3KOWQvZnPliUTN0G1Bun2sfzjJGkFuTO5Du5lZMtGaZT+UdSoYESO/drFWUnHMPfq6eZFQHbg=,iv:jDpW0O5t/Hq6t2Geo2l5YRJJ0Ynclk7KQ8umBubdOJ0=,tag:J1vfpWPumaqaU/yp82vfug==,type:str]
    version: 3.13.3
