apiVersion: v1
data:
  jwt-private.pem: ENC[AES256_GCM,data:pcVRe7ZuOyxqYTVqEOO9Vppl4TE8eTlSvxGUjyoTbT/bMsLdipn7ooHn2CXitFnYuvcHnmBj52RsXf4TTx8Z4qZbH7HPiCSJky7Nr55vXoK79pOBuc5LqJXc2itdcc5ZjHuN34ZioYiaZ+H+Q8gBeMG4qFvZIxcSSlF1XPmzvrXFE1jftDy12e++H3G0QJZ5/IeQU5Wo0n85k4K/ZZBwWuP0h1sJz4EAoQuErJueuPrXBRG0zfEHsA2iRR1yvLxcRRYG8xfazs6/TKewRpgX43h8o0ImT/SH7iTqX2VpeuzOklLjRcKMIOnCwBZFltOR7a2kNnbErdSKXcZ2Td/1ao7AvicpJe83Pu0Ree6GYytcOapC0SpV/5omCaGqxjD4sh29UDDuPyrnsBoNSkyie3I1MQ/lzqntqr0yOgEPK1zGOD5X,iv:xKgsnj7X16ZLW2XpSPsz0mYsOiNp6dr0wvK8G1jXaVo=,tag:GE6UHbatAaMdBh/kcCEZWg==,type:str]
  jwt-public.pem: ENC[AES256_GCM,data:gdsDCglCcmioBAcX9wBzxV25tzwWisHfDmX7BRQIT0OTQ5ebNdr6EaWoCII/Q05CKsiw/SRlKyVRtt9Z5X9zcornp687BEqWgnUpcRphADBLpmlGqTRExkLsVJyRoSsu/KkwLvjwSXwIZYjAZ2VbBE036+cuxMNY5HCB97wqRaqTgC+oFTMpbB8kVCYBiCRsUWXG8Sg2UGYN9oWvA1Gdx9TVg3LD9gX/VzpXAL/6k9I2+O4ZCnjcqR0eaAwh21zb3nE5pvMUMqnRzjqrPZaD89Ih/EfxKOs2dlVxvry9kEOVqcvyy3pfynpZNcNnrDdj,iv:/sotXZn2gciwyuZNlyoiOCvhnIK4XUTZd6LJULi5ogs=,tag:NMGuHUaDVZoCSE6RtAkDfw==,type:str]
kind: Secret
metadata:
  name: api-jwt
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUXYxSGFOZ3BVYnBtWmEv
        aXZOV2Rtc3lMdkFpTkZOWGpZUTFsK0JIc25vClJydERtcEVONzdmK2tRSFBGS1pS
        Y2FTU1JaK0UzUW1WTzZHZmZqWjYxUEEKLS0tIFRkR0M0QU9IVklQU000a0ozcGRE
        Y09kZ0NqWEtocTU3YVl3V0RxZjB3aVkKVJYZOxebewxUf8BWqylSqWKY236nfRpf
        SLIky//0/vE5rd8YKYsmGij1VbQU84iN7MiDyZlMgcQGkMF2+E2eMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T13:33:41Z"
  mac: ENC[AES256_GCM,data:EhESSkD0kW87V25pZ81Px0dcSS+hwTcH8KTHzNVz9CUDE4jDLsX0ynQ8AfrJvpFbNlVC64nMfm6k37IiC++ekyNQjUyZn34afG6bc+d54og1nRwdY+nEF1TTNzj/RQ/EqWModgBy+n8x6iIQ+YmEareOdu9aMoYGV5rNqmNax50=,iv:9H7DfSMwohQFSKHUG5KdB/sv6JBvA1m40VOpHzOfXdU=,tag:PHSU9ecLMlbT9zEYxZ4vdw==,type:str]
  version: 3.13.3
