apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - ../../base
  - networkpolicy.yaml
  - jwt-secret.yaml
  - ingress.yaml

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: api-config
    literals:
      - ORIGIN=https://puuury.com
      - JWT_SIGNING_KID=k1
