apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      automountServiceAccountToken: false
      containers:
        - name: client
          image: mdstaicu/client
          envFrom:
            - secretRef:
                name: dotenv
          # ----------------------------------------------------------------------------------------
          #
          # Development only
          #
          # We use init containers to download the root certificate authority certificate,
          # that was used to sign the intermediate and leaf certificate of Traefik,
          # and mount the certificate to the client's container as NODE_EXTRA_CA_CERTS
          #
          # We need to do this because otherwise any HTTPS requests issued from the client to Traefik will fail
          # ----------------------------------------------------------------------------------------
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: /certs/pebble-root-ca.pem
            - name: REMIX_DEV_SERVER_WS_PORT
              value: "3001"
          volumeMounts:
            - name: certs
              mountPath: /certs
      initContainers:
        # ------------------------------------------
        #
        # Stage 1: Wait for Pebble to be available
        #
        # ------------------------------------------
        - name: client-wait-for-pebble
          image: alpine/curl
          command: ["/bin/sh", "-c"]
          args:
            [
              'while [[ "$(curl --insecure -s -o /dev/null -w %{http_code} https://pebble:15000/roots/0)" != "200" ]]; do echo "Waiting for Pebble..."; sleep 5; done',
            ]
        # ----------------------------------------------------------------------------------------
        #
        # Stage 2: Get the root CA used to sign Traefik's leaf and intermediate certificate
        #
        # ----------------------------------------------------------------------------------------
        - name: client-get-root-certs
          image: alpine/curl
          command: ["/bin/sh", "-c"]
          args:
            [
              "curl --insecure -s -o /certs/pebble-root-ca.pem https://pebble:15000/roots/0",
            ]
          volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: client-live-reload
      protocol: TCP
      port: 3001
      targetPort: 3001
