apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spaces

resources:
  - spaces-migrate-job.yaml
  - namespace.yaml

# TODO: Add and encrypt secret
# secretGenerator:
#   - name: spaces-db
#     literals:
#       - DATABASE_URL=postgres://postgres@postgres-srv:5432/spaces?sslmode=disable

generatorOptions:
  disableNameSuffixHash: true
