apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: relay
  namespace: flux-system
spec:
  image: ghcr.io/mstaicu/relay
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: relay
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: relay
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 5m
