apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-identities-api-and-migrate-to-postgres
spec:
  podSelector:
    matchLabels:
      app: identities-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: identities-api
        - podSelector:
            matchLabels:
              app: identities-migrate
      ports:
        - protocol: TCP
          port: 5432
