apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - ../../api
  - auth-api-ingress.yaml
  - auth-api-jwt.yaml
  - auth-np.yaml
  - auth-ns.yaml

patches:
  - path: auth-api-depl.yaml

configMapGenerator:
  - name: auth-api-cm
    literals:
      - ORIGIN=https://tma.com

# TODO: Add and encrypt secret
# secretGenerator:
#   - name: auth-db
#     literals:
#       - DATABASE_URL=postgres://postgres@postgres-srv:5432/auth?sslmode=disable

images:
  - name: mdstaicu/auth-api
    # This field is managed by this ImagePolicy: <namespace>:<imagepolicy-name>
    # meaning: flux-system:auth-api-latest
    newTag: latest # {"$imagepolicy": "flux-system:auth-api-latest"}
