apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: jetstream-controller-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - jetstream.nats.io
    resources:
      - streams
      - streams/status
      - consumers
      - consumers/status
      - streamtemplates
      - streamtemplates/status
      - accounts
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
