apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#more-practical-use-cases
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - auth
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
        - name: auth
          image: mdstaicu/auth
          env:
            - name: MONGO_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: auth_config
                  key: MONGO_DB_URI
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: auth_config
                  key: DOMAIN
            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: auth_config
                  key: ORIGIN

            - name: ACCESS_TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth_secrets
                  key: ACCESS_TOKEN_PRIVATE_KEY
            - name: ACCESS_TOKEN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth_secrets
                  key: ACCESS_TOKEN_PUBLIC_KEY
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth_secrets
                  key: REFRESH_TOKEN_SECRET

            - name: NATS_USERS_AUTH_CREDS
              valueFrom:
                secretKeyRef:
                  name: nats-users
                  key: nats_users_auth_creds

          #
          # total probe time =
          #     initialDelay + timeout + ( (periodSeconds + timeout) * (failureThreshold - 1) )
          #
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
