apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mdstaicu/auth
          env:
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: MONGO_DB_URI

            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: JWT_PRIVATE_KEY

            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: JWT_PUBLIC_KEY

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: PORT

            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: DOMAIN

            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: ORIGIN
          #
          # total probe time =
          #     initialDelay + timeout + ( (periodSeconds + timeout) * (failureThreshold - 1) )
          #
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5 # Start checking 5 seconds after the pod starts
            periodSeconds: 5 # Check every 5 seconds
            timeoutSeconds: 5 # Wait up to 5 seconds for a response
            failureThreshold: 1 # Mark as "not ready" after a single failure ( currently after 5 + 3 seconds )

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
