apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: auth-role-binding
subjects:
  - kind: ServiceAccount
    name: auth-serviceaccount
roleRef:
  kind: Role
  name: auth-role
  apiGroup: rbac.authorization.k8s.io
