apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: auth

requires:
  - path: workloads/postgres/skaffold.yaml
  - path: workloads/migrations/skaffold.yaml
  - path: workloads/api/skaffold.yaml
  - path: workloads/ui/skaffold.yaml
  - path: workloads/retention/skaffold.yaml
