apiVersion: apps/v1
kind: Deployment

metadata:
  name: identity-postgres
spec:
  template:
    spec:
      containers:
        - name: identity-postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
