apiVersion: batch/v1
kind: Job
metadata:
  name: auth-migrate

spec:
  backoffLimit: 4
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never

      initContainers:
        - name: wait-postgres
          image: postgres:18
          command:
            - sh
            - -c
            - |
              echo "waiting for postgres..."
              until pg_isready -h postgres-srv -p 5432 -d auth; do
                sleep 2
              done
              echo "postgres ready"

      containers:
        - name: migrate
          image: mdstaicu/auth-migrate:latest
          command:
            - sh
            - -c
            - |
              migrate \
                -path=/migrations \
                -database="$DATABASE_URL" \
                up

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-db
                  key: DATABASE_URL
