apiVersion: jetstream.nats.io/v1beta2
kind: Account

metadata:
  name: auth-api
spec:
  servers:
    - nats://nats-headless.nats.svc.cluster.local:4222
  user:
    secret:
      name: auth-api-nats-creds
    user: user
    password: password
