apiVersion: apps/v1
kind: Deployment

metadata:
  name: features-api-depl
spec:
  selector:
    matchLabels:
      app: features-api
  replicas: 3
  template:
    metadata:
      labels:
        app: features-api
    spec:
      terminationGracePeriodSeconds: 15
      serviceAccountName: features-api
      # Defense in deep, disable this at the pod level
      # to prevent overwrites at the service account level
      automountServiceAccountToken: false

      containers:
        - name: features-api
          image: mdstaicu/features-api
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: features-api-db
                  key: DATABASE_URL

            - name: IDENTITY_JWKS_URL
              value: http://traefik-srv.traefik.svc.cluster.local/.well-known/jwks.json

            - name: ACCESS_TOKEN_AUDIENCE
              value: aperitif-api

          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
