apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - features-api-ingress.yaml
  - features-np.yaml
  - features-api-depl.yaml
  - features-api-sa.yaml
  - features-api-srv.yaml
