apiVersion: apps/v1
kind: Deployment

metadata:
  name: identities-api-depl
spec:
  selector:
    matchLabels:
      app: identities-api
  replicas: 3
  template:
    metadata:
      labels:
        app: identities-api
    spec:
      terminationGracePeriodSeconds: 15
      serviceAccountName: identities-api
      # Defense in deep, disable this at the pod level
      # to prevent overwrites at the service account level
      automountServiceAccountToken: false

      containers:
        - name: identities-api
          image: mdstaicu/identities-api
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: identities-api-db
                  key: DATABASE_URL

            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: identities-api-cm
                  key: ORIGIN
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: identities-api-cm
                  key: JWT_AUDIENCE

            - name: JWT_PRIVATE_KEY_PATH
              value: /app/keys/jwt-private.pem
            - name: JWT_PUBLIC_KEY_PATH
              value: /app/keys/jwt-public.pem

            - name: OTEL_SERVICE_NAME
              value: identities-api

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-srv.otel.svc.cluster.local:4318

            - name: OTEL_METRICS_EXPORTER
              value: none

            - name: OTEL_LOGS_EXPORTER
              value: none

          volumeMounts:
            - name: identities-api-jwt
              mountPath: /app/keys
              readOnly: true

          #
          # total probe time =
          #     initialDelay + timeout + ( (periodSeconds + timeout) * (failureThreshold - 1) )
          #
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2

      volumes:
        - name: identities-api-jwt
          secret:
            secretName: identities-api-jwt
