apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - identities-api-depl.yaml
  - identities-api-ingress.yaml
  - identities-np.yaml
  - identities-api-sa.yaml
  - identities-api-srv.yaml
