apiVersion: batch/v1
kind: Job

metadata:
  name: migrate
spec:
  template:
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: migrate
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://accounts-postgres:5432/accounts?user=postgres&password=postgres"
