apiVersion: batch/v1
kind: Job

metadata:
  name: migrate
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: identities-migrate
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
          image: mdstaicu/identities-migrate

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: identities-migrate-db
                  key: DATABASE_URL
