# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute

# metadata:
#   name: auth-ui
# spec:
#   parentRefs:
#     - name: traefik-gw
#       namespace: traefik

#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /auth

#       backendRefs:
#         - name: auth-ui-srv
#           port: 3000

# ---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: auth-api
spec:
  parentRefs:
    - name: traefik-pgw
      namespace: traefik

    - name: traefik-igw
      namespace: traefik

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /auth/v1

      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /v1

      backendRefs:
        - name: auth-api-srv
          port: 3000
