apiVersion: batch/v1
kind: Job

metadata:
  name: tls-secrets-job
spec:
  template:
    spec:
      serviceAccountName: tls-secrets-sa
      restartPolicy: OnFailure
      volumes:
        - name: certs
          emptyDir: {}
      initContainers:
        - name: generate-certs
          image: smallstep/step-cli:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /certs
              cd /certs

              # 1. Generate Root CA (ECDSA)
              step certificate create root.linkerd.cluster.local ca.crt ca.key \
                --profile root-ca --no-password --insecure --not-after=87600h

              # 2. Generate Intermediate (Issuer)
              step certificate create identity.linkerd.cluster.local issuer.crt issuer.key \
                --profile intermediate-ca --not-after 8760h --no-password --insecure \
                --ca ca.crt --ca-key ca.key

              # ⬅️ Make all files world-readable
              chmod 0644 *.crt *.key

          volumeMounts:
            - name: certs
              mountPath: /certs

      containers:
        - name: create-secrets
          image: bitnami/kubectl:latest
          env:
            - name: LINKERD_NAMESPACE
              value: linkerd
            - name: TRAEFIK_NAMESPACE
              value: traefik
          command:
            - /bin/sh
            - -c
            - |
              set -e

              kubectl -n $LINKERD_NAMESPACE delete secret linkerd-identity-issuer || true
              kubectl -n $LINKERD_NAMESPACE create secret generic linkerd-identity-issuer \
                --from-file=tls.crt=/certs/issuer.crt \
                --from-file=tls.key=/certs/issuer.key \
                --from-file=ca.crt=/certs/ca.crt

              kubectl -n $LINKERD_NAMESPACE delete configmap linkerd-identity-trust-roots || true
              kubectl -n $LINKERD_NAMESPACE create configmap linkerd-identity-trust-roots \
                --from-file=ca-bundle.crt=/certs/ca.crt

              kubectl -n $TRAEFIK_NAMESPACE delete secret linkerd-trust-bundle || true
              kubectl -n $TRAEFIK_NAMESPACE create secret generic linkerd-trust-bundle \
                --from-file=ca.crt=/certs/ca.crt

              echo "Bootstrap completed: linkerd-identity-issuer, linkerd-identity-trust-roots, linkerd-trust-bundle, traefik-tls"
          volumeMounts:
            - name: certs
              mountPath: /certs
