apiVersion: apps/v1
kind: Deployment

metadata:
  name: accounts-projection
spec:
  template:
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: accounts-projection
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres:5432/plans"
            - name: NATS_URL
              value: nats://nats-client.nats.svc.cluster.local:4222
            - name: OTEL_SERVICE_NAME
              value: plans-accounts-projection
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.otel.svc.cluster.local:4318
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
