apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capabilities

resources:
  - namespace.yaml
  - ../../base
  - capabilities-api-db.yaml

patches:
  - path: capabilities-api-depl.yaml

images:
  - name: mdstaicu/capabilities-api
    newTag: latest
