apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-accounts-components-to-postgres
spec:
  podSelector:
    matchLabels:
      app: accounts-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: accounts-api
        - podSelector:
            matchLabels:
              app: accounts-migrate
        - podSelector:
            matchLabels:
              app: outbox-publisher
      ports:
        - protocol: TCP
          port: 5432
