apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: event-bus

manifests:
  kustomize:
    paths:
      - overlays/local

    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}
