apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identities

resources:
  - ../../base

images:
  - name: mdstaicu/identities-ui
    # This field is managed by this ImagePolicy: <namespace>:<imagepolicy-name>
    # meaning: flux-system:identities-ui-latest
    newTag: latest # {"$imagepolicy": "flux-system:identities-ui-latest"}
