apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenancy

resources:
  - ../../base

secretGenerator:
  - name: tenancy-api-db
    literals:
      - DATABASE_URL=postgres://postgres@postgres-srv:5432/tenancy?sslmode=disable
    options:
      disableNameSuffixHash: true

images:
  - name: mdstaicu/tenancy-api
    # This field is managed by this ImagePolicy: <namespace>:<imagepolicy-name>
    # meaning: flux-system:tenancy-api-latest
    newTag: latest # {"$imagepolicy": "flux-system:tenancy-api-latest"}
