apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenancy

resources:
  - namespace.yaml
  - ../../base
  - tenancy-api-db.yaml

patches:
  - path: tenancy-api-depl.yaml

images:
  - name: mdstaicu/tenancy-api
    newTag: latest
