apiVersion: apps/v1
kind: Deployment

metadata:
  name: accounts-api
spec:
  selector:
    matchLabels:
      app: accounts-api
  replicas: 3
  template:
    metadata:
      labels:
        app: accounts-api
    spec:
      terminationGracePeriodSeconds: 15
      automountServiceAccountToken: false

      containers:
        - name: accounts-api
          image: ghcr.io/mstaicu/accounts-api
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
