apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - accounts-api-internal-ingressroute.yaml
  - accounts-api-networkpolicy.yaml
  - accounts-api-deployment.yaml
  - accounts-api-service.yaml
