apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: auth-ui

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/auth-ui
      context: .
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - infra/overlays/local

deploy:
  kubectl: {}
