apiVersion: viaduct.ai/v1
kind: KSOPS

metadata:
  name: features-worker-ksops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - features-worker-db.yaml
