apiVersion: viaduct.ai/v1
kind: KSOPS

metadata:
  name: tenancy-migrate-ksops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - tenancy-migrate-db.yaml
