apiVersion: v1
kind: Secret
metadata:
  name: tenancy-migrate-db
stringData:
  FLYWAY_URL: ENC[AES256_GCM,data:RzKT+614CA7EWssadjb5CVHup797SI9FGG7wp1t/ofzgcjub99WxjTZ1tGL5gKOTFefeKhCLzbKWs0c=,iv:W3yA64Dn3zyjjA7tnB1ZWCmB2lDvj/KyvRNiay0MLi4=,tag:QeNIhMwEKvEhZAGTJYtzFQ==,type:str]
  FLYWAY_USER: ENC[AES256_GCM,data:YQgzTVMG68gMoeiHSzTkGg==,iv:zDKJvSFOZKcmM2xTLnPkhYpO34TE2aktRdWpTV6GLDA=,tag:8OFwDwcLJc6iEGL342EcEQ==,type:str]
  FLYWAY_PASSWORD: ENC[AES256_GCM,data:nL+b,iv:qlrtXNnqUW7mQn3z4nHKCOZnxQI/c1qXkQ/ZATYNx+4=,tag:Iw7zXhxxVo1zaHwXtzmryw==,type:str]
sops:
  age:
    - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NHpLMWttQmFYV0k2d1hk
        RFpyWTJFdWVZOTIzbnBxVTRZYTAxYzRKL3lFCmVGZEdsbnN2czlrQWRBM0hWdkZ4
        V2lLS1BXR08rbThobzhiMWhDKzVjTDQKLS0tIE5nVWpiUlpTVzhKWGdSVU0zSGlJ
        WTBpSysxL2tKNEtUL0R1bWk1RDNnOVEKZoQ1ua8Xf5k/80Yn7T49NSwfKlJmTAvH
        a1HZpNAKALCLsk/zeLSe5alazU0iNVQO9Qkih6GW1znB9TyHHmFr4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T18:53:55Z"
  mac: ENC[AES256_GCM,data:nw4ILq3W7nLjgOKXcsm0xJCz1WGkTMbEK6rTgJ3v5U58JKV/9IwhVJV/xGVgPwXYY0DURfW5CGV8jIjxJQ0x+O/mXSIA7OK2TPWBhA9cEFez5XuyVpRoCqPzN7Koql8UwFMSRY8XWAnYOglBQBQ2M9sahuN+XiYdJpEKMAcETIk=,iv:nDrEs4YWAxgxyTi0Whh1ORR+qNAVYn/9QxTG1rhlYnA=,tag:lM1nseV2X2ldYqx22M0CAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
