apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenancy

resources:
  - namespace.yaml
  - ../../base
  - tenancy-migrate-db.yaml

images:
  - name: mdstaicu/tenancy-migrate
    newTag: latest
