apiVersion: apps/v1
kind: Deployment

metadata:
  name: identity-ui
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: identity-ui
          env:
            - name: API_INTERNAL_V1_URL
              value: http://traefik-internal.traefik.svc.cluster.local/v1
            - name: NODE_OPTIONS
              value: "--experimental-loader=@opentelemetry/instrumentation/hook.mjs --import ./app/platform/otel.ts"
            - name: OTEL_SERVICE_NAME
              value: identity-ui
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://signoz-ingester.signoz.svc.cluster.local:4318
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
