apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - ../../base
  - accounts-api-public-ingressroute.yaml
  - accounts-api-public-docs-ingressroute.yaml

patches:
  - path: accounts-api-deployment.yaml

images:
  - name: ghcr.io/mstaicu/accounts-api
    newTag: latest
