apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: api-public
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`api.tma.com`) && Path(`/v1/accounts`)
      services:
        - name: api
          port: 3000
  tls:
    certResolver: le
    domains:
      - main: api.tma.com
