apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  replicas: 3
  template:
    spec:
      affinity: null
      serviceAccountName: nats-sa
      initContainers:
        - name: wait-jobs
          image: bitnami/kubectl:latest
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/sh
            - -c
            - |
              kubectl wait --for=condition=complete --timeout=300s job/nats-secrets-job -n "$NAMESPACE" > /dev/null 2>&1

              until kubectl get secret nats-resolver -n "$NAMESPACE" > /dev/null 2>&1; do
                sleep 2
              done

              kubectl get secret nats-resolver -n "$NAMESPACE" -o jsonpath="{.data.resolver\.conf}" | base64 -d > /secrets/resolver.conf

          volumeMounts:
            - name: nats-secrets-volume
              mountPath: /secrets

      containers:
        - name: nats
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: nats-secrets-volume
              mountPath: /secrets
            - name: nats-pvc
              mountPath: /data
      volumes:
        - name: nats-secrets-volume
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: nats-pvc
      spec:
        storageClassName: hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
