apiVersion: batch/v1
kind: Job

metadata:
  name: nats-secrets-job
spec:
  template:
    spec:
      serviceAccountName: secrets-manager-sa
      restartPolicy: Never
      initContainers:
        - name: generate-secrets
          image: natsio/nats-box:latest
          command:
            - /bin/sh
            - /scripts/gen-secrets.sh

          volumeMounts:
            - name: nats-scripts-cm
              mountPath: /scripts
            - name: nats-secrets-volume
              mountPath: /secrets

      containers:
        - name: create-secret
          image: bitnami/kubectl:latest
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/sh
            - /scripts/create-secrets.sh

          volumeMounts:
            - name: nats-scripts-cm
              mountPath: /scripts
            - name: nats-secrets-volume
              mountPath: /secrets

      volumes:
        - name: nats-secrets-volume
          emptyDir: {}
        - name: nats-scripts-cm
          configMap:
            name: nats-scripts-cm
