apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base

patches:
  - path: identity-migrations-job.yaml

images:
  - name: ghcr.io/mstaicu/identity-migrations
    newTag: latest
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000 # {"$imagepolicy": "flux-system:identity-migrations:digest"}
