apiVersion: v1
data:
  CF_DNS_API_TOKEN: ENC[AES256_GCM,data:WM5hCTKAwq3QFwsolGnL5kYLjG/zmkTO/RQ1ndNnbdi5TU1cEIPtDv3C+PUL2NRTuT3oz0bSCwaNrFzgRopCy+5RcI4nA5huDWJEjsL7lSn913TaWzblww==,iv:q8oPwVHiHYpypIwtNZXhaQ/Hd3esqrtBoowAinIAsCM=,tag:zkA++eP9JF7z0Kx1hEfgGw==,type:str]
kind: Secret
metadata:
  name: cloudflare-dns
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOFR2OFFLczFYNllhODFV
        SHlMYUxnaHozZ3kxOEMwcXBNejRRUGVXWkQ0CktScmRUL3JWb2k1YmI1aGdUbWtB
        anE3MnpySjhpeWVCYUcwbTdhUDRySW8KLS0tIHZIazFlbGtjQk5SOWFjVmw0M2lD
        RytkbXo5TUE4U1Z4VDZHZnRQOFlBSGsK1Iqp7dlal4qKIc25AFndrHpNky8LZGVh
        9NNytBbnvAiHhYtc72U/K28wplwCp6qvMrsHOf/o1+3E6o1WbSYttw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T13:33:42Z"
  mac: ENC[AES256_GCM,data:g5c88gG69alkcvAYJdIrVZbknfP4oIwhrsSPWVjvX1owZa4Tdo+iCVHRI/dMsKvqSL51v2vZwJbHC6DFqHeAcYPa6uw3Ihfisj1LQk8EV00xXK1g3Bf1H83jWB8LCfAWg5NyxlfwVM6gsO/CmBwDr98AJsVRsht6S5l7gGJaRPY=,iv:u7+ZI+nTjoAaGceEabI0NUdMN0e0bfjYPO7WuiiuNTA=,tag:d+iXjNCrRCoh/cmu8G3p3Q==,type:str]
  version: 3.13.3
