apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns
type: Opaque
stringData:
  CF_DNS_API_TOKEN: ENC[AES256_GCM,data:CVDXAfOMd/fXps8ZWnhZM36tY55DiQtWepTKhu+46/y4QM4DXr47xzGbmiPwhLlJ/NYJbdk/gBAWsLtCBzTNVA==,iv:SeVsHuiR0RXeNPZquMYIjA/2dyK5iWB60KNIGYjCLW8=,tag:ORPDhaNctBw6V/WduNLt7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ2dPSHJLNVFPdzRWRzRz
        YTdyVGZLT09JL2dNNW1MSGJEUWt3N3FYWFE4ClEvKzZrZFpta3ZaRmN1b09raDEr
        cGFTQytsWFFYUVJMcEpuWkZnK2JRV3cKLS0tIDA4cEJlNUh0Z1JPdjM1azhiY0Q2
        TnRMUGhWYmlZSjYxOUl0aXpXTGdobUUK0c5Gn5o72W+k6xIXU4wJlJfBYcLXMlLD
        GdaMUoCOFTNcSHmcmhOZxb+Bj775Pper7130V0pE+QWnWxPkey7YHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j2qashtf39jk0dxytcx66e5v24ze2vmmj3ah84aewj57mumy2pgqhreu86
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T14:48:09Z"
  mac: ENC[AES256_GCM,data:n/OwjD+qJwIaXdfa8osImJd411J1rMrGs2py3gpBIpMnVxXWQw/Y3bmJKC1Cw/VAjqN2aNzanrVEJcVIRyxk2tvwsa6ye+H3qS4kUBWYWm+tj5iKWod7/HkOLWwHmJeJqw/ZSku4i/qfdpc9Xa+A26m++0JY7zoey2EXgeHTyog=,iv:AWN8grk4KBe3SBdqR1Kt9ccg1JiTFZvO7KJ6RmrNIvo=,tag:BmWue8Q/k1cF7nh3Z3VO7A==,type:str]
  version: 3.12.2
