server_name: $HOSTNAME

port: 4222
http_port: 8222

jetstream {
  store_dir: "/data"
}

cluster {
  name: "EU"
  port: 6222
  routes = [
    "nats://nats-depl-0.nats-headless.nats.svc.cluster.local:6222"
  ]
}

authorization {
  default_permissions = {
    publish = []
    subscribe = []
  }

  users = [
    {
      user: "auth-api"
      password: ${NATS_AUTH_API_PASSWORD}
      permissions = {
        publish = ["auth.>"]
        subscribe = ["auth.>"]
      }
    },
    {
      user: "auth-worker"
      password: ${NATS_AUTH_WORKER_PASSWORD}
      permissions = {
        publish = ["auth.>"]
        subscribe = ["auth.>"]
      }
    },
    {
      user: "nack"
      password: ${NATS_NACK_PASSWORD}
      permissions = {
        # publish = [">", "$JS.API.>"]
        publish = [">"]
        # subscribe = [">", "$JS.API.>"]
        subscribe = [">"]
      }
    }
  ]
}