apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - otel-agent-serviceaccount.yaml
  - otel-agent-clusterrole.yaml
  - otel-agent-clusterrolebinding.yaml
  - otel-agent-daemonset.yaml
  - otel-collector-deployment.yaml
  - otel-collector-service.yaml
  - otel-collector-networkpolicy.yaml

configMapGenerator:
  - name: otel-agent
    files:
      - otel-config.yaml=otel-agent-config.yaml
  - name: otel-collector
    files:
      - otel-config.yaml=otel-collector-config.yaml
