apiVersion: apps/v1
kind: Deployment

metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      automountServiceAccountToken: false
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.147.0
          args:
            - --config=/conf/otel-config.yaml

          ports:
            - containerPort: 4318
            - containerPort: 4317
            - name: health
              containerPort: 13133

          readinessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1

          livenessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1

          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: otel-collector
