apiVersion: v1
kind: ConfigMap

metadata:
  name: otel-agent
data:
  otel-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    receivers:
      filelog:
        include:
          - /var/log/containers/*.log
        exclude:
          - /var/log/containers/otel-agent*_otel_*.log
          - /var/log/containers/otel-collector*_otel_*.log
        include_file_path: true
        include_file_name: false
        exclude_older_than: 10m
        start_at: end
        operators:
          - type: container

      kubeletstats:
        auth_type: serviceAccount
        collection_interval: 30s
        endpoint: https://${env:K8S_NODE_NAME}:10250
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container
        resource_attributes:
          aws.volume.id:
            enabled: false
          fs.type:
            enabled: false
          gce.pd.name:
            enabled: false
          glusterfs.endpoints.name:
            enabled: false
          glusterfs.path:
            enabled: false
          partition:
            enabled: false

    processors:
      k8s_attributes:
        auth_type: serviceAccount

      batch:

    exporters:
      otlp_grpc:
        endpoint: otel-collector.otel.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      extensions:
        - health_check

      pipelines:
        logs:
          receivers:
            - filelog
          processors:
            - k8s_attributes
            - batch
          exporters:
            - otlp_grpc

        metrics:
          receivers:
            - kubeletstats
          processors:
            - k8s_attributes
            - batch
          exporters:
            - otlp_grpc
