apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: otel-agent
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - nodes/stats
      - pods
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
