apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: otel-agent
spec:
  selector:
    matchLabels:
      app: otel-agent
  template:
    metadata:
      labels:
        app: otel-agent
    spec:
      serviceAccountName: otel-agent
      containers:
        - name: otel-agent
          image: otel/opentelemetry-collector-contrib:0.147.0
          args:
            - --config=/conf/otel-config.yaml

          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          ports:
            - name: health
              containerPort: 13133

          readinessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1

          livenessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1

          volumeMounts:
            - name: config
              mountPath: /conf
            - name: pod-logs
              mountPath: /var/log/pods
              readOnly: true
            - name: container-logs
              mountPath: /var/log/containers
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: otel-agent
        - name: pod-logs
          hostPath:
            path: /var/log/pods
        - name: container-logs
          hostPath:
            path: /var/log/containers
