apiVersion: v1
kind: ServiceAccount

metadata:
  name: otel-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: otel-agent
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - nodes/stats
      - pods
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: otel-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-agent
subjects:
  - kind: ServiceAccount
    name: otel-agent
