apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: outbox-relay-streams
    files:
      - streams.json

resources:
  - deployment.yaml
  - networkpolicy.yaml
