apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenancy

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: tenancy-postgres-depl.yaml

configMapGenerator:
  - name: tenancy-postgres-init
    files:
      - tenancy-postgres-init.sql
