CREATE ROLE tenancy_migrator
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

CREATE ROLE tenancy_api
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

CREATE ROLE tenancy_worker
WITH LOGIN INHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
PASSWORD 'dev';

REVOKE CONNECT, TEMPORARY ON DATABASE tenancy FROM PUBLIC;

GRANT CONNECT, CREATE, TEMPORARY
ON DATABASE tenancy
TO tenancy_migrator;

GRANT CONNECT
ON DATABASE tenancy
TO tenancy_api,
   tenancy_worker;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;

GRANT USAGE, CREATE
ON SCHEMA public
TO tenancy_migrator;

GRANT USAGE
ON SCHEMA public
TO tenancy_api,
   tenancy_worker;
