apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: traefik-http-dash
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`tma.com`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: traefik-https-dash
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`tma.com`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefik-tls
    # options:
    #   name: tls-options
    #   namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption

metadata:
  name: tls-options
spec:
  minVersion: VersionTLS12
  curvePreferences:
    - CurveP256
    - CurveP384
    - CurveP521
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  sniStrict: true
