apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - identity-ui-depl.yaml
  - identity-ui-ingress.yaml
  - identity-ui-middlewares.yaml
  - identity-ui-np.yaml
  - identity-ui-sa.yaml
  - identity-ui-srv.yaml
