apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - ../../base
  - networkpolicy.yaml
patches:
  - path: job.yaml
images:
  - name: ghcr.io/mstaicu/auth-migrations
    newTag: latest
    digest: sha256:026a705996cf65f40b7ff5281912e127ebfcb881e878c43c8ab430c9cba81d41 # {"$imagepolicy": "flux-system:auth-migrations:digest"}
