apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform.yaml
  - images/automation.yaml
  - images/auth.yaml
  - images/accounts.yaml
  - images/plans.yaml
  - images/relay.yaml
  - domains/auth.yaml
  - domains/accounts.yaml
  - domains/plans.yaml
