apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform.yaml
  - images/automation.yaml
  - images/identity.yaml
  - images/accounts.yaml
  - images/entitlements.yaml
  - domains/identity.yaml
  - domains/accounts.yaml
  - domains/entitlements.yaml
