apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform
  - domains/identity-namespace.yaml
  - domains/accounts-namespace.yaml
  - domains/entitlements-namespace.yaml
  - domains
  - image-automation.yaml
