apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: traefik-crds
spec:
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
  path: ./k8s/infra/traefik/crd
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
