apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plans

resources:
  - ../../base
  - networkpolicy.yaml

configMapGenerator:
  - name: outbox-relay-streams
    files:
      - streams.json

patches:
  - path: deployment.yaml
