apiVersion: batch/v1
kind: Job

metadata:
  name: migrations
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: documents-migrations
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never

      containers:
        - name: migrations
          image: ghcr.io/mstaicu/documents-migrations

          env:
            - name: FLYWAY_LOCATIONS
              value: filesystem:/db/sql
            - name: FLYWAY_FAIL_ON_MISSING_LOCATIONS
              value: "true"
