apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel

resources:
  - ../../base
  - openobserve-statefulset.yaml
  - openobserve-service.yaml
  - openobserve-networkpolicy.yaml
  - openobserve-secret.yaml

configMapGenerator:
  - name: collector
    files:
      - otel-config.yaml=collector-config.yaml

patches:
  - path: collector-deployment.yaml
