apiVersion: v1
data:
  OPENOBSERVE_TOKEN: ENC[AES256_GCM,data:eSsgCGuRELNDeSmTvSoDETXhTuu7IrjqRwIpc/oBNZKKOmtRc4nD8Qqx6oEqJlAO,iv:YGwYOV3OVsdJJlxPZ9i5ktgizXGO4hUmBxJjUJIad64=,tag:G33stHzhpvihM1iEli36GQ==,type:str]
  ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:QPAuekZsikrg80c3bi5+6VdI6e/eoh6B2YQZgQ==,iv:Fv//BpkKoPIadEhvqx9yoZ+39VTQauacsmo1I32mhSk=,tag:vuHGCI5sFlcjDexZofL2tg==,type:str]
  ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:UsExIJXf9bk=,iv:FBOpkkwmbGg9P2fRdiTJDf+1wagyr8vqKP4uRbE1Uek=,tag:7sD+jD/IHyOsK67/D10soQ==,type:str]
kind: Secret
metadata:
  name: openobserve
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeE9FMXJrSmNaT0NpVmFj
        aCtwK1N0QWRrYjJiZ1NGcHNnbW9nMWQweFZFCmZJK3IwQjFkdHpGTU5iWXQxMHc3
        UUhmYlB2SExHUk1zWTVCeFhycnlyL2cKLS0tIGEwWlNhaFYxeFYyL2VuN0E0Q09C
        UzlaNGg4MkU0dUpwT0ZFVW5RZ29ZV1UKRgim1Rq1iOTU9jW/vLbPOmlG+DLhvnks
        n3HKplVAicRAa3u9XbiMkMMF6qycw7M0b9ylS479Ik1dNH5N16M99Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j2qashtf39jk0dxytcx66e5v24ze2vmmj3ah84aewj57mumy2pgqhreu86
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T11:07:05Z"
  mac: ENC[AES256_GCM,data:BL2rG7ORBPgop+/qkRh94YMNvCpNXsmAJSRshXzeoSPbVe0wZCq7j0JpaJI5Y/7mLPZnD4bnlB3oK27plOgBfy7sz5A93NgY9g3TSVSTaUSw5ZuGxuECPikAb6y2UBf8r7nVkdhtOtljI9CN/m7bmsuytwrG9vGuRBXnTdaK6g4=,iv:lt12ad7jd/vOH+vVCbuffUbmXdYCaNqUWJ23IK67lHY=,tag:hqtRwBiBf2HvO4klTos8Gg==,type:str]
  version: 3.13.1
