apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik-crd.yaml
  - traefik-depl.yaml
  - traefik-role.yaml
  - traefik-rolebinding.yaml
  - traefik-routes.yaml
  - traefik-sa.yaml
