apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/nats
  - nats-job-secrets.yaml

configMapGenerator:
  - name: nats-cm-server-conf
    files:
      - nats-server.conf=nats-server.conf
  - name: nats-cm-scripts
    files:
      - create-secrets.sh=scripts/create-secrets.sh
      - generate-secrets.sh=scripts/generate-secrets.sh

patches:
  - path: nats-depl.yaml
