apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nats-sa-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nats-sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: nats-sa
roleRef:
  kind: Role
  name: nats-sa-role
  apiGroup: rbac.authorization.k8s.io
