apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  template:
    spec:
      affinity: null
      containers:
        - name: nats
          volumeMounts:
            - name: nats-storage
              mountPath: /data
      volumes:
        - name: nats-storage
          hostPath:
            path: /tmp/nats-storage
            type: DirectoryOrCreate
