apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nats
  serviceName: nats-headless
  template:
    metadata:
      labels:
        app: nats
    spec:
      affinity: null
