apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  template:
    spec:
      affinity: null
      readinessGates:
        - conditionType: SecretsReady
      containers:
        - name: nats
          lifecycle:
            preStop:
              exec:
                command:
                  - nats-server
                  - -sl=ldm=/tmp/nats.pid
          volumeMounts:
            - name: nats-resolver-volume
              mountPath: /etc/resolver.conf
              subPath: resolver.conf
            - name: nats-storage
              mountPath: /data
      volumes:
        - name: nats-resolver-volume
          secret:
            secretName: nats-resolver-secret

  volumeClaimTemplates:
    - metadata:
        name: nats-storage
      spec:
        storageClassName: hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
