apiVersion: jetstream.nats.io/v1beta2
kind: Stream

metadata:
  name: resources
  namespace: dev
spec:
  name: resources
  retention: interest
  subjects: ["subscriptions.*"]
---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer

metadata:
  name: auth-subscriptions
  namespace: dev
spec:
  streamName: resources

  ackPolicy: explicit
  deliverPolicy: all
  durableName: auth-subscriptions

  filterSubjects:
    - subscriptions.created
    - subscriptions.updated
    - subscriptions.deleted
