apiVersion: batch/v1
kind: Job

metadata:
  name: nats-secrets-job
spec:
  template:
    spec:
      serviceAccountName: secrets-manager-sa
      restartPolicy: Never
      initContainers:
        - name: nats-ic-generate-secrets
          image: natsio/nats-box:latest
          command:
            - /bin/sh
            - /scripts/generate-secrets.sh
          volumeMounts:
            - name: nats-cm-scripts
              mountPath: /scripts
            - name: nats-volume-scripts
              mountPath: /secrets

      containers:
        - name: nats-ic-create-secret
          image: bitnami/kubectl:latest
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/sh
            - /scripts/create-secrets.sh
          volumeMounts:
            - name: nats-cm-scripts
              mountPath: /scripts
            - name: nats-volume-scripts
              mountPath: /secrets

      volumes:
        - name: nats-volume-scripts
          emptyDir: {}
        - name: nats-cm-scripts
          configMap:
            name: nats-cm-scripts
