apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  template:
    spec:
      affinity: null
      containers:
        - name: nats
          lifecycle:
            preStop:
              exec:
                command:
                  - nats-server
                  - -sl=ldm=/tmp/nats.pid
          volumeMounts:
            - name: nats-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: nats-storage
      spec:
        storageClassName: hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
