apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-server-config-cm
data:
  #
  # https://github.com/nats-io/nats-docker/blob/256811340a89b8a3b78f1a144b6a87fba4424b67/2.10.x/scratch/Dockerfile#L9
  # https://docs.nats.io/running-a-nats-service/configuration/clustering/jetstream_clustering#raft
  #
  nats-server.conf: |
    server_name=$HOSTNAME

    accounts: {
      $SYS: {
        users: [
          { user: admin, password: password }
        ]
      },
      TMA: {
        jetstream: enabled,
        users: [
          { user: me, password: admin }
        ]
      }
    }

    jetstream {
      "store_dir": "/data"
    }

    cluster: {
      name: EU,
      port: 6222,
      routes: [
        "nats://nats-depl-0.nats-headless.default.svc.cluster.local:6222"
      ]
    }

#
# EDIT: No longer true apparently
# Depending on cluster provider, the route URL for the gossip protocol might differ
# For example, on Digital Ocean, we should use nats://nats-0.nats-headless:6222
# but locally on k8s with Docker Desktop, we should use nats://nats-depl-0.nats-headless.default.svc.cluster.local:6222
#
# Since the cluster uses a gossiping protocol to uncover other replicas, we don't need to specify
# the URL's for all seed servers in the routes array, we can keep only the first one

# The official deployment files however keep all the routes in the config
#     routes: [
#       "nats://nats-0.nats-headless:6222",
#       "nats://nats-1.nats-headless:6222",
#       "nats://nats-2.nats-headless:6222",
#     ]
