apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nats
  serviceName: nats-headless
  template:
    metadata:
      labels:
        app: nats
    spec:
      affinity: null
      automountServiceAccountToken: false
      containers:
        - name: nats
          image: nats:alpine
          args: ["-c", "/etc/nats/nats-server.conf"]
          ports:
            - name: nats-client
              containerPort: 4222
            - name: nats-cluster
              containerPort: 6222
          volumeMounts:
            - name: nats-storage
              mountPath: /data
            - name: nats-cm
              mountPath: /etc/nats/
  volumeClaimTemplates:
    - metadata:
        name: nats-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
