apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: secrets-manager-binding
subjects:
  - kind: ServiceAccount
    name: secrets-manager-serviceaccount
roleRef:
  kind: Role
  name: secrets-manager-role
  apiGroup: rbac.authorization.k8s.io
