apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - ../../base
  - jwt-secret.yaml
  - public-ingressroute.yaml
  - public-docs-ingressroute.yaml
  - public-jwks-ingressroute.yaml

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: api-config
    literals:
      - ORIGIN=https://tma.com

images:
  - name: ghcr.io/mstaicu/auth-api
    newTag: latest
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000 # {"$imagepolicy": "flux-system:auth-api:digest"}
