apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: identity-cleanup
spec:
  podSelector:
    matchLabels:
      app: identity-cleanup
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: identity-postgres
      ports:
        - protocol: TCP
          port: 5432
