apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - headless-service.yaml
  - client-service.yaml

configMapGenerator:
  - name: nats-config
    files:
      - nats.conf=nats.conf
