apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository

metadata:
  name: spaces-api
spec:
  image: docker.io/mdstaicu/spaces-api
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy

metadata:
  name: spaces-api-latest
spec:
  imageRepositoryRef:
    name: spaces-api
  filterTags:
    pattern: "^[a-f0-9]{7}$"
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation

metadata:
  name: spaces
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@tma.com
        name: FluxCD Bot
    push:
      branch: master
  update:
    path: ./k8s/domains/spaces/infra/env/live
    strategy: Setters
