apiVersion: apps/v1
kind: Deployment

metadata:
  name: accounts-postgres-depl
spec:
  template:
    spec:
      containers:
        - name: accounts-postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
