apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO: Omitting the CRDs so that they are no deleted when I close the skaffold dev -p depl
resources:
  # - gateway-api-crd.yaml
  # - linkerd-crd.yaml
  # - linkerd-depl.yaml
  - linkerd-ns.yaml
