apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: plans-api

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/plans-api
      context: .
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - infra/overlays/local-edge

deploy:
  kubectl: {}
