apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  template:
    spec:
      containers:
        - name: nats
          volumeMounts:
            - name: nats-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: nats-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
