apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - namespace.yaml
  - ../../base

generators:
  - ksops-generator.yaml

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: api-config
    literals:
      - ORIGIN=https://tma.com

generatorOptions:
  disableNameSuffixHash: true
