name: auth worker

on:
  push:
    paths:
      - "auth-worker/**"
    branches:
      - master
  pull_request:
    paths:
      - "auth-worker/**"

env:
  REGISTRY: docker.io
  IMAGE_NAME: mdstaicu/auth-worker

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-worker
    steps:
      - uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install deps
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm test

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-worker
    steps:
      - uses: actions/checkout@v4
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set short sha
        id: short_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: set image tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "tag=pr-${{ github.event.number }}-${{ steps.short_sha.outputs.sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.short_sha.outputs.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: build and push image
        uses: docker/build-push-action@v5
        with:
          context: auth-worker
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
