name: CD / Entitlements / Migrate

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "domains/entitlements/packages/database/Dockerfile"
      - "domains/entitlements/packages/database/.dockerignore"
      - "domains/entitlements/packages/database/sql/**"

permissions:
  contents: write
  packages: write

jobs:
  cd:
    uses: ./.github/workflows/cd-unit.yaml
    with:
      build_context: domains/entitlements/packages/database
      domain: entitlements
      image: ghcr.io/mstaicu/entitlements-migrate
      overlay: domains/entitlements/infra/migrate/overlays/prod-eu
      unit: migrate
