name: CI / Accounts

on:
  pull_request:
    paths:
      - "domains/accounts/**"

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-domain.yaml
    with:
      domain: accounts
    secrets:
      EPHEMERAL_SOPS_AGE_KEY: ${{ secrets.EPHEMERAL_SOPS_AGE_KEY }}
