name: CI / Identity

on:
  pull_request:
    paths:
      - "domains/identity/**"

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-domain.yaml
    with:
      domain: identity
    secrets:
      EPHEMERAL_SOPS_AGE_KEY: ${{ secrets.EPHEMERAL_SOPS_AGE_KEY }}
