name: deployment / identity / ui

on:
  push:
    branches:
      - master
    paths:
      - "domains/identity/packages/ui/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/identity/packages/ui
      domain: identity
      image: mdstaicu/identity-ui
      manifest: domains/identity/infra/ui/overlays/prod-eu
      unit: ui
    secrets: inherit
