name: deployment / documents / worker

on:
  push:
    branches:
      - master
    paths:
      - "domains/documents/packages/worker/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/documents/packages/worker
      domain: documents
      image: mdstaicu/documents-worker
      manifest: domains/documents/infra/worker/overlays/live
      unit: worker
    secrets: inherit
