name: deployment / accounts / worker

on:
  push:
    branches:
      - master
    paths:
      - "domains/accounts/packages/worker/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/accounts/packages/worker
      domain: accounts
      image: mdstaicu/accounts-worker
      manifest: domains/accounts/infra/worker/overlays/prod-eu
      unit: worker
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
