name: deployment / documents / ui

on:
  push:
    branches:
      - master
    paths:
      - "domains/documents/packages/ui/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/documents/packages/ui
      domain: documents
      image: mdstaicu/documents-ui
      manifest: domains/documents/infra/ui/overlays/prod-eu
      unit: ui
    secrets: inherit
