name: deployment / accounts / api

on:
  push:
    branches:
      - master
    paths:
      - "domains/accounts/packages/api/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/accounts/packages/api
      domain: accounts
      image: mdstaicu/accounts-api
      manifest: domains/accounts/infra/api/overlays/prod-eu
      unit: api
    secrets: inherit
