name: deployment / identity / api

on:
  push:
    branches:
      - master
    paths:
      - "domains/identity/packages/api/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/identity/packages/api
      domain: identity
      image: mdstaicu/identity-api
      manifest: domains/identity/infra/api/overlays/live
      unit: api
    secrets: inherit
