name: deployment / capabilities / migrate

on:
  push:
    branches:
      - master
    paths:
      - "domains/capabilities/packages/migrate/Dockerfile"
      - "domains/capabilities/packages/migrate/migrations/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/capabilities/packages/migrate
      domain: capabilities
      image: mdstaicu/capabilities-migrate
      manifest: domains/capabilities/infra/migrate/overlays/live
      unit: migrate
    secrets: inherit
