name: deployment / identity / migrate

on:
  push:
    branches:
      - master
    paths:
      - "domains/identity/packages/migrate/Dockerfile"
      - "domains/identity/packages/migrate/migrations/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/identity/packages/migrate
      domain: identity
      image: mdstaicu/identity-migrate
      manifest: domains/identity/infra/migrate/overlays/live
      unit: migrate
    secrets: inherit
