name: deployment / documents / api

on:
  push:
    branches:
      - master
    paths:
      - "domains/documents/packages/api/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/documents/packages/api
      domain: documents
      image: mdstaicu/documents-api
      manifest: domains/documents/infra/api/overlays/live
      unit: api
    secrets: inherit
