name: deploy-ticket

on:
  push:
    branches:
      - master
    paths:
      - "ticket/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticket && docker build -t mdstaicu/ticket .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push mdstaicu/ticket
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # Get the name of the cluster from DigitalOcean, in this case "k8s-ticketing"
      - run: doctl kubernetes cluster kubeconfig save k8s-ticketing
      # Use the name of the deployment as specified in the depl file, in the metadata section, in this case "tickets-depl"
      - run: kubectl rollout restart deployment tickets-depl
