name: deployment / documents / migrate

on:
  push:
    branches:
      - master
    paths:
      - "domains/documents/packages/database/Dockerfile"
      - "domains/documents/packages/database/sql/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/documents/packages/database
      domain: documents
      image: mdstaicu/documents-migrate
      manifest: domains/documents/infra/migrate/overlays/prod-eu
      unit: migrate
    secrets: inherit
