name: deployment / capabilities / worker

on:
  push:
    branches:
      - master
    paths:
      - "domains/capabilities/packages/worker/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/capabilities/packages/worker
      domain: capabilities
      image: mdstaicu/capabilities-worker
      manifest: domains/capabilities/infra/worker/overlays/prod-eu
      unit: worker
    secrets: inherit
