name: deployment / entitlements / worker

on:
  push:
    branches:
      - master
    paths:
      - "domains/entitlements/packages/worker/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/entitlements/packages/worker
      domain: entitlements
      image: mdstaicu/entitlements-worker
      manifest: domains/entitlements/infra/worker/overlays/prod-eu
      unit: worker
    secrets: inherit
