name: deployment / accounts / migrate

on:
  push:
    branches:
      - master
    paths:
      - "domains/accounts/packages/migrate/Dockerfile"
      - "domains/accounts/packages/migrate/migrations/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/accounts/packages/migrate
      domain: accounts
      image: mdstaicu/accounts-migrate
      manifest: domains/accounts/infra/migrate/overlays/prod-eu
      unit: migrate
    secrets: inherit
