name: deployment / documents / migrate

on:
  push:
    branches:
      - master
    paths:
      - "domains/documents/packages/migrate/Dockerfile"
      - "domains/documents/packages/migrate/migrations/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/documents/packages/migrate
      domain: documents
      image: mdstaicu/documents-migrate
      manifest: domains/documents/infra/migrate/overlays/live
      unit: migrate
    secrets: inherit
