name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # Get the name of the cluster from DigitalOcean, in this case "k8s-ticketing"
      - run: doctl kubernetes cluster kubeconfig save k8s-ticketing
      # Apply all the config files from the infra/k8s dir
      - run: kubectl apply -f infra/k8s-setup
      - run: kubectl apply -f infra/k8s
      - run: kubectl apply -f infra/k8s-prod
