name: deployment / accounts / migrate

on:
  push:
    branches:
      - master
    paths:
      - "domains/accounts/packages/database/Dockerfile"
      - "domains/accounts/packages/database/.dockerignore"
      - "domains/accounts/packages/database/sql/**"

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      context: domains/accounts/packages/database
      domain: accounts
      image: mdstaicu/accounts-migrate
      manifest: domains/accounts/infra/migrate/overlays/prod-eu
      unit: migrate
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
