name: integration / identity

on:
  pull_request:
    paths:
      - "domains/identity/**"

permissions:
  contents: read

jobs:
  integration:
    uses: ./.github/workflows/integration.yaml
    with:
      domain: identity
      make_target: deploy-identity
    secrets: inherit
