name: integration / capabilities

on:
  pull_request:
    paths:
      - "domains/capabilities/**"

permissions:
  contents: read

jobs:
  integration:
    uses: ./.github/workflows/integration.yaml
    with:
      domain: capabilities
      make_target: integration-capabilities
    secrets: inherit
