name: integration / accounts

on:
  pull_request:
    paths:
      - "domains/accounts/**"

permissions:
  contents: read

jobs:
  integration:
    uses: ./.github/workflows/integration.yaml
    with:
      domain: accounts
    secrets:
      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
