name: integration / accounts

on:
  pull_request:
    paths:
      - "domains/accounts/**"

permissions:
  contents: read

jobs:
  integration:
    uses: ./.github/workflows/integration.yaml
    with:
      domain: accounts
      make_target: integration-accounts
    secrets: inherit
