name: integration / documents

on:
  pull_request:
    paths:
      - "domains/documents/**"

permissions:
  contents: read

jobs:
  integration:
    uses: ./.github/workflows/integration.yaml
    with:
      domain: documents
      make_target: deploy-documents
    secrets: inherit
