name: post-merge

on:
  push:
    branches: [master]
    paths:
      - "domains/*/components/*/**"
      - "!domains/*/components/*/infra/**"

concurrency:
  group: post-merge
  queue: max

permissions:
  contents: read

jobs:
  changes:
    name: find changed components
    runs-on: ubuntu-24.04
    outputs:
      components: ${{ steps.changes.outputs.all_changed_and_modified_files }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: changes
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: domains/*/components/*/**
          files_ignore: domains/*/components/*/infra/**
          dir_names: true
          dir_names_max_depth: 4
          matrix: true

  publish:
    name: publish ${{ matrix.component }}
    needs: changes
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(needs.changes.outputs.components) }}

    steps:
      - uses: actions/checkout@v6

      - id: image
        name: read image name
        run: echo "name=$(yq -r '.images[0].name' '${{ matrix.component }}/infra/overlays/prod-eu/kustomization.yaml')" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: build and publish image
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.component }}
          target: prod
          push: true
          tags: |
            ${{ steps.image.outputs.name }}:${{ github.sha }}
            ${{ steps.image.outputs.name }}:latest
