name: pre-merge

on:
  pull_request:

concurrency:
  group: pre-merge-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    name: check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 26

      - uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede # v4.0.1

      - id: changes
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            domains/**
            platform/**
          dir_names: true
          dir_names_max_depth: 2

      - name: check changed domains
        run: |
          for domain in ${{ steps.changes.outputs.all_changed_and_modified_files }}; do
            make -C "$domain" check
          done
