name: publish images

on:
  push:
    branches: [master]
    paths:
      - "domains/*/workloads/*/**"
      - "platform/runtime/*/**"

concurrency:
  group: publish-images
  queue: max

permissions:
  contents: read

jobs:
  domain-workloads:
    name: find changed domain workloads
    runs-on: ubuntu-24.04
    outputs:
      sources: ${{ steps.changes.outputs.all_changed_and_modified_files }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - id: changes
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: domains/*/workloads/*/**
          dir_names: true
          dir_names_max_depth: 4
          matrix: true

  runtimes:
    name: find changed shared runtimes
    runs-on: ubuntu-24.04
    outputs:
      sources: ${{ steps.changes.outputs.all_changed_and_modified_files }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - id: changes
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: platform/runtime/*/**
          dir_names: true
          dir_names_max_depth: 3
          matrix: true

  publish-domain-workload:
    name: publish ${{ matrix.source }}
    needs: domain-workloads
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        source: ${{ fromJSON(needs.domain-workloads.outputs.sources) }}

    uses: ./.github/workflows/publish-image.yaml
    with:
      source: ${{ matrix.source }}

  publish-runtime:
    name: publish ${{ matrix.source }}
    needs: runtimes
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        source: ${{ fromJSON(needs.runtimes.outputs.sources) }}

    uses: ./.github/workflows/publish-image.yaml
    with:
      source: ${{ matrix.source }}
