apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mdstaicu/auth
          envFrom:
            - secretRef:
                name: dotenv
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 30
          #   periodSeconds: 5
          #   failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            #
            # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
            #
            initialDelaySeconds: 5
            #
            # How often (in seconds) to perform the probe. Default to 10 seconds. The minimum value is 1
            #
            periodSeconds: 10
            #
            # Defaults to 3
            #
            failureThreshold: 3
