apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: trust-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  chartRef:
    kind: OCIRepository
    name: trust-manager-oci
    namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation: { retries: 3 }
  upgrade:
    crds: CreateReplace
    remediation: { retries: 3 }
  values:
    app:
      trust:
        namespace: cert-manager
