apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nats

resources:
  - ../../base

configMapGenerator:
  - name: nats-cm
    files:
      - nats-server.conf=nats-server.conf
