apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: nats
  serviceName: nats-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nats
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nats
              topologyKey: kubernetes.io/hostname
      containers:
        - name: nats

          volumeMounts:
            - name: nats-conf-cm
              mountPath: /etc/nats/
            - name: nats-storage
              mountPath: /data

      volumes:
        - name: nats-conf-cm
          configMap:
            name: nats-conf-cm

  volumeClaimTemplates:
    - metadata:
        name: nats-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
