apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenancy

resources:
  - tenancy-worker-depl.yaml
  - tenancy-worker-np.yaml
  - tenancy-worker-ns.yaml
  - tenancy-worker-sa.yaml
