apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base

  - namespace.yaml

  - auth-ing.yaml

configMapGenerator:
  - name: auth-env-cm
    literals:
      - MONGO_DB_URI=mongodb://auth-mongo-srv:27017
      - DOMAIN=tma.com
      - ORIGIN=https://tma.com

patches:
  - path: auth-depl.yaml
