apiVersion: batch/v1
kind: Job

metadata:
  name: migrate
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
          image: mdstaicu/spaces-migrate:latest

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: spaces-db
                  key: DATABASE_URL
