apiVersion: v1
kind: Secret
metadata:
    name: documents-migrate-db
stringData:
    FLYWAY_PASSWORD: ENC[AES256_GCM,data:BZTA,iv:95Jo0SuJHoQOa+FthnrZVfLPQiU2BgApSrQ3O2UCfS8=,tag:UQ7kPSav0orvXdnsJI6MlQ==,type:str]
    FLYWAY_URL: ENC[AES256_GCM,data:tvbC4KdyaDnLvZgIjMsMuxhyQN7MorFdWINzqyb9pIoiisQSNfyLpWgJzTdRlGx23Gz1xiPVAc5H7vICVA==,iv:H8gvwkMBgCtkVorJP/C4RU+0qtykT8EI1z2lHIz3fz0=,tag:h5f2kJ3397wWX9c++Gf5lQ==,type:str]
    FLYWAY_USER: ENC[AES256_GCM,data:Wj94IjPgm9Ku3hQY7aIGiR+b,iv:swZ8NMtnSTALTH7ae6cE0j0fO1hK8chy4SpokjRbedw=,tag:yP1mCpqEkyCeb7d/k+4cXg==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVDdLcVJnVW03bkdLcUcw
            elE4Z285cW4wOUtPZ3RObUtuZ1h0RDRHVEcwCkdpMThrM0tOc1RsRUNaRGFBZFcy
            QWwzTzlHNzgxZjliekRJcGQ1QWhoN0kKLS0tIFhNQzJFK3R3Nzd3WU40WjRJempK
            Q3VoTVNJaDA2ZWZaWnoycVFsOU1NWEUKkNF6RV90VrbIEs8z8RIB6u/7xdRW6Fxy
            nAYfdrO+EY5ig9+Y5d2t6gErUvuUOFcT5PM6RF0B15mPQeHFPvJF8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T18:25:19Z"
    mac: ENC[AES256_GCM,data:/wKOHg2avBVzBhKaYJC79GUd8QeiVLc2dv/XrQ/3YZ1UuBEgl8sG9zdtLhg7nPxecGNoJqhnb09SnqQQaeNTXtX8btp4XhGK/Nn1chW+r2kiC29b3v64VI5KV+hCiVPMOVk5x8TUtQE8U29cRLw2hb9xYK4FDF21puPjY1qgtpQ=,iv:QQeBdHZIxD6DLL0AKQit/opeRSnSOQbrRab4P6EqC48=,tag:hTsBBYc9D/DxUa1LKr4Y6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
