apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenancy

resources:
  - ../../base

patches:
  - path: tenancy-api-depl.yaml

secretGenerator:
  - name: tenancy-api-db
    literals:
      - DATABASE_URL=postgres://postgres@postgres-srv:5432/tenancy?sslmode=disable

generatorOptions:
  disableNameSuffixHash: true
