apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identities

resources:
  - ../../base

generators:
  - identities-ksops-generator.yaml

patches:
  - path: identities-api-depl.yaml

configMapGenerator:
  - name: identities-api-cm
    literals:
      - ORIGIN=https://tma.com
      - JWT_ALLOWED_AUDIENCES=spaces

secretGenerator:
  - name: identities-api-db
    literals:
      - DATABASE_URL=postgres://postgres@postgres-srv:5432/identities?sslmode=disable

generatorOptions:
  disableNameSuffixHash: true
