apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
data:
  otel-config.yaml: |
    extensions:
      health_check:

    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318

    processors:
      k8s_attributes:
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.deployment.name

      transform/traefik:
        error_mode: ignore
        metric_statements:
          - context: datapoint
            statements:
              - delete_key(attributes, "entrypoint")
              - delete_key(attributes, "protocol")
              - delete_key(attributes, "tls_cipher")
              - delete_key(attributes, "tls_version")

      batch:

    exporters:
      debug:
        verbosity: detailed

    service:
      extensions:
        - health_check

      pipelines:

        traces:
          receivers:
            - otlp
          processors:
            - k8s_attributes
            - batch
          exporters:
            - debug

        logs:
          receivers:
            - otlp
          processors:
            - k8s_attributes
            - batch
          exporters:
            - debug

        metrics:
          receivers:
            - otlp
          processors:
            - k8s_attributes
            - transform/traefik
            - batch
          exporters:
            - debug

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector
roleRef:
  kind: ClusterRole
  name: otel-collector
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      tolerations:
        - operator: Exists
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.147.0
          args:
            - --config=/conf/otel-config.yaml
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          ports:
            - containerPort: 4318
            - containerPort: 4317

          volumeMounts:
            - name: config
              mountPath: /conf

      volumes:
        - name: config
          configMap:
            name: otel-collector

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
