apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
data:
  otel-config.yaml: |
    extensions:
      health_check:

    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317

    processors:

      filter/traefik_red:
        metrics:
          include:
            match_type: strict
            metric_names:
              - http.server.request.duration

      transform/resources:
        error_mode: ignore
        trace_statements:
          - context: resource
            statements:
              - keep_keys(attributes, ["service.name"])
        metric_statements:
          - context: resource
            statements:
              - keep_keys(attributes, ["service.name"])

      transform/spans:
        error_mode: ignore
        trace_statements:
          - context: span
            statements:
              - keep_keys(attributes, ["http.method", "http.route", "http.status_code"])

      batch:

    exporters:
      debug:
        verbosity: detailed

    service:
      extensions:
        - health_check

      pipelines:

        traces:
          receivers:
            - otlp
          processors:
            - transform/resources
            - transform/spans
            - batch
          exporters:
            - debug

        metrics:
          receivers:
            - otlp
          processors:
            - filter/traefik_red
            - transform/resources
            - batch
          exporters:
            - debug

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      automountServiceAccountToken: false
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.147.0
          args:
            - --config=/conf/otel-config.yaml
          ports:
            - containerPort: 4318
            - containerPort: 4317
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: otel-collector

---
apiVersion: v1
kind: Service

metadata:
  name: otel-srv
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
