apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: api-internal
spec:
  entryPoints:
    - http

  routes:
    - kind: Rule
      match: >-
        PathPrefix(`/v1/plans/docs`) ||
        PathRegexp(`^/v1/accounts/[^/]+/plan$`)
      services:
        - name: api
          port: 3000
