apiVersion: v1
kind: Service

metadata:
  name: traefik-public-lb
spec:
  type: LoadBalancer
  selector:
    app: traefik-public
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
