apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`tma.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      priority: 40
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefik-public-secret-certs
    options:
      name: traefik-public-tls-options
