# apiVersion: traefik.io/v1alpha1

# kind: IngressRoute
# metadata:
#   name: client-route-https
# spec:
#   entryPoints:
#     - https
#   routes:
#     - match: PathPrefix(`/`)
#       kind: Rule
#       middlewares:
#         - name: tls
#       services:
#         - name: client-srv
#           port: 3000
# tls:
#   secretName: certs-secret
#   options:
#     name: tls-options
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`tma.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      priority: 40
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: certs-secret
    options:
      name: tls-options
