#
# https://tferdinand.net/en/traefik-2-tls-configuration/
#
#
# Local TLS auditing of the cluster https://testssl.sh/
# $ brew install testssl
#
#
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tls
spec:
  headers:
    #
    # Tells the browser that the page cannot be loaded in an iframe
    #
    frameDeny: true
    #
    # Allows to limit "Cross Site Scripting" attacks from the browser
    # https://owasp.org/www-community/attacks/xss/
    #
    browserXssFilter: true
    #
    # Tells the browser not to do mime type detection, the goal here is to limit "Drive by download" attacks
    # https://www.kaspersky.com/resource-center/definitions/drive-by-download
    #
    contentTypeNosniff: true
    #
    # HSTS (HTTP Strict Transport Security) headers
    #
    # These headers will tell the browser to only communicate securely with the server
    #
    # The major difference with a simple 301 Redirect to HTTPS is that
    # the browser will not send any information to the server, such as user cookies
    #
    # In case of a man in the middle attack, a site registered in HSTS with preloading will be protected
    #
    # To fully use HSTS, it is important that this middleware is present in
    # HTTP and HTTPS ingress route definition objects
    #
    # stsSeconds tells the browser how long this domain should be accessed exclusively in HTTPS
    # To be able to use HSTS Preloading, this parameter must be at least 31536000 seconds (one year)
    stsSeconds: 31536000
    #
    # stsPreload allows you to indicate that this site supports HSTS preloading
    # This allows you to secure the connection from the first attempt instead of the second
    #
    # The preloading requires to register its site beforehand on https://hstspreload.org/
    # which will allow that it is directly present in the navigator
    stsPreload: true
    #
    # stsIncludeSubdomains allows to indicate that we want all the subdomains attached to the requested domain to be also in HSTS
    stsIncludeSubdomains: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: tls-options
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 # TLS 1.2
    - TLS_AES_256_GCM_SHA384 # TLS 1.3
    - TLS_CHACHA20_POLY1305_SHA256 # TLS 1.3
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: true
