apiVersion: v1
kind: Secret
metadata:
    name: documents-api-db
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:godR8iZHQ75NskiErZwXBDRm1H7UqmZdlLh1VnZjUBqCaJgSO/uwFxzdPsa0QlfRMkdlmmk6/iQWGIBf9Jdk48fln8Ggnuc6,iv:fj1syLKO+JhiriFa8l+tI+XjTwLSMS7s4ZLwLyyFAw0=,tag:pnJOzhlzXqwtrWNepGN44w==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WWxzRlVDUUNJeVhyUTJ1
            SEJoT25Ic29XQjJhM1lSaFBlMnBCMVRZUlI4CmZETFRFYjRvVXFDQndHVG5hNUVP
            NldBVXhwdUxQUGlrdmozcjNhMnhXRTgKLS0tIDJUcjVNZVkyTkprWmEwYnVNSm5G
            YjhJM0tCT1VnM0lpQSsyZ1lOSUFDcG8KSvvolRT0H48yEY46zIqrASXIZzUhCxgN
            ZOIHZVAmOTr9mbbbGKjDiVLDdH9r2S2M3J8rGKC4W2Nxk0atDTlA5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T18:25:19Z"
    mac: ENC[AES256_GCM,data:C94hdlPRoKvZXJCZgrDix1zr3p7HW4CIEeppRhZHq8ijaNYEjk+ErxVI4AYgSdbkfXIfMVJCLfhPLV8ORzAty3L9PubC7KzewqdqIlI63P8Ci27AoteSwoHTeMz+OBSxE320uykCeDMwqH6sJV7+VwHbzg67GJ+NtM83qCzyrhY=,iv:NjwofKuOhIcKQVKNizWD1hY+alW/ukH3I/faEPj2a3E=,tag:QOebLBkPd/hQ0cTNy5kyNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
