apiVersion: v1
kind: Secret
metadata:
  name: linkerd-identity-issuer
type: Opaque
data:
  crt.pem: ENC[AES256_GCM,data:Ljrjt9y178rTmsSJ6jliCYoN8Qph1oo0+o8TWifU7kMGgWQrekP8Uzz9i7z+HO9fcbjgB+kfzHwEbA0viUmArJ0jWlA5Kj+t+NWQSKjBRsZ0HtspUcgs6D+rZli1zptisBJjlhdEIPSSOP7nMwn/Xq5f8gvbSQaQTbL10uY7bs+X7NsPJ6aDWWUKbpZ94vYhbXETjsh964+9TLHarKp3z3niKxIsW2rJ1jiQ9+mwNu64NfixmVx1Leqry9ArjLB6tyNlM/z7lC4xlS+XMvgcYFynQAxYf1xKhwId60j97LCFqTa//4Pp5KB8BcPQ//iQoaMhqVaqv06rrz01tkLRufiUJXH8eAdZdTJvMhU3SM4YRx8DhaqKb5y1fVujwlEus2CoUTQelCww6VCs6qDoH7USRyG9Ft64S5s27GX3daK6sdmfnYZPAetAJRrF0d78FVZ08+519tMmlBt14ZlguwXRhxWj+Dvcis4EZr8sEAj3CcBD9+dY5ll/e5Ew8GVm+zgvCHsgocCpW7qzhn40a+UthreeattWOdAK0/TRDeeUob3ZK5X15iunkl2RkvVqNIHh12VHphIFiomBRgk1ZlTtziUL3zPu6urJOnknEXyPvQv9N8nPj8AkITINlvswpKipqd2bssFVKF4Zvqy2fXtJzin7jh2zW5fMU2la5852R+1lshTWwsZart5CBJfyE5kiAM+Q0QfwYJwhsPjSRTwCZ3U1oy/m10KnGHW3pt+9XUEtzc3kxRO66oRuWnm5dnDJHVx9Hloq42E6dtAT8SgsxRrq/j4R+y4GxMwS1JMgnvy4pNYSEgao3iTlrLS4JiEndnGHZVQl0aL5IzGae5cxAcniN0wXJkQcRaUUkJIYn870lkJkr06cncelmNDUZRXTihKU/adWsBrLwmKiTRphe5MmOYtOFTBMejto647ukeTylhSgus3NqaS4hqHOaC5R+g3cHkdDe3xxFi4OmlJdlZIQS09rKKz2CZctH72HYrpzTY6/zu+/LkwXn0NZwVLVNUzN287eWUjtqa61vfUzMAveISV6gAL6B3npBkQmEUsqBG5wyywKxjeyktF/GZYdHYFhlqkV2m5pjb8CXiQ70KSA7zJX8muiG8UgqWs/0tWOeSC1L0QOnfPjZ5aPYo7P/9Q4pOw=,iv:1nbFUj7y7XFWAQh/eorvREAY03vQRsrUP0aKVeJJT4I=,tag:YFjc95mp/+g1OWJOfRqoFA==,type:str]
  key.pem: ENC[AES256_GCM,data:HOykIiNQPjoHuJZ7EvFdD7qIArnAGPVj5AHxp0RLsmEEgC91ZNrDDU45P9s+ImRlPRvuI7OtbSTUxe9n5+NYvd5AhLu6orSqewXmmLzf7TQe07PsP+1On+fvj5L2ZubH6+5fiVrltNPzTRhyZtPekuf9XpP/pOSFIcg9jI7aXtGRbbVGQ0Yms0HnmaKvvxSeQyX4RHhYFWkvWK5ZflBEYHal04MRiZxZZL6FC8wsJx2M0Qm8d2PqUKyVEQsTrAUWb3SWugnlv2sSd6jtb6YmjSYfwHwsVj8jSGwNjeSQjNxhTNHa4gLu+Qu1mm/9aNBaKI7P434sRGSX/kU8QO2hzGytWPEd1FpStRw4Wluvv8AQwyOUtq1TpplNUnX2JUzrox1SU2+qS45FX7sL2j2gmA==,iv:90Y6Y/PeSb/zUKmtETu01uKGnPjzhpnx4kbJF7u0wlQ=,tag:7vx5LEIXXCGjSHcpoAXLHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc1RXRU13WC9lTVRhcnB1
        cDUrNm1iSGNLa2VxUWczMjk2MkhkWmRJOHpvCnV6YTMrdndiMmNkWDNiR1V4RHoy
        VVNwcWtyMTI1YWNkSFo4aUVaMFVJV2MKLS0tIGRqRzNnWUc1VzdoMys5MjFGSU1Z
        MWF6cHVVdlRMdFhoWnVidi9wd3hDV3cK4ok4Mn0WET62yzrkj192ZLFJj4Srj7r1
        tlb0VbzHU5y3WP90UZ4VnlZMosBkrZwbWhF/J61nZMYJF5fyyjfXiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T18:28:40Z"
  mac: ENC[AES256_GCM,data:cPTF1uB4bf7ZoGp4nM3R0gx1sE09azScEC2oHM+cX7qimTB5vc8xvPTrjes4MmmuR8oM4XLo3OzI+s4Nsh5VYEEaarDaNOTiSc9ciS19cvAQqmQfm2w9JG3W0tEvRAvMPR+x67vfrLF5ubm98KYULDKRMgo+P5mrImTSuPDfjww=,iv:Nlw3YZrL5TvskL2GxKOrPqspIx5q5TrNvOOGL6VZ9J0=,tag:r8OjJChO55Nyma7yFm84Mg==,type:str]
  version: 3.13.1
