apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-webhook-trust-roots
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBwDCCAWegAwIBAgIUalNZw/rNKDku5s6MJES7thegNREwCgYIKoZIzj0EAwIw
    NjE0MDIGA1UEAwwrbGlua2VyZC13ZWJob29rcy5saXZlLmxpbmtlcmQuY2x1c3Rl
    ci5sb2NhbDAeFw0yNjA0MTkxNzAyMDBaFw0zNjA0MTYxNzAyMDBaMDYxNDAyBgNV
    BAMMK2xpbmtlcmQtd2ViaG9va3MubGl2ZS5saW5rZXJkLmNsdXN0ZXIubG9jYWww
    WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQzg2v+2hh82y+gX9a+NmVhqqSj9btj
    lP47AP8kgn3pZd224P93fVQ7X2b3+JLfyUi9OGZOhn3ypzYwV6q7kPUso1MwUTAd
    BgNVHQ4EFgQUE6RNjiUoGjV2Y+hyzCgVxu8oM3IwHwYDVR0jBBgwFoAUE6RNjiUo
    GjV2Y+hyzCgVxu8oM3IwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBE
    AiA/zD0tqZJZ8dkjL6cVml8InAGkwu0x0rK7u8v4ntPCzQIgawq81BG0ISN4dcpk
    RxjxHd8QyNX37oPh3PbXNtwBgi4=
    -----END CERTIFICATE-----
