apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik-deployment.yaml
  - traefik-internal-service.yaml
  - traefik-public-service.yaml
  - traefik-clusterrole.yaml
  - traefik-clusterrolebinding.yaml
  - traefik-serviceaccount.yaml
