apiVersion: v1
kind: Service

metadata:
  name: traefik-lb
  namespace: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
