apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: signoz
spec:
  replicas: 1
  serviceName: signoz
  selector:
    matchLabels:
      app: signoz
  template:
    metadata:
      labels:
        app: signoz
    spec:
      containers:
        - name: signoz
          image: signoz/signoz:v0.114.1
          ports:
            - containerPort: 8080
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: CLICKHOUSE_PORT
              value: "9000"
            - name: SIGNOZ_TELEMETRYSTORE_PROVIDER
              value: clickhouse
            - name: SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN
              value: tcp://clickhouse:9000
