apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenancy

resources:
  - tenancy-api-ingress.yaml
  - tenancy-np.yaml
  - tenancy-api-depl.yaml
  - tenancy-api-sa.yaml
  - tenancy-api-srv.yaml
  - tenancy-ns.yaml
