apiVersion: batch/v1
kind: Job

metadata:
  name: migrate
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
          image: mdstaicu/auth-migrate

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-migrate-db
                  key: DATABASE_URL
