apiVersion: apps/v1
kind: Deployment

metadata:
  name: identity-api-depl
spec:
  selector:
    matchLabels:
      app: identity-api
  replicas: 3
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      terminationGracePeriodSeconds: 15
      automountServiceAccountToken: false

      containers:
        - name: identity-api
          image: ghcr.io/mstaicu/identity-api
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: identity-api-cm
                  key: ORIGIN

            - name: JWT_PRIVATE_KEY_PATH
              value: /app/keys/jwt-private.pem
            - name: JWT_PUBLIC_KEY_PATH
              value: /app/keys/jwt-public.pem

          volumeMounts:
            - name: identity-api-jwt
              mountPath: /app/keys
              readOnly: true

          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2

      volumes:
        - name: identity-api-jwt
          secret:
            secretName: identity-api-jwt
