apiVersion: v1
kind: Secret
metadata:
    name: capabilities-migrate-db
stringData:
    FLYWAY_URL: ENC[AES256_GCM,data:Di2eYP8uGFXxcgDoFKzei/oHtohdVz6calRLZMfBLGxvTjrp0aW9WNSSKUWKGF0wafC3v08tUBmhmSpDmyLv7w==,iv:cH3xs2FZcFcuUr6ai90s1urtWV3yZA+5oViTnj8G1D8=,tag:AXUIMxPvY50oHcjEduLoFQ==,type:str]
    FLYWAY_USER: ENC[AES256_GCM,data:KcnyW6Rb2A4ABW5bhdQ25F9jRJOA,iv:32LjNjhF3t8VlMw8aBX33VLArw9tmEE/YJAOxng/6Sc=,tag:nRPycsGp4TfmzE+HBcqQxg==,type:str]
    FLYWAY_PASSWORD: ENC[AES256_GCM,data:Gixn,iv:34/Lpj/WfNrfKi6UjvyPlRD0OzRp1ZYEbBriJkhzrD8=,tag:J6EWNpgljM1TaGFiuwaYKg==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIanNFNGl4NlRxSXI1RGEv
            cVM5NEMxSUVzZFNpU1pRaDVFd25NREJOcHlnCjVhdmN6KzQ4eVA5ZXFoVHBJKzFI
            RVdpK2t6TlNud0hnMU9JMDBxTGtESHcKLS0tIEphWUNua0ZnWlFNVmI3YmwwVnVo
            QzFiVTd4VDFhVjVZb3ArMGlsUnM0NGsKMUxcOvVcMvgt5nPpcHfMebe3iHNYBgwa
            AHUIE2UPl1jxLOtUiqfBvhAiSIHaQUQMw3jBk0HOp84naM0LBzaauQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T16:25:15Z"
    mac: ENC[AES256_GCM,data:NAAW+xvm2a6clQ1k6EPjOP/XtVfj7HIYN8D+qytoFZc1fOHh7y1ugDa/AjdoozhdBnwaRKb+5frPbirT6Pr+800NAo4/v/6CVLv9rF7bULsR70ZR20WZiKtKUBqRsSSCTWxfre5ryk4ZT1Agoa98iA7oNp2ruOUDwC9M1sVKjEs=,iv:0jqfSyOom6R5QdiTjC2THUS3DSNt+O8dTQh66w2a4ks=,tag:pAVfZXEQ+hHkO/gOxwEOow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
