apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capabilities

resources:
  - namespace.yaml
  - ../../base
  - capabilities-migrate-db.yaml

patches:
  - path: capabilities-migrate-job.yaml

images:
  - name: mdstaicu/capabilities-migrate
    newTag: latest
