apiVersion: apps/v1
kind: Deployment

metadata:
  name: nack
  labels:
    app: nack
spec:
  selector:
    matchLabels:
      app: nack

  replicas: 1

  template:
    metadata:
      labels:
        app: nack
    spec:
      serviceAccountName: jetstream-controller
      containers:
        - name: jsc
          image: natsio/jetstream-controller:0.22.2
          workingDir: /nack
          command:
            - /jetstream-controller
          args:
            - -s=nats://nats-depl-0.nats-headless.$(POD_NAMESPACE).svc.cluster.local:4222
            - --control-loop
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: runtime
              mountPath: /nack
      volumes:
        - name: runtime
          emptyDir: {}
