apiVersion: v1
kind: Secret
metadata:
    name: documents-api-db
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:e5djP3fU1wNisuWCUw5Hd+9p0xuUK9kHQv8kTxWo9xizOZ/g2UakHEVJxoDN6+biEazQbkCR1NtmWa0ymJud9lTrGuA01n9T,iv:TtFKUSOl4ljllkT2qK41ugldA5GRzHZVAR6wur4954o=,tag:36fvzVSMw02WYpPgd0nduQ==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdXhHV3hRaWZQdHFlTndj
            TmoxSzVtWU9UN3hzaGZyZ3JrbmJDdzVCV0Z3Ckd5YyswRHJOd3lHa1BTekdUNjFo
            T0pybURPVHdSemUwYnhCNWN1R1ZqRGcKLS0tIDhoT2lyK09oNXhVZk5jQ0dPU3U3
            RERMTFkvNWY3R01hREZhK0NjTGV4OXcKchhGoBChPg2Ie1ZCSaWJD2DwapY8UsjK
            RpDRmZ6s+7jBak5XBxfMFwcupupqcGkvLWEAHs2g+k7QXJtz2pgoIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T18:25:19Z"
    mac: ENC[AES256_GCM,data:kxHLU6ZivUzLOdJn9RX80WLg049jr0Ni5jIEajFMQ1eT8vro9gpAXcXQpCivKF3MFdugsaBc6uj2YGWlwRdbvjekUsPnXMPIS3d11qWzguZSkV+mlOrNi3WJiy+ziNbDjfnlyQlaXTSnLFAB835Z0HnKjXruvAYT9LNQqmJMNxM=,iv:ghAHQzfZ7sdM3P5V9K6Q5FNrRXMPeKaZmyBolIh+3qg=,tag:8xZXn4K+DXvHd5mmYsGNqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
