apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - ../../base
  - auth-api-ingress.yaml
  - auth-api-jwt.yaml
  - auth-api-middleware.yaml
  - auth-ns.yaml

configMapGenerator:
  - name: auth-api-cm
    literals:
      - MONGO_DB_URI=mongodb://auth-mongo-srv:27017
      - ORIGIN=https://tma.com

generators:
  - auth-ksops-gen.yaml

images:
  - name: docker.io/mdstaicu/auth-api
    # Translation: This field is managed by this ImagePolicy:
    # <namespace>:<imagepolicy-name>
    # meaning: flux-system:auth-api-latest
    newTag: latest # {"$imagepolicy": "flux-system:auth-api-latest"}
