apiVersion: v1
kind: Namespace

metadata:
  name: accounts
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: accounts-postgres
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/accounts/deploy/postgres/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: accounts-migrations
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/accounts/deploy/migrations/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: accounts-postgres
  force: true
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: accounts-api
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/accounts/deploy/api/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-crds
    - name: accounts-migrations
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: accounts-outbox-relay
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/accounts/deploy/outbox-relay/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: accounts-migrations
    - name: event-bus
  wait: true
  timeout: 5m
