apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: accounts-api
spec:
  interval: 10m
  path: ./k8s/domains/accounts/components/api/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress
    - name: observability
    - name: identity-api
    - name: accounts-migrations
  wait: true
  timeout: 5m
