apiVersion: v1
kind: Namespace

metadata:
  name: auth
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: auth-api
  namespace: flux-system
spec:
  image: ghcr.io/mstaicu/auth-api
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: auth-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auth-api
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: auth-ui
  namespace: flux-system
spec:
  image: ghcr.io/mstaicu/auth-ui
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: auth-ui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auth-ui
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: auth-migrations
  namespace: flux-system
spec:
  image: ghcr.io/mstaicu/auth-migrations
  interval: 5m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: auth-migrations
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auth-migrations
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: auth-postgres
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/auth/workloads/postgres/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: auth-migrations
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/auth/workloads/migrations/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: auth-postgres
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: auth-api
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/auth/workloads/api/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: auth-migrations
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: auth-retention
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/auth/workloads/retention/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: auth-migrations
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: auth-ui
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/domains/auth/workloads/ui/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
