apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: capabilities-migrate
spec:
  interval: 10m
  path: ./k8s/domains/capabilities/infra/migrate/overlays/live
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: capabilities-postgres
  force: true
  wait: true
  timeout: 5m
