apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: entitlements-accounts-projector
spec:
  interval: 10m
  path: ./k8s/domains/entitlements/components/accounts-projector/infra/overlays/prod-eu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: event-bus
    - name: entitlements-migrate
  wait: true
  timeout: 5m
