apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: identities-ui
spec:
  interval: 10m
  path: ./k8s/domains/identities/infra/ui/overlays/live
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress
    - name: identities-api
  wait: true
  timeout: 5m
