apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: identities-db
spec:
  interval: 10m
  path: ./k8s/domains/identities/infra/db/overlays/live
  wait: true
  timeout: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
