apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - identities-db.yaml
  - identities-migrate.yaml
  - identities-api.yaml
  - accounts-db.yaml
  - accounts-migrate.yaml
  - accounts-api.yaml
  - accounts-worker.yaml
