apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - identity-postgres.yaml
  - identity-migrations.yaml
  - identity-api.yaml
  - identity-cleanup.yaml
  - identity-ui.yaml
  - accounts-postgres.yaml
  - accounts-migrations.yaml
  - accounts-api.yaml
  - accounts-outbox-publisher.yaml
  - entitlements-postgres.yaml
  - entitlements-migrations.yaml
  - entitlements-api.yaml
  - entitlements-outbox-publisher.yaml
  - entitlements-accounts-projector.yaml
