apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - identity-postgres.yaml
  - identity-migrate.yaml
  - identity-api.yaml
  - identity-ui.yaml
  - tenancy-postgres.yaml
  - tenancy-migrate.yaml
  - tenancy-api.yaml
  - tenancy-worker.yaml
  - features-postgres.yaml
  - features-migrate.yaml
  - features-api.yaml
  - features-worker.yaml
  - documents-postgres.yaml
  - documents-migrate.yaml
  - documents-api.yaml
  - documents-worker.yaml
