apiVersion: jetstream.nats.io/v1beta2
kind: Account

metadata:
  name: nack
spec:
  servers:
    - nats://nats-depl-0.nats-headless.nats.svc.cluster.local:4222
  user:
    secret:
      name: nack-nats-creds
    user: user
    password: password
