apiVersion: v1
kind: Secret
metadata:
    name: capabilities-api-db
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ksbkKWXpSJYmkXqR8Byo4O6765FhhS0V42VRGgxSa5YD6mNxq7IbRJng8JPN7QSXn8OMzYuXZIcDNf+YKdWIgIkjkW2AgRP4ODflqkKC,iv:qDbSr3dlqupS+ZofrnYD2ENN+0qAqM/1oQizuborqL4=,tag:cnkoH235C3mECJOeYVgfFg==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTW8wTWwxSmdSd05GTG9u
            RFUwVWgwOEJsRXdQNGVCektKc1lYSG92MlNZClNzdFFxUEVaV0hVTTZWckhzNW83
            UXpYRUgwdEw1amVEUnk1N1JiU0FkSXcKLS0tIGhodVNTRVRPRE0zdDZadHRkVWpI
            N3FrZkRBVG5xbkJ5MXV6eXNKd3h6c1EKT/4GU2HlJBOek5Np7PZ/tvSU0aPDVi3Q
            k0k1F2S1QbxZMTRAGR6Oex9UX2SAcAsMKQAGF09TH/zFGOqLFVeb4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T16:25:15Z"
    mac: ENC[AES256_GCM,data:UZDbLM447LyffejJ5/UoI2CQaossonKk1rpUd2joRR4D7WH2+9XBxZWqyelDcc+2cJqQo1JqfAXHBXV0GwBP+9JRBN7JlutVbIsYmZ/pgpLrXlnhaMrDHVTmrLdtmHmqt7pkFxAYHcFNmdXoBG3TVd4pOBwXXjkFqC5ZVgJGXLI=,iv:0RDTZKZNuGGuRriFeWnsJijm5FmNVA2atEPIIYMW1cU=,tag:GzypWHYNtVfaDstq9AHs1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
