apiVersion: viaduct.ai/v1
kind: KSOPS

metadata:
  name: capabilities-api-ksops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - capabilities-api-db.yaml
