apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capabilities

resources:
  - namespace.yaml
  - ../../base

generators:
  - capabilities-api-ksops-generator.yaml

patches:
  - path: capabilities-api-depl.yaml
