apiVersion: skaffold/v4beta14
kind: Config

metadata:
  name: accounts

requires:
  - path: workloads/postgres/skaffold.yaml
    configs: [accounts-postgres]
  - path: workloads/migrations/skaffold.yaml
    configs: [accounts-migrations]
  - path: workloads/api/skaffold.yaml
    configs: [accounts-api]
  - path: workloads/outbox-relay/skaffold.yaml
    configs: [accounts-outbox-relay]
