apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: accounts-postgres

manifests:
  kustomize:
    paths:
      - infra/postgres/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: accounts-migrate

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/accounts-migrate
      context: components/migrate
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - components/migrate/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: accounts-api

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/accounts-api
      context: components/api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/api/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: accounts-worker

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/accounts-worker
      context: components/worker
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/worker/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}
