apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - ../../base
  - traefik-dashboard-ingressroute.yaml
  - traefik-tlsstore.yaml

patches:
  - path: traefik-deployment.yaml
  - path: traefik-public-service.yaml
