apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: identity-api-public-jwks
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`api.tma.com`) && Path(`/.well-known/jwks.json`)
      services:
        - name: identity-api
          port: 3000
  tls: {}
