apiVersion: apps/v1
kind: Deployment

metadata:
  name: documents-ui-depl
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: documents-ui
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: NODE_OPTIONS
              value: "--experimental-loader=@opentelemetry/instrumentation/hook.mjs --import ./dist/otel.js"
            - name: OTEL_SERVICE_NAME
              value: documents-ui
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-srv.otel.svc.cluster.local:4318
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
