apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: features-api
spec:
  image: docker.io/mdstaicu/features-api
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: features-migrate
spec:
  image: docker.io/mdstaicu/features-migrate
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: features-worker
spec:
  image: docker.io/mdstaicu/features-worker
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: features-api-latest
spec:
  imageRepositoryRef:
    name: features-api
  filterTags:
    pattern: "^[a-f0-9]{7}$"
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: features-migrate-latest
spec:
  imageRepositoryRef:
    name: features-migrate
  filterTags:
    pattern: "^[a-f0-9]{7}$"
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: features-worker-latest
spec:
  imageRepositoryRef:
    name: features-worker
  filterTags:
    pattern: "^[a-f0-9]{7}$"
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation

metadata:
  name: features
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@tma.com
        name: FluxCD Bot
    push:
      branch: master
  update:
    path: ./k8s/domains/features/infra
    strategy: Setters
