apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: identities-api
spec:
  image: docker.io/mdstaicu/identities-api
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: identities-migrate
spec:
  image: docker.io/mdstaicu/identities-migrate
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: identities-api-latest
spec:
  imageRepositoryRef:
    name: identities-api
  filterTags:
    pattern: "^[a-f0-9]{7}$" # Only short SHAs, 7 hex chars
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: identities-migrate-latest
spec:
  imageRepositoryRef:
    name: identities-migrate
  filterTags:
    pattern: "^[a-f0-9]{7}$" # Only short SHAs, 7 hex chars
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation

metadata:
  name: identities
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@tma.com
        name: FluxCD Bot
    push:
      branch: master
  update:
    path: ./k8s/domains/identities/infra
    strategy: Setters
