apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: tenancy-api
spec:
  image: docker.io/mdstaicu/tenancy-api
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: tenancy-migrate
spec:
  image: docker.io/mdstaicu/tenancy-migrate
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: tenancy-worker
spec:
  image: docker.io/mdstaicu/tenancy-worker
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: tenancy-api-latest
spec:
  imageRepositoryRef:
    name: tenancy-api
  filterTags:
    pattern: "^[a-f0-9]{7}$"
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: tenancy-migrate-latest
spec:
  imageRepositoryRef:
    name: tenancy-migrate
  filterTags:
    pattern: "^[a-f0-9]{7}$"
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: tenancy-worker-latest
spec:
  imageRepositoryRef:
    name: tenancy-worker
  filterTags:
    pattern: "^[a-f0-9]{7}$"
  policy:
    latest: {}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation

metadata:
  name: tenancy
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@tma.com
        name: FluxCD Bot
    push:
      branch: master
  update:
    path: ./k8s/domains/tenancy/infra
    strategy: Setters
