apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-documents-components-to-postgres
spec:
  podSelector:
    matchLabels:
      app: documents-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: documents-api
        - podSelector:
            matchLabels:
              app: documents-migrations
        - podSelector:
            matchLabels:
              app: accounts-projector
        - podSelector:
            matchLabels:
              app: entitlements-projector
      ports:
        - protocol: TCP
          port: 5432
