apiVersion: v1
kind: Secret
metadata:
  name: api-jwt
data:
  jwt-private.pem: ENC[AES256_GCM,data:JNFr717TDrGzFsreYb2JvIvEITZq480dbgnRQsrGYoMfTcKknNlNo8D4gitc+06zwKKJ9A0eiz1lL+hNw2tvJ/PLOJFjsd/iNxVw/zbJ/D0axxEXfGVif78r/7WHDA2+YQuY/+fSAMtsugrYvgJ/HPdqB3XplL/3WBI7V7obEedTTsqTB1g3FEmC12qBC4hGv6pmGyKGmGxeoajL5Zdbh4sZGu3JwQAiNkg9KXWNtMK6BvsI1EZTcdGAjKej3V45N+0urQmagCwFGQ+UPz9ue2/kaAyJeDRYtZIbkaDWeSMM/c7D3P55OVBAk8hrsfyxZO1LhVXsrj5v/ZcG5ou+s9FwMsIm5WX6RUu4OsGlRgV5awpNgRg2FPtU4EWlMbm7+mJ05A/mr8A80uboDEae8878BVbClpv9vO1i7yUQ8RxTtIqD,iv:oEyX5QNe9RDL6D9eQfUDLD07r2GFaiih5Z/ZRr4O6CQ=,tag:tX8uO9l0fYsOcs6xySANBw==,type:str]
  jwt-public.pem: ENC[AES256_GCM,data:unxJywExWGNn8bEoSpZ0/RkLrHxH3OUQKDQ9XVBdJKpqcGsJEwFj3U1d0nuzvbNA4UwZN7tYUdWB5nHGhi8IHGVGtmSEJG1UxdPblGyQxXdPrDJ7qWn4s9SZADndceeq+b3coUqOa0piJxWrNqq51QPjERjwOn+iGJ3BdECzWhbJGxooCdCVXkTXGQA7KKDYd3zrFyvhJG92b1lvkZn5jmVS69JWfQ4cmFJ6PRltuWQewJdLcWrZPtipHWYZ753lb1AyIPs1qVMVVmmBrxARW/PdO+pWpYLX5ZuSLgfMuEvuqTxKVsYe+Gh8fmmo6DaC,iv:4o3FWNjJ/EzymcVSmKvjlsbDlaGbbQzwwPAUVOaxsUA=,tag:dJSHSW3WkZLI8SbHjob+lA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RlBLMDNvQUw3THYrSmsw
        L3NsZXRrbVIwRG5XMWM1QW83cWNleTNLWjNBCmdtQTFXV0FHUkNzcmFCUGtGeXhx
        b2dualJORi8rVzNJblZuckh2a1V6dFkKLS0tIEVGRmpsdkhWMXRjZTBzc09WRXJr
        WHBuT3JrKzJ2WWFUa0thcWsvTzQ0SUUKlQwv8Em8N315hkaNCCpecpU1s3gnrIPw
        W7t8Fu5NEg2GZ42V2yZcmgLmr6SrndSJujuC7jsdDdZgpmMAV468TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j2qashtf39jk0dxytcx66e5v24ze2vmmj3ah84aewj57mumy2pgqhreu86
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T14:04:53Z"
  mac: ENC[AES256_GCM,data:SwiT7049DLXoTO0NYUZ0V2MUGuS9l6APtoz61zj26SzXzYFk5JQYV9LHR+1VbVmXa612RwCt5pU58ipN6VKye/KY/GE4WFCQVkg/23UOMseAGlxJEgUViq8U5sf12oyNbjeBC5L9Ffdh5aIgUxdXodhZE4sKSwx8aaEOPEMgCps=,iv:qtqGsoQS0xDQ2C47XXFI0jVFRQDrl482w3HNDAT4d/A=,tag:aWJOnf3/YOTg3gzYHorXWA==,type:str]
  version: 3.12.2
