apiVersion: v1
kind: Secret
metadata:
    name: features-worker-db
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Wod1hwps/G73y972ciimmXSOwEjAeZzUkYg0FEG45oorPvvFXbOrAjvZkuiO4/ytifGAb0hqfG6BTFbmlqLw0Hj0GKQ73gpVLA==,iv:5104ZLTWa4vM2hztP2XNqik2+H5aJPKAtKAJF79+EHY=,tag:gdt7VdCNV++lwttcTUuggw==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVjlYQ0NKZkV1aktDck1P
            RnJKMDhWbldnbGtZOFdVazNoZU1MTFpVQndZCnZha2pKTzRGaENOMWUzcGRwZldn
            YjdVV3FZU3YvNDFzQVB3c2ljdUtvbkEKLS0tIC9yZFZhRTNqTWsxTGtnZzBqWFIz
            NmhrY2JDa1FYNFVJWlU2MVZVd1pDNmsKV7NGbh+ZbiJxaR8n8lm8IUHofognO0V9
            xw38hQeWOXRQeWvhxtx/EXutncW6m/xtuvt0c4gP0h6B3FZR3UnYwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T11:29:25Z"
    mac: ENC[AES256_GCM,data:I76gJhox7sDWAI1PxGJ98wGf62udTHIWadxi9b5p0gcxWZblF/Dx9Wt9c8xPDL67wxz/FWegPJS2gq/pO+ayj2QKrXQ7kpjJPKkxMrVOGFpKYgBVkjvmdW5ig66a3HxcXPlQ01oV0E+yvzdHkt+SLb4/HXw0fufgR3zEwwxQlDA=,iv:ZmtXZZsLyoi8zFGK+chFGeDQsDynfMShRqV8rHc5vXY=,tag:R1SUedmlkSQNaMzMttffeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
