apiVersion: v1
kind: Secret
metadata:
    name: accounts-migrate-db
stringData:
    FLYWAY_URL: ENC[AES256_GCM,data:ZETm4o1B7124Q28G5lGmDlIaQreZmvPv9Uk9bexg+w/22saG97S/n8kJGQy2gxy7jhU5mtrCaolBPN51,iv:/EvcoOrnTatRP3hj1pjYPH7SL1mz4Z7GX9XeV2+LsaQ=,tag:YPP1pV6Ic6vhKi/DSgEvrw==,type:str]
    FLYWAY_USER: ENC[AES256_GCM,data:y/wov15m3+zTca+0rlHbHJM=,iv:899+q1r/0dFQ3LWGoy/fzd1A3xFqrWvP66EOHF5jpSw=,tag:UHBqTjIlx1qNBnfHa4oERQ==,type:str]
    FLYWAY_PASSWORD: ENC[AES256_GCM,data:+Thi,iv:peCSBXMaKGlTXkhikvCqI/Q+beKAEfm0/7fSSV/LPyQ=,tag:zPunogiRtvmNK0H8xE/1mA==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFT3pUQzNUOUQzbjRMOTVo
            eHM4OGg2R0V5emVPeXRPdmlnQW4wU2dSK3dRCjhwcVcwL3htQ2tUbmhTZ0FuYzQx
            M0lrbHVMMWx1aSszNjFERFNlZkhmK0EKLS0tIGpCcmI0VjB1MzV4YitWWTZkcEhx
            NjM3T05BcjdyK1VqYngzRDJrdHBNcWcK3YrQnN2KqrTgWrgnx/zFpDV0DI+ofyxk
            kr5meJn6PmVBacK0aso16ZuG2Tma4/0T8FyNirM+YU82nRbS8MxQoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T08:35:59Z"
    mac: ENC[AES256_GCM,data:QR2J8QOvvQRVTnqgTwwDmLXMhdZsHr79yUPUSgXUo6WZFZu5thi74YP6xnpkM3iii5LSRaSSi/kWJgDtoORbGesRyQ137WESnX+NPfLsgPHyHriEXEsB9fSv8oRtI/OAFl+LlREwL2CJV7MGN/fFtBM2/5+VDCC7SpWQf+w4Pns=,iv:zJGIlmVqxSRtYkeWhfXbK20StCE4VEuYXNUKwP9Lztg=,tag:S6+ALr5hQKZgMxLqRcS+Uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
