apiVersion: v1
kind: Secret
metadata:
    name: accounts-migrate-db
stringData:
    FLYWAY_URL: ENC[AES256_GCM,data:DrBbTzXpwir8MJfBREbf9H0CMnNR4vrv0dPf0Qmn1rHwfvulcoME3gIqw/PmcnXMAdxUQqsH3QS8K/G+,iv:n4CktFHZ2uGbUjAU+EU/z2azR0NHILUOAkVGgMQIJAc=,tag:lmECsamzU8TawU1MnL4rMg==,type:str]
    FLYWAY_USER: ENC[AES256_GCM,data:WaejAqNZFkCSamv7ZmGZ+JE=,iv:CQIhA6R4YSKZANlxS+s1sZ+fyI/g5+TS9twRX0Ex9ac=,tag:dFPvUloZnEgnBUFgL/tUXA==,type:str]
    FLYWAY_PASSWORD: ENC[AES256_GCM,data:43A3,iv:lInN3wq7X75TrrHB7TbsrVEMZ9BK8NsA/HIqX/d8eMc=,tag:QX/7K8Okgoh/Mqrkyqdd8w==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWCtlakoveHlTblBTVEpV
            WnVUVjdQUjRKZ0UyMmRjT29rQ3FRR01ZMFdrClEyQ3FraHc1NTRBb1IrbWl2MWdN
            a1pJWE9TWVlTODY5c1pMZzg2bXh4Wm8KLS0tIERKNzdUc0JJRTIwNko1SU9uMjNh
            OXNvWFFLTVdrSm9UdGMyTTVXWm02Sk0KtgoyS9MGMtNgGJoWncDdBfXYEnqJngjE
            Xwc/CtX5h5l9a7jtZMM2JQ2DAnKleZcQxJjlH0oiVfG5YgKNJhkM4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T11:33:32Z"
    mac: ENC[AES256_GCM,data:c+Pvb10CIrvvpK24Kwyk8PsMLfxzSSQCezUPny8CXAS+xFmEGUHwTHzaJo/M2YvcLBE0NQ6d+p71h2MmKS6rp6489P/hBFJpdr1ZXB9rDLsEskTIVkRDqkeODMdzki2p6ZiOItDkpBc1EgwP+1wJaRmCWBywD+DHYvcEgMziwSg=,iv:UnSIZgEPnwyyS4twT8PMeEic2w9LGrdtpQSSZQRqIKk=,tag:OEVCM99CnDtydczUfOYTBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
