# These point to clusters/prod-eu/domains
# That's where the dependsOn DAG is defined
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: cluster-domains
spec:
  interval: 10m
  path: ./clusters/prod-eu/domains
  prune: true
  sourceRef:
    kind: GitRepository
    name: aperitif-repo
  wait: true
  timeout: 10m
  dependsOn:
    - name: cluster-platform
