apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: domains

requires:
  - path: auth

profiles:
  - name: local
    requires:
      - path: auth
        activeProfiles:
          - name: local
