apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nats-depl
spec:
  template:
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: nats
          maxSkew: 1
          topologyKey: kubernetes.io/hostname

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: nats
              topologyKey: kubernetes.io/hostname

      containers:
        - name: nats
          args:
            - --config
            - /etc/nats-config/nats.conf
          envFrom:
            - secretRef:
                name: nats-secrets
          volumeMounts:
            - name: config
              mountPath: /etc/nats-config

      volumes:
        - name: config
          configMap:
            name: nats-config
