apiVersion: viaduct.ai/v1
kind: KSOPS

metadata:
  name: accounts-worker-ksops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - accounts-worker-db.yaml
