version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directories:
      - /domains/*/components/*
      - /domains/*/packages/*
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directories:
      - /domains/*/components/*
    schedule:
      interval: weekly
