apiVersion: apps/v1
kind: Deployment

metadata:
  name: accounts-worker-depl
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: accounts-worker
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: NATS_STREAM_REPLICAS
              value: "3"
