apiVersion: v1
kind: Secret
metadata:
    name: accounts-worker-db
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:9kRnvPyLwztQdIG/SkX5FfIlo/McJxvfEFcDrfFMdkMnJbTyCP2XG7YrW5eDMvm8Ym4roE/lqwmEBjuVtWhHX3jIbk59S4NE1w==,iv:mNvssr/UZN9JF4SXgjxI1ko8y9zPLQRohanItF8Bdec=,tag:saCnqnxOlOK4W+hHsGJ9bg==,type:str]
sops:
    age:
        - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVjVnMDF4cndVMlpaQWEr
            VDNsSHhhZXVKVHlpWUR0UDkwQVNLS01mSWd3CmovdmJtcFZiN2g5OEJrNXBVQ2F0
            ekdKaXNYNVJDK0ZsejBxbXlROVhQdUUKLS0tIEVlOFNkcy85RVR0ZlpuNWNROExH
            Z2paeHhsb1VNbzYreWdGZWpCY3diVjgKlZ4ij83Cdv2MxcWqi+ij89SdSqY/4i9l
            z3MDp+EWhmSAYDhuY1yDlkwkyPVfD8cu5CETxDF0++PEjPAUg8kzVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T08:35:59Z"
    mac: ENC[AES256_GCM,data:ows8f+gHDZouPKCWQb+P6XDy/ZYfewaIDuB/sWmBeFgNSO+19ZerUuFZVp8YHVImtvOBw7ztEm1//qbKgHIwMg+Gjw9KpiflIUxasdBdHc19vH+gI+PIvhxq0gpnpdSNTNHcINiZivoM6TY5GzM1HFyhMfrHSvGj8rfPVql5ywU=,iv:zb3VlBpzfAdhuPB/5BnaOBRdYXwuCnmnefhB/pKKPu8=,tag:hHHrZHtj/panPn2RWk1xNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
