apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - ../../base

patches:
  - path: accounts-worker-depl.yaml

secretGenerator:
  - name: accounts-worker-db
    literals:
      - DATABASE_URL=postgres://postgres@postgres-srv:5432/accounts?sslmode=disable

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: mdstaicu/accounts-worker
    newTag: latest
