apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - namespace.yaml
  - ../../base
  - accounts-worker-db.yaml

patches:
  - path: accounts-worker-depl.yaml

images:
  - name: mdstaicu/accounts-worker
    newTag: latest
