apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: identity-postgres-depl.yaml

configMapGenerator:
  - name: identity-postgres-init
    files:
      - identity-postgres-init.sql
