apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts

resources:
  - ../../base
  - accounts-api-ingress.yaml

patches:
  - path: accounts-api-depl.yaml

images:
  - name: ghcr.io/mstaicu/accounts-api
    newTag: latest
