apiVersion: apps/v1
kind: Deployment

metadata:
  name: identity-ui-depl
spec:
  template:
    spec:
      containers:
        - name: identity-ui
          env:
            - name: OTEL_SERVICE_NAME
              value: identity-ui
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-srv.otel.svc.cluster.local:4318
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
