apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base

patches:
  - path: identity-ui-depl.yaml

images:
  - name: mdstaicu/identity-ui
    # This field is managed by this ImagePolicy: <namespace>:<imagepolicy-name>
    # meaning: flux-system:identity-ui-latest
    newTag: latest # {"$imagepolicy": "flux-system:identity-ui-latest"}
