apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: identity-ui-depl.yaml

images:
  - name: mdstaicu/identity-ui
    newTag: latest
