apiVersion: batch/v1
kind: Job

metadata:
  name: migrate
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: entitlements-migrate
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never

      containers:
        - name: migrate
          image: mdstaicu/entitlements-migrate
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          env:
            - name: FLYWAY_LOCATIONS
              value: filesystem:/db/sql
            - name: FLYWAY_FAIL_ON_MISSING_LOCATIONS
              value: "true"
