apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - networkpolicy.yaml
  - public-docs-ingressroute.yaml
  - public-ingressroute.yaml
  - public-jwks-ingressroute.yaml
  - service.yaml
