apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agent-serviceaccount.yaml
  - agent-clusterrole.yaml
  - agent-clusterrolebinding.yaml
  - agent-daemonset.yaml
  - collector-serviceaccount.yaml
  - collector-clusterrole.yaml
  - collector-clusterrolebinding.yaml
  - collector-deployment.yaml
  - collector-service.yaml
  - openobserve-statefulset.yaml
  - openobserve-service.yaml

configMapGenerator:
  - name: agent
    files:
      - otel-config.yaml=agent-config.yaml
  - name: collector
    files:
      - otel-config.yaml=collector-config.yaml
