apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clickhouseinstallations.yaml
  - clickhouseinstallationtemplates.yaml
  - clickhouseoperatorconfigurations.yaml
  - clickhousekeeperinstallations.yaml
