apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-controller
  template:
    metadata:
      labels:
        app: kustomize-controller
    spec:
      serviceAccountName: kustomize-controller
      containers:
        - name: manager
          image: ghcr.io/fluxcd/kustomize-controller:v1.8.2
          args:
            - --watch-all-namespaces=true
            - --log-level=info
          ports:
            - name: healthz
              containerPort: 9440
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
