apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-controller
  template:
    metadata:
      labels:
        app: source-controller
    spec:
      serviceAccountName: source-controller
      containers:
        - name: manager
          image: ghcr.io/fluxcd/source-controller:v1.8.1
          args:
            - --watch-all-namespaces=true
            - --log-level=info
            - --storage-path=/data
            - --storage-adv-addr=source-controller.flux-system.svc.cluster.local.
          ports:
            - name: http
              containerPort: 9090
            - name: healthz
              containerPort: 9440
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
