apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrolebinding-flux-cluster-admin.yaml
  - deployment-image-automation-controller.yaml
  - deployment-image-reflector-controller.yaml
  - deployment-kustomize-controller.yaml
  - deployment-source-controller.yaml
  - service-source-controller.yaml
  - serviceaccount-image-automation-controller.yaml
  - serviceaccount-image-reflector-controller.yaml
  - serviceaccount-kustomize-controller.yaml
  - serviceaccount-source-controller.yaml
