apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - csidriver.yaml
  - rbac-secretproviderclass.yaml
  - rbac-secretproviderrotation.yaml
  - rbac-secretprovidersyncing.yaml
  - secrets-store-csi-driver.yaml
