apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: step-ca

resources:
  - ../../base
  - namespace.yaml

configMapGenerator:
  - name: step-ca-config
    files:
      - ca.json=ca.json
