apiVersion: v1
kind: Secret
metadata:
  name: identity-migrate-db
stringData:
  FLYWAY_URL: ENC[AES256_GCM,data:Pk6FK+RBov3BfsIUJ1/M9K9I+yq2aFWMzZ3HTCyMHkd6Sf3JzsAJhLi00P7geMToK+/D5NyT6MGpAM3P,iv:vt0B7DV/BSSdBmz4gv6pCb4J1VR1C5ixAbUt47oX4n8=,tag:PbfiZvTbUiKVApyPHEO1ug==,type:str]
  FLYWAY_USER: ENC[AES256_GCM,data:kNpOaitBnacF2GlD9jHTLg0=,iv:2W6WKjtLkGJQFuLo5resDJv4aMhTr54AdOep5dvpPd8=,tag:Stl1DpI23VIMahrJVfr3Xw==,type:str]
  FLYWAY_PASSWORD: ENC[AES256_GCM,data:A7pD,iv:FtiZf0gtASALTdKDr61E+C4FaA2ehsuBIyoChnxn2ow=,tag:FYKnKboCEfoTuQuCveU0Yg==,type:str]
  FLYWAY_LOCATIONS: ENC[AES256_GCM,data:MBX8vSzUG9OrdnIFvIgbxd03hrBPJ51aPUt12l3Z8XZaeqXW+QI10lHa8lk1X2bKUUyn,iv:PEZcqS8TTIxr3kzKib+ClUJG/DE341a63ranrLIoZU4=,tag:sdMoyIPAiLsGqjG5X3HL9g==,type:str]
sops:
  age:
    - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdHZ5R2dkd1JwSUpqQUpo
        ays5Q3ZacVZ5MWc2OWVSRXAxTW5GRW13STFNCklEZnlXUERkTStsTW5sVFNUR1ln
        ZVY2YlNtK3JnUUlXWU8vYlUzUEIrTVEKLS0tIDJxaDREbXlPdlZjcnlFT0EreUtx
        Y0R2Z1hzK1NtS0R0VjFuUy8yYmdMODQK0FllYhfNTUsqQV5RiBCgLlYo4LjZ2awp
        HQt+dc+Zl1ADri8pj8FoPEcB4tUfCTTemf/N0TldsX7kcXsBA0JLPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T21:07:04Z"
  mac: ENC[AES256_GCM,data:GGxUTIfVe+HLajKWk/efnSoo8TPC8lnfXJH7ua6fQeoPuw05jg68B5+EITwSlzP66945did/5yg8YqKCXkO2bfWd8Z+wv3iNnNlGt/dI5wOHsrJtaSNIeOMdZUrrmHr9rFcGzzSqz4799iIavO2heDA4zX2gWSmCejOjdL/Ef9A=,iv:eliXiB+wfXje8SMiUJ1ffaREYbNJcZDuaUccbfLfWkw=,tag:gkFuwVd9I7Y5KW8hfoYoig==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
