apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base
  - identity-migrate-db.yaml

images:
  - name: mdstaicu/identity-migrate
    # This field is managed by this ImagePolicy: <namespace>:<imagepolicy-name>
    # meaning: flux-system:identity-migrate-latest
    newTag: latest # {"$imagepolicy": "flux-system:identity-migrate-latest"}
