apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - namespace.yaml
  - ../../base
  - identity-migrate-db.yaml

images:
  - name: mdstaicu/identity-migrate
    newTag: latest
