apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - namespace.yaml
  - ../../base
  - networkpolicy.yaml
  - ingress.yaml

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: api-config
    literals:
      - ORIGIN=http://localhost
      - JWT_SIGNING_KID=local-2026-09-25

secretGenerator:
  - name: api-jwt
    files:
      - jwks.json=jwks.local.json
