apiVersion: v1
kind: Secret

metadata:
  name: cloudflare-dns
type: Opaque
stringData:
  CF_DNS_API_TOKEN: ENC[AES256_GCM,data:DfblZfWaaWkuQ1c38D39ZBY=,iv:L+gtujv2Py56aPxSCaupcSRF91EuC0ebkrCwu42oxMs=,tag:pArGedhreHAoZr0iOWZs4Q==,type:str]
sops:
  age:
    - recipient: age1m0848yekwnxypu3te3n55845z9mmve8qvu0dqfgs34jgn87meaksdvkyu0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWTBJL2JLRXFBaE9SMElr
        UVZIVTdQZjlERXRScVVOTXZUTVplaFkwc1FrCms1eGJCU0dXMXNMZjVNTjF0VHVQ
        d25FRVZub3RvaDQ2V01MckNJZFlYdk0KLS0tIEwxdzhuR2l2em9UakJVdTNWYitN
        U3d5bUhpcFFieTA2MmR2YlE2MmovSmcKXQNp5RXyjTBh+qTC3MoNuVaBPgqMN8eh
        Njxg72+ZI5DHXPE6Yv3KbkSdvBcYp8h+zQYb+3JtkD68u3uzxzK+lg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-24T11:35:09Z"
  mac: ENC[AES256_GCM,data:AVDbFrtZARhNfrGIYfhqXkbnxiG3kZFOmWqrNW8O505DukMKL0XUUkOaeYoc8QCY+V5dieIeID6B4ogPYcprMgF3+qepoXje5AffnvQux2lj1ubSYJ2NFCNLSRGvoImEWBy3BLhDJiXJQKNwgvYuNRrGhVVguFafVfj2i2olqj0=,iv:99/R9910f2bzLjkXgH6nFR1eE02wPDaeJke3xzJw9iA=,tag:wRKShu/r+FUv89WJ18XkaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
