name: Check

on:
  pull_request:
  merge_group:
    types: [checks_requested]

concurrency:
  group: pull-request-check-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changes:
    name: Find changed components
    runs-on: ubuntu-24.04
    outputs:
      paths: ${{ steps.changes.outputs.all_changed_and_modified_files }}

    steps:
      - name: Check out source
        uses: actions/checkout@v6.1.0
        with:
          fetch-depth: 0

      - id: changes
        name: Find changed components
        uses: tj-actions/changed-files@v47.0.6
        with:
          files: |
            domains/*/**
            platform/*/**
            clusters/*/**
          dir_names: true
          dir_names_max_depth: 2
          output_renamed_files_as_deleted_and_added: true
          fail_on_initial_diff_error: true
          matrix: true

  check:
    name: ${{ matrix.path }}
    needs: changes
    if: needs.changes.outputs.paths != '[]'
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(needs.changes.outputs.paths) }}

    steps:
      - name: Check out source
        uses: actions/checkout@v6.1.0

      - name: Set up Node 26.10.0
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 26.10.0

      - name: Run make check
        env:
          UNIT: ${{ matrix.path }}
        run: make -C "$UNIT" check
