apiVersion: apps/v1
kind: Deployment

metadata:
  name: identity-api
spec:
  template:
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: identity-api
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@identity-postgres:5432/identity"
            - name: OTEL_SERVICE_NAME
              value: identity-api
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://signoz-ingester.signoz.svc.cluster.local:4318
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
