apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base
  - identity-api-jwt.yaml
  - identity-api-ingress.yaml

patches:
  - path: identity-api-depl.yaml

configMapGenerator:
  - name: identity-api-cm
    literals:
      - ORIGIN=https://tma.com

images:
  - name: ghcr.io/mstaicu/identity-api
    newTag: latest
