apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - ../../base
  - identity-api-jwt-secret.yaml
  - identity-api-public-ingressroute.yaml
  - identity-api-public-docs-ingressroute.yaml
  - identity-api-public-jwks-ingressroute.yaml

patches:
  - path: identity-api-deployment.yaml

configMapGenerator:
  - name: identity-api-cm
    literals:
      - ORIGIN=https://tma.com

images:
  - name: ghcr.io/mstaicu/identity-api
    newTag: latest
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000 # {"$imagepolicy": "flux-system:identity-api:digest"}
