apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-postgres

manifests:
  kustomize:
    paths:
      - infra/postgres/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-migrations

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/identity-migrations
      context: components/migrations
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - components/migrations/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-api

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/identity-api
      context: components/api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/api/infra/overlays/ephemeral
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-ui

build:
  local:
    push: false

  artifacts:
    - image: ghcr.io/mstaicu/identity-ui
      context: components/ui
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: app/**/*
            dest: /home/node/app
          - src: public/**/*
            dest: /home/node/app
          - src: server.ts
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - components/ui/infra/overlays/ephemeral

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-cleanup

manifests:
  kustomize:
    paths:
      - infra/cleanup/overlays/ephemeral

deploy:
  kubectl: {}
