apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-postgres-dev

manifests:
  kustomize:
    paths:
      - infra/postgres/overlays/dev

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-migrate-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/identity-migrate
      context: packages/migrate
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - infra/migrate/overlays/dev
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-api-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/identity-api
      context: packages/api
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: src/**/*
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - infra/api/overlays/dev
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: identity-ui-dev

build:
  local:
    push: false

  artifacts:
    - image: mdstaicu/identity-ui
      context: packages/ui
      docker:
        dockerfile: Dockerfile
        target: dev

      sync:
        manual:
          - src: app/**/*
            dest: /home/node/app
          - src: public/**/*
            dest: /home/node/app
          - src: server.ts
            dest: /home/node/app

manifests:
  kustomize:
    paths:
      - infra/ui/overlays/dev

deploy:
  kubectl: {}
