apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: signoz

resources:
  - ../../base
  - clickhouse-srv.yaml
  - otel-config.yaml
  - otel-job.yaml
  - otel-srv.yaml
  - signoz-ns.yaml
  - signoz-srv.yaml

patches:
  - path: clickhouse-statefulset.yaml
  - path: otel-depl.yaml
  - path: signoz-statefulset.yaml
