apiVersion: apps/v1
kind: Deployment

metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      initContainers:
        - name: wait-clickhouse
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z clickhouse 9000; do
                echo "waiting for clickhouse..."
                sleep 2
              done
      containers:
        - name: collector
          args:
            - "--config=/conf/config.yaml"
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: otel-config
