apiVersion: v1
kind: ConfigMap

metadata:
  name: otel-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      clickhousetraces:
        datasource: tcp://admin:password@clickhouse:9000/signoz_traces

      signozclickhousemetrics:
        dsn: tcp://admin:password@clickhouse:9000/signoz_metrics

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhousetraces]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [signozclickhousemetrics]
