apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: signoz
spec:
  serviceName: signoz
  replicas: 1
  selector:
    matchLabels:
      app: signoz
  template:
    metadata:
      labels:
        app: signoz
    spec:
      containers:
        - name: signoz
          image: signoz/signoz:v0.114.1
          ports:
            - containerPort: 8080
            - containerPort: 8085
          env:
            - name: SIGNOZ_TELEMETRYSTORE_PROVIDER
              value: clickhouse
            - name: SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN
              value: tcp://admin:password@clickhouse:9000
          volumeMounts:
            - name: signoz-db
              mountPath: /var/lib/signoz

  volumeClaimTemplates:
    - metadata:
        name: signoz-db
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
