apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - ../../api
  - ../../migrate/local
  - auth-api-ingress.yaml
  - namespace.yaml
  - auth-postgres-depl.yaml

generators:
  - auth-ksops-generator.yaml

patches:
  - path: auth-api-depl.yaml

configMapGenerator:
  - name: auth-api-cm
    literals:
      - ORIGIN=https://tma.com

secretGenerator:
  - name: auth-db
    literals:
      - DATABASE_URL=postgres://postgres@postgres-srv:5432/auth?sslmode=disable

generatorOptions:
  disableNameSuffixHash: true
