apiVersion: viaduct.ai/v1
kind: KSOPS

metadata:
  name: openobserve-ksops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - openobserve-secret.yaml
